<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBMessage;
use MessageBird\Wire\Model\AMBMessageEventList;
use MessageBird\Wire\Model\AMBMessageList;
use MessageBird\Wire\Model\AMBMessageSendRequest;

class AmbBase extends Resource
{
    /**
     * Reads the processing events for a message in your workspace. Use the events to inspect rejections and gateway failures before deciding whether to submit another message.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->listEvents('amb_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function listEvents(string $messageId, ?array $query = null, ?RequestOptions $options = null): AMBMessageEventList
    {
        return $this->single('GET', '/v1/amb/messages/' . rawurlencode($messageId) . '/events', AMBMessageEventList::class, null, $query, $options);
    }

    /**
     * Reads a message in your workspace, including its native content and processing state. Sent records Apple gateway acceptance; a send failure does not rule out an earlier attempt reaching Apple.
     *
     * @example Example
     * $bird->amb->get('amb_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function get(string $messageId, ?RequestOptions $options = null): AMBMessage
    {
        return $this->single('GET', '/v1/amb/messages/' . rawurlencode($messageId), AMBMessage::class, null, null, $options);
    }

    /**
     * Lists your workspace's incoming and outgoing Apple messages with cursor pagination. Filter by business or conversation to inspect one exchange; sent records Apple gateway acceptance.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<AMBMessage>
     *
     * @example Example
     * $bird->amb->list(['business_account_id' => 'abz_01krdgeqcxet5s7t44vh8rt9mg', 'limit' => '2']);
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            AMBMessage::class,
            fn (?string $cursor): AMBMessageList => $this->single('GET', '/v1/amb/messages', AMBMessageList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AMBMessageList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AMBMessageList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Queues a billable reply to an open customer conversation. Requires a configured business, regardless of onboarding status. Apple decides whether to accept the message. Use the business's apple_business_id as from and the conversation's recipient.opaque_user_id as to. Sent records Apple gateway acceptance; device delivery and read receipts are unavailable.
     *
     * @example Example
     * $bird->amb->send((new Model\AMBMessageSendRequest())->setFrom('b52d6267-2b62-4f8a-8842-0533d0f1dc07')->setTo('opaque-customer')->setContent(['type' => 'text', 'body' => 'Your order is ready.']));
     */
    public function send(AMBMessageSendRequest $params, ?RequestOptions $options = null): AMBMessage
    {
        return $this->single('POST', '/v1/amb/messages', AMBMessage::class, $params, null, $options);
    }
}
