<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBBusinessAccountSubmission;
use MessageBird\Wire\Model\AMBBusinessAccountSubmissionCreate;
use MessageBird\Wire\Model\AMBBusinessAccountSubmissionList;

final class AmbBusinessAccountsSubmissions extends Resource
{
    /**
     * Lists the review attempts for a business in your workspace. Each attempt retains the business identity and evidence selected at submission.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<AMBBusinessAccountSubmission>
     *
     * @example Example
     * foreach ($bird->amb->businessAccounts->submissions->list('abz_01krdgeqcxet5s7t44vh8rt9mg', ['limit' => '2']) as $item) {
     *     var_dump($item);
     * }
     */
    public function list(string $businessAccountId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            AMBBusinessAccountSubmission::class,
            fn (?string $cursor): AMBBusinessAccountSubmissionList => $this->single('GET', '/v1/amb/business-accounts/' . rawurlencode($businessAccountId) . '/submissions', AMBBusinessAccountSubmissionList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AMBBusinessAccountSubmissionList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AMBBusinessAccountSubmissionList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Submits an account for review, making its name, Apple UUID and three uploaded evidence attachments available to Bird staff. This does not approve the account.
     *
     * @example Example
     * $bird->amb->businessAccounts->submissions->create(
     *     'abz_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new Model\AMBBusinessAccountSubmissionCreate())
     *         ->setReadinessAttachmentId('tca_01krdgeqcxet5s7t44vh8rt9mg')
     *         ->setUseCasesAttachmentId('tca_01krdgeqcxet5s7t44vh8rt9mh')
     *         ->setVideoAttachmentId('tca_01krdgeqcxet5s7t44vh8rt9mj'),
     * );
     */
    public function create(string $businessAccountId, AMBBusinessAccountSubmissionCreate $params, ?RequestOptions $options = null): AMBBusinessAccountSubmission
    {
        return $this->single('POST', '/v1/amb/business-accounts/' . rawurlencode($businessAccountId) . '/submissions', AMBBusinessAccountSubmission::class, $params, null, $options);
    }
}
