<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBBusinessAccount;
use MessageBird\Wire\Model\AMBBusinessAccountCreate;
use MessageBird\Wire\Model\AMBBusinessAccountList;
use MessageBird\Wire\Model\AMBBusinessAccountUpdate;

class AmbBusinessAccountsBase extends Resource
{
    /**
     * Stops new and queued sends while retaining the account, Apple UUID, approval, credentials and history. Repeated disconnects succeed without changing history. An already-started send attempt may finish; provider requests cannot be recalled. This is a local Bird connection change, not Apple deregistration.
     *
     * @example Example
     * $bird->amb->businessAccounts->delete('abz_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function delete(string $businessAccountId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/amb/business-accounts/' . rawurlencode($businessAccountId), null, null, $options);
    }

    /**
     * Restores the local connection. The retained approval and suspension state still determines whether the account can send. Repeated reconnects return the current account.
     *
     * @example Example
     * $bird->amb->businessAccounts->reconnect('abz_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function reconnect(string $businessAccountId, ?RequestOptions $options = null): AMBBusinessAccount
    {
        return $this->single('POST', '/v1/amb/business-accounts/' . rawurlencode($businessAccountId) . '/reconnect', AMBBusinessAccount::class, null, null, $options);
    }

    /**
     * Reads a business record in your workspace. Its apple_business_id supplies the from field for sends; creating a draft does not establish Apple approval.
     *
     * @example Example
     * $bird->amb->businessAccounts->get('abz_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function get(string $businessAccountId, ?RequestOptions $options = null): AMBBusinessAccount
    {
        return $this->single('GET', '/v1/amb/business-accounts/' . rawurlencode($businessAccountId), AMBBusinessAccount::class, null, null, $options);
    }

    /**
     * Updates a business in your workspace, leaving omitted fields unchanged. Changing Apple's business UUID does not submit the record or change its approval state.
     *
     * @example Example
     * $bird->amb->businessAccounts->update('abz_01krdgeqcxet5s7t44vh8rt9mg', (new Model\AMBBusinessAccountUpdate())->setName('Acme Support'));
     */
    public function update(string $businessAccountId, AMBBusinessAccountUpdate $params, ?RequestOptions $options = null): AMBBusinessAccount
    {
        return $this->single('PATCH', '/v1/amb/business-accounts/' . rawurlencode($businessAccountId), AMBBusinessAccount::class, $params, null, $options);
    }

    /**
     * Lists the Apple businesses registered in your workspace, with cursor pagination. Requires business-management read permission. Use the configured apple_business_id when sending; onboarding status does not gate messaging.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<AMBBusinessAccount>
     *
     * @example Example
     * foreach ($bird->amb->businessAccounts->list(['limit' => '2']) as $item) {
     *     var_dump($item);
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            AMBBusinessAccount::class,
            fn (?string $cursor): AMBBusinessAccountList => $this->single('GET', '/v1/amb/business-accounts', AMBBusinessAccountList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AMBBusinessAccountList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AMBBusinessAccountList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Creates a draft business in your workspace. Supplying Apple's business UUID does not submit the record; upload evidence and create a submission when ready for review.
     *
     * @example Example
     * $bird->amb->businessAccounts->create((new Model\AMBBusinessAccountCreate())->setName('Acme Retail')->setAppleBusinessId('b52d6267-2b62-4f8a-8842-0533d0f1dc07'));
     */
    public function create(AMBBusinessAccountCreate $params, ?RequestOptions $options = null): AMBBusinessAccount
    {
        return $this->single('POST', '/v1/amb/business-accounts', AMBBusinessAccount::class, $params, null, $options);
    }
}
