<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBChannelSettings;
use MessageBird\Wire\Model\AMBChannelSettingsUpdate;

final class AmbBusinessAccountsSettings extends Resource
{
    /**
     * Returns the channel settings for your workspace's Apple Messages for Business record: its entry points, default locale, and the brand name and logo shown on the landing page customers use to connect it.
     *
     * @example Example
     * $bird->amb->businessAccounts->settings->get('abz_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function get(string $businessAccountId, ?RequestOptions $options = null): AMBChannelSettings
    {
        return $this->single('GET', '/v1/amb/business-accounts/' . rawurlencode($businessAccountId) . '/channel-settings', AMBChannelSettings::class, null, null, $options);
    }

    /**
     * Changes the channel settings for your workspace's Apple Messages for Business record. Fields you omit are left as they are, except `entry_points`: sending it replaces the entire set, since there is no way to add or remove a single entry point without resending the rest.
     *
     * @example Example
     * $bird->amb->businessAccounts->settings->update('abz_01krdgeqcxet5s7t44vh8rt9mg', (new Model\AMBChannelSettingsUpdate())->setBrandName('Acme Support')->setLogoAssetId(null));
     */
    public function update(string $businessAccountId, AMBChannelSettingsUpdate $params, ?RequestOptions $options = null): AMBChannelSettings
    {
        return $this->single('PATCH', '/v1/amb/business-accounts/' . rawurlencode($businessAccountId) . '/channel-settings', AMBChannelSettings::class, $params, null, $options);
    }
}
