<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBConversation;
use MessageBird\Wire\Model\AMBConversationList;
use MessageBird\Wire\Model\AMBConversationTypingRequest;
use MessageBird\Wire\Model\AMBConversationUpdate;
use MessageBird\Wire\Model\AMBMessage;
use MessageBird\Wire\Model\AMBMessageList;

final class AmbConversations extends Resource
{
    /**
     * Reads a customer-initiated conversation in your workspace. Its opaque_user_id supplies the to field for replies; verify the business and open state before sending.
     *
     * @example Example
     * $bird->amb->conversations->get('acv_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function get(string $conversationId, ?RequestOptions $options = null): AMBConversation
    {
        return $this->single('GET', '/v1/amb/conversations/' . rawurlencode($conversationId), AMBConversation::class, null, null, $options);
    }

    /**
     * Updates assignment, labels and read state on a workspace conversation. Omitted fields stay unchanged; null assigned_to unassigns, empty labels clears labels, and read false has no effect. This operation does not close or reopen a conversation.
     *
     * @example Example
     * $bird->amb->conversations->update('acv_01krdgeqcxet5s7t44vh8rt9mg', (new Model\AMBConversationUpdate())->setAssignedTo(null)->setLabels([])->setRead(false));
     */
    public function update(string $conversationId, AMBConversationUpdate $params, ?RequestOptions $options = null): AMBConversation
    {
        return $this->single('PATCH', '/v1/amb/conversations/' . rawurlencode($conversationId), AMBConversation::class, $params, null, $options);
    }

    /**
     * Returns the messages in a conversation, newest first, both received and sent. To page through older messages, use `starting_after`. The sort order is fixed, so to render the messages in conversation order, reverse the page yourself.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<AMBMessage>
     *
     * @example Example
     * foreach ($bird->amb->conversations->listMessages('acv_01krdgeqcxet5s7t44vh8rt9mg', ['limit' => '2']) as $item) {
     *     var_dump($item);
     * }
     */
    public function listMessages(string $conversationId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            AMBMessage::class,
            fn (?string $cursor): AMBMessageList => $this->single('GET', '/v1/amb/conversations/' . rawurlencode($conversationId) . '/messages', AMBMessageList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AMBMessageList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AMBMessageList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Sends a typing signal through Apple for an existing conversation. Typing is best effort; typing_end still needs native device verification. It does not enqueue a billable message.
     *
     * @example Example
     * $bird->amb->conversations->typing('acv_01krdgeqcxet5s7t44vh8rt9mg', (new Model\AMBConversationTypingRequest())->setEvent('typing_start'));
     */
    public function typing(string $conversationId, AMBConversationTypingRequest $params, ?RequestOptions $options = null): void
    {
        $this->none('POST', '/v1/amb/conversations/' . rawurlencode($conversationId) . '/typing', $params, null, $options);
    }

    /**
     * Returns the conversations your business has with customers on Apple Messages for Business, newest first by last message. To page through older conversations, use `starting_after`. A closed conversation stays in this list; filter on `status` to separate them from open ones.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<AMBConversation>
     *
     * @example Example
     * foreach ($bird->amb->conversations->list(['business_account_id' => 'abz_01krdgeqcxet5s7t44vh8rt9mg', 'limit' => '2']) as $item) {
     *     var_dump($item);
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            AMBConversation::class,
            fn (?string $cursor): AMBConversationList => $this->single('GET', '/v1/amb/conversations', AMBConversationList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AMBConversationList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AMBConversationList);

                return $page->getNextCursor();
            },
        );
    }
}
