<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBRoutingRule;
use MessageBird\Wire\Model\AMBRoutingRuleCreate;
use MessageBird\Wire\Model\AMBRoutingRuleList;
use MessageBird\Wire\Model\AMBRoutingRuleUpdate;

final class AmbRoutingRules extends Resource
{
    /**
     * Returns one routing rule by ID.
     *
     * @example Example
     * $bird->amb->routingRules->get('arr_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function get(string $routingRuleId, ?RequestOptions $options = null): AMBRoutingRule
    {
        return $this->single('GET', '/v1/amb/routing-rules/' . rawurlencode($routingRuleId), AMBRoutingRule::class, null, null, $options);
    }

    /**
     * Changes a routing rule's business, match, queue, precedence, or default status. The match changes as a unit: send `match_kind` with the intent and group ids it requires, as on create. Returns a `409` when the update would leave this rule as the default of a business that already has a different default rule.
     *
     * @example Example
     * $bird->amb->routingRules->update('arr_01krdgeqcxet5s7t44vh8rt9mg', (new Model\AMBRoutingRuleUpdate())->setQueue('sales')->setPrecedence(0)->setIsDefault(false));
     */
    public function update(string $routingRuleId, AMBRoutingRuleUpdate $params, ?RequestOptions $options = null): AMBRoutingRule
    {
        return $this->single('PATCH', '/v1/amb/routing-rules/' . rawurlencode($routingRuleId), AMBRoutingRule::class, $params, null, $options);
    }

    /**
     * Deletes a routing rule. A conversation already routed by it keeps its queue; only newly created or reopened conversations stop matching it. Deleting a business's default rule leaves it with none, so unmatched conversations route to an empty queue until you create another.
     *
     * @example Example
     * $bird->amb->routingRules->delete('arr_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function delete(string $routingRuleId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/amb/routing-rules/' . rawurlencode($routingRuleId), null, null, $options);
    }

    /**
     * Returns the workspace's Apple Messages for Business routing rules, highest precedence first. Rules run when a conversation is created, when a closed conversation reopens, and when a customer writes to a resolved conversation, matching its group and intent to a queue. A message without a group or intent routes on the conversation's stored values. Later messages while the conversation is open in the inbox retain its queue.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $rules = $bird->amb->routingRules->list(['business_account_id' => 'abz_01krdgeqcxet5s7t44vh8rt9mg']);
     * var_dump($rules->getData());
     */
    public function list(?array $query = null, ?RequestOptions $options = null): AMBRoutingRuleList
    {
        return $this->single('GET', '/v1/amb/routing-rules', AMBRoutingRuleList::class, null, $query, $options);
    }

    /**
     * Creates a routing rule for one of your Apple Messages for Business brands. Set `is_default` to make it the rule that catches a conversation matching nothing else. A business can have only one default rule, and creating a second while one exists returns a `409`.
     *
     * @example Example
     * $bird->amb->routingRules->create((new Model\AMBRoutingRuleCreate())->setBusinessAccountId('abz_01krdgeqcxet5s7t44vh8rt9mg')->setMatchKind('intent')->setMatchIntentId('support')->setQueue('support')->setPrecedence(0)->setIsDefault(false)->setMatchGroupId(null));
     */
    public function create(AMBRoutingRuleCreate $params, ?RequestOptions $options = null): AMBRoutingRule
    {
        return $this->single('POST', '/v1/amb/routing-rules', AMBRoutingRule::class, $params, null, $options);
    }
}
