<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBStatsByBusinessResponse;
use MessageBird\Wire\Model\AMBStatsByCategoryResponse;
use MessageBird\Wire\Model\AMBStatsByErrorCodeResponse;
use MessageBird\Wire\Model\AMBStatsByGroupResponse;
use MessageBird\Wire\Model\AMBStatsByIntentResponse;
use MessageBird\Wire\Model\AMBStatsByMessageKindResponse;
use MessageBird\Wire\Model\AMBStatsByTagResponse;
use MessageBird\Wire\Model\AMBStatsResponse;
use MessageBird\Wire\Model\AMBStatsSummary;

class AmbStatsBase extends Resource
{
    /**
     * Returns outbound counts and latency percentiles grouped by business, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->byBusiness(['limit' => '2']);
     */
    public function byBusiness(?array $query = null, ?RequestOptions $options = null): AMBStatsByBusinessResponse
    {
        return $this->single('GET', '/v1/amb/stats/businesses', AMBStatsByBusinessResponse::class, null, $query, $options);
    }

    /**
     * Returns outbound counts and latency percentiles grouped by message category, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). A send that names no category is grouped under an empty-string category. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->byCategory(['limit' => '2']);
     */
    public function byCategory(?array $query = null, ?RequestOptions $options = null): AMBStatsByCategoryResponse
    {
        return $this->single('GET', '/v1/amb/stats/categories', AMBStatsByCategoryResponse::class, null, $query, $options);
    }

    /**
     * Returns one row of outbound Apple Messages for Business counts and processing-latency percentiles per calendar day for the workspace, gap-filled so a silent day is a zero row rather than a missing one. Every count in a row is attributed to the day its message was accepted, regardless of when a later event, such as a send failure, arrived.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->daily(['business_account_id' => 'abz_01krdgeqcxet5s7t44vh8rt9mg']);
     */
    public function daily(?array $query = null, ?RequestOptions $options = null): AMBStatsResponse
    {
        return $this->single('GET', '/v1/amb/stats/daily', AMBStatsResponse::class, null, $query, $options);
    }

    /**
     * Returns outbound counts and latency percentiles grouped by failure reason, for the requested period. Rows are ranked by `send_failed + rejected` descending and capped at the requested `limit` (default 50, max 200). Only messages carrying a failure reason appear: a `bird:` code is usually a rejection (never charged, never attempted), an `apple:` code a send failure; use the summary for the period's full accepted total.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->byErrorCode(['limit' => '2']);
     */
    public function byErrorCode(?array $query = null, ?RequestOptions $options = null): AMBStatsByErrorCodeResponse
    {
        return $this->single('GET', '/v1/amb/stats/error-codes', AMBStatsByErrorCodeResponse::class, null, $query, $options);
    }

    /**
     * Returns outbound counts and latency percentiles grouped by entry-point group, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Groups are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->byGroup(['limit' => '2']);
     */
    public function byGroup(?array $query = null, ?RequestOptions $options = null): AMBStatsByGroupResponse
    {
        return $this->single('GET', '/v1/amb/stats/groups', AMBStatsByGroupResponse::class, null, $query, $options);
    }

    /**
     * Returns one row of outbound Apple Messages for Business counts and processing-latency percentiles per hour, gap-filled so a silent hour is a zero row rather than a missing one. Every count in a row is attributed to the hour its message was accepted, regardless of when a later event, such as a send failure, arrived. Use it where the daily grain hides the shape; a window spans at most 720 hours (30 days), and for anything longer use `amb.stats.daily`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->hourly(['business_account_id' => 'abz_01krdgeqcxet5s7t44vh8rt9mg']);
     */
    public function hourly(?array $query = null, ?RequestOptions $options = null): AMBStatsResponse
    {
        return $this->single('GET', '/v1/amb/stats/hourly', AMBStatsResponse::class, null, $query, $options);
    }

    /**
     * Returns outbound counts and latency percentiles grouped by entry-point intent, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Intents are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->byIntent(['limit' => '2']);
     */
    public function byIntent(?array $query = null, ?RequestOptions $options = null): AMBStatsByIntentResponse
    {
        return $this->single('GET', '/v1/amb/stats/intents', AMBStatsByIntentResponse::class, null, $query, $options);
    }

    /**
     * Returns outbound counts and latency percentiles grouped by message content kind, for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period. Each row also carries `first_response` latency percentiles, omitted when no qualifying message contributes a measurement.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->byMessageKind(['limit' => '2']);
     */
    public function byMessageKind(?array $query = null, ?RequestOptions $options = null): AMBStatsByMessageKindResponse
    {
        return $this->single('GET', '/v1/amb/stats/message-kinds', AMBStatsByMessageKindResponse::class, null, $query, $options);
    }

    /**
     * Returns one aggregate row of outbound Apple Messages for Business counts and latency percentiles (`p50`, `p95`, and `p99`) for the requested period. Counts are attributed to the time each message was accepted, so a send failure recorded today counts against the day its message was accepted; `period.data_as_of` is the freshness boundary the rollups have reached.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->summary(['business_account_id' => 'abz_01krdgeqcxet5s7t44vh8rt9mg']);
     */
    public function summary(?array $query = null, ?RequestOptions $options = null): AMBStatsSummary
    {
        return $this->single('GET', '/v1/amb/stats/summary', AMBStatsSummary::class, null, $query, $options);
    }

    /**
     * Returns outbound counts and latency percentiles grouped by tag (`name` or `name:value`), for the requested period. Rows are ranked by accepted volume descending and capped at the requested `limit` (default 50, max 200). Only tagged messages appear, and one carrying several tags counts once under each, so rows do not sum to the period total. Rows use accepted-time attribution: a send failure recorded during the period for a message accepted earlier counts against the earlier period.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->byTag(['limit' => '2']);
     */
    public function byTag(?array $query = null, ?RequestOptions $options = null): AMBStatsByTagResponse
    {
        return $this->single('GET', '/v1/amb/stats/tags', AMBStatsByTagResponse::class, null, $query, $options);
    }
}
