<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBConversationStatsResponse;
use MessageBird\Wire\Model\AMBConversationStatsSummary;

final class AmbStatsConversations extends Resource
{
    /**
     * Returns one row of Apple Messages for Business conversation lifecycle counts (`started`, `reopened`, `closed`, `conversations`) per calendar day for the workspace, gap-filled so a silent day is a zero row rather than a missing one. Every row is attributed to the day the lifecycle event occurred, not to any earlier outbound message. A conversation can be reopened and closed more than once, so `started`, `reopened`, and `closed` need not sum to `conversations` within a row, and any one of them can exceed it.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->conversations->daily();
     */
    public function daily(?array $query = null, ?RequestOptions $options = null): AMBConversationStatsResponse
    {
        return $this->single('GET', '/v1/amb/stats/conversations/daily', AMBConversationStatsResponse::class, null, $query, $options);
    }

    /**
     * Returns one row of Apple Messages for Business conversation lifecycle counts (`started`, `reopened`, `closed`, `conversations`) per hour, gap-filled so a silent hour is a zero row rather than a missing one. Every row is attributed to the hour the lifecycle event occurred, not to any earlier outbound message. A conversation can be reopened and closed more than once, so `started`, `reopened`, and `closed` need not sum to `conversations` within a row, and any one of them can exceed it.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->conversations->hourly();
     */
    public function hourly(?array $query = null, ?RequestOptions $options = null): AMBConversationStatsResponse
    {
        return $this->single('GET', '/v1/amb/stats/conversations/hourly', AMBConversationStatsResponse::class, null, $query, $options);
    }

    /**
     * Returns one aggregate row of Apple Messages for Business conversation lifecycle counts (`started`, `reopened`, `closed`, `conversations`) for the requested period. Rows are attributed to when the lifecycle event occurred, not to any earlier outbound message. A conversation can be reopened and closed more than once, so `started`, `reopened`, and `closed` need not sum to `conversations`, and any one of them can exceed it. `period.data_as_of` is the freshness boundary the rollups have reached.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->conversations->summary();
     */
    public function summary(?array $query = null, ?RequestOptions $options = null): AMBConversationStatsSummary
    {
        return $this->single('GET', '/v1/amb/stats/conversations/summary', AMBConversationStatsSummary::class, null, $query, $options);
    }
}
