<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBSuppression;
use MessageBird\Wire\Model\AMBSuppressionCreate;
use MessageBird\Wire\Model\AMBSuppressionList;

final class AmbSuppressions extends Resource
{
    /**
     * Returns the suppression episode for the given ID, including one that has already ended. An ended episode keeps its dates and reports when and how it ended.
     *
     * @example Example
     * $bird->amb->suppressions->get('asp_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function get(string $suppressionId, ?RequestOptions $options = null): AMBSuppression
    {
        return $this->single('GET', '/v1/amb/suppressions/' . rawurlencode($suppressionId), AMBSuppression::class, null, null, $options);
    }

    /**
     * Ends a manual suppression while retaining its history. Recipient opt-outs and automatic conversation facts cannot be ended through this endpoint.
     *
     * @example Example
     * $bird->amb->suppressions->delete('asp_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function delete(string $suppressionId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/amb/suppressions/' . rawurlencode($suppressionId), null, null, $options);
    }

    /**
     * Returns a paginated list of the workspace's active Apple Messages for Business suppressions: customers who have opted out of one brand, or of the whole workspace. Episodes that have ended are left out; fetch one by ID to read it. Filter by `business_account_id` to see one brand's suppressions, including the workspace-wide ones that block it too.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<AMBSuppression>
     *
     * @example Example
     * foreach ($bird->amb->suppressions->list(['business_account_id' => 'abz_01krdgeqcxet5s7t44vh8rt9mg', 'limit' => '2']) as $item) {
     *     var_dump($item);
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            AMBSuppression::class,
            fn (?string $cursor): AMBSuppressionList => $this->single('GET', '/v1/amb/suppressions', AMBSuppressionList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AMBSuppressionList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AMBSuppressionList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Manually opens a suppression episode for a address, blocking every outbound path to it: operator and automated replies, API sends, typing indicators, and invitations. Set `business_account_id` to block the address for one brand only, or omit it to block the address for every brand in the workspace. If the address already has an active episode with reason `manual`, the API returns `200` with the existing episode instead of creating a second one.
     *
     * @example Example
     * $bird->amb->suppressions->create((new Model\AMBSuppressionCreate())->setAddress('opaque-customer')->setAddressType('opaque_user_id'));
     */
    public function create(AMBSuppressionCreate $params, ?RequestOptions $options = null): AMBSuppression
    {
        return $this->single('POST', '/v1/amb/suppressions', AMBSuppression::class, $params, null, $options);
    }
}
