<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AMBInboundStatsByBusinessResponse;
use MessageBird\Wire\Model\AMBInboundStatsByIntentResponse;
use MessageBird\Wire\Model\AMBInboundStatsResponse;
use MessageBird\Wire\Model\AMBInboundStatsSummary;

final class AmbStatsInbound extends Resource
{
    /**
     * Returns inbound received counts grouped by business, for the requested period. Rows are ranked by received volume descending and capped at the requested `limit` (default 50, max 200). Rows are attributed to when the inbound event occurred, not to any earlier outbound message. This channel has no delivery receipt and no derived rate, so each row carries only the raw `received` count. The maximum window is 365 days; a longer range returns `422`. Historical dates are supported within the maximum window length; the requested dates are not shifted forward.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->inbound->byBusiness(['limit' => '2']);
     */
    public function byBusiness(?array $query = null, ?RequestOptions $options = null): AMBInboundStatsByBusinessResponse
    {
        return $this->single('GET', '/v1/amb/stats/inbound/businesses', AMBInboundStatsByBusinessResponse::class, null, $query, $options);
    }

    /**
     * Returns one row of inbound Apple Messages for Business counts per calendar day for the workspace, gap-filled so a silent day is a zero row rather than a missing one. Every row is attributed to the day the inbound event occurred, not to any earlier outbound message.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->inbound->daily();
     */
    public function daily(?array $query = null, ?RequestOptions $options = null): AMBInboundStatsResponse
    {
        return $this->single('GET', '/v1/amb/stats/inbound/daily', AMBInboundStatsResponse::class, null, $query, $options);
    }

    /**
     * Returns one row of inbound Apple Messages for Business counts per hour, gap-filled so a silent hour is a zero row rather than a missing one. Every row is attributed to the hour the inbound event occurred, not to any earlier outbound message. Use it where the daily grain hides the shape; a window spans at most 720 hours (30 days), and for anything longer use `amb.stats.inbound.daily`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->inbound->hourly();
     */
    public function hourly(?array $query = null, ?RequestOptions $options = null): AMBInboundStatsResponse
    {
        return $this->single('GET', '/v1/amb/stats/inbound/hourly', AMBInboundStatsResponse::class, null, $query, $options);
    }

    /**
     * Returns inbound received counts grouped by entry-point intent, for the requested period. Rows are ranked by received volume descending and capped at the requested `limit` (default 50, max 200). Intents are workspace-defined strings configured on the business's entry points and have no fixed vocabulary. Rows are attributed to when the inbound event occurred, not to any earlier outbound message. This channel has no delivery receipt and no derived rate, so each row carries only the raw `received` count.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->inbound->byIntent(['limit' => '2']);
     */
    public function byIntent(?array $query = null, ?RequestOptions $options = null): AMBInboundStatsByIntentResponse
    {
        return $this->single('GET', '/v1/amb/stats/inbound/intents', AMBInboundStatsByIntentResponse::class, null, $query, $options);
    }

    /**
     * Returns one aggregate row of inbound Apple Messages for Business counts for the requested period. Inbound statistics are attributed to when the event occurred, not to any earlier outbound message, so a reply received today counts against today regardless of when the conversation started. `period.data_as_of` is the freshness boundary the rollups have reached.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Example
     * $bird->amb->stats->inbound->summary();
     */
    public function summary(?array $query = null, ?RequestOptions $options = null): AMBInboundStatsSummary
    {
        return $this->single('GET', '/v1/amb/stats/inbound/summary', AMBInboundStatsSummary::class, null, $query, $options);
    }
}
