<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Audience;
use MessageBird\Wire\Model\AudienceContactsAddRequest;
use MessageBird\Wire\Model\AudienceContactsRemoveRequest;
use MessageBird\Wire\Model\AudienceCreateRequest;
use MessageBird\Wire\Model\AudienceList;
use MessageBird\Wire\Model\AudienceMember;
use MessageBird\Wire\Model\AudienceMemberList;
use MessageBird\Wire\Model\AudienceUpdateRequest;

final class Audiences extends Resource
{
    /**
     * List the workspace's audiences as a cursor page, newest first. Filter by name substring with `q`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<Audience>
     *
     * @example Iterate every audience across pages
     * foreach ($bird->audiences->list() as $audience) {
     *     echo $audience->getId(), ' ', $audience->getName(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            Audience::class,
            fn (?string $cursor): AudienceList => $this->single('GET', '/v1/audiences', AudienceList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AudienceList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AudienceList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get a single audience by ID: name, description, and type. Members are listed separately with `audiences.list_contacts`.
     *
     * @example Fetch an audience by id
     * $audience = $bird->audiences->get('adn_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $audience->getName();
     */
    public function get(string $audienceId, ?RequestOptions $options = null): Audience
    {
        return $this->single('GET', '/v1/audiences/' . rawurlencode($audienceId), Audience::class, null, null, $options);
    }

    /**
     * Create an audience in the workspace. New audiences start empty; add contacts with `audiences.add_contacts` or `contacts.batch`. Only static audiences can be created today.
     *
     * @example Create an audience
     * $audience = $bird->audiences->create(
     *     (new AudienceCreateRequest())->setName('Newsletter subscribers'),
     * );
     * echo $audience->getId(); // "adn_…"
     */
    public function create(AudienceCreateRequest $params, ?RequestOptions $options = null): Audience
    {
        return $this->single('POST', '/v1/audiences', Audience::class, $params, null, $options);
    }

    /**
     * Update an audience's name or description. Omitted fields are unchanged; a null description clears it.
     *
     * @example Rename an audience
     * $bird->audiences->update(
     *     'adn_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new AudienceUpdateRequest())->setName('Renamed'),
     * );
     */
    public function update(string $audienceId, AudienceUpdateRequest $params, ?RequestOptions $options = null): Audience
    {
        return $this->single('PATCH', '/v1/audiences/' . rawurlencode($audienceId), Audience::class, $params, null, $options);
    }

    /**
     * Delete an audience and its memberships; contacts themselves are not deleted. Fails while a broadcast targeting the audience is scheduled, accepted, sending, or canceling.
     *
     * @example Delete an audience by id
     * $bird->audiences->delete('adn_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function delete(string $audienceId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/audiences/' . rawurlencode($audienceId), null, null, $options);
    }

    /**
     * List the contacts in a static audience by ID, as a cursor page ordered by when each contact joined (most recent first). Each entry pairs the contact with its join time.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<AudienceMember>
     *
     * @example Iterate an audience's members
     * foreach ($bird->audiences->listContacts('adn_01krdgeqcxet5s7t44vh8rt9mg') as $member) {
     *     echo $member->getContact()?->getId(), ' ', $member->getJoinedAt()?->format(DATE_ATOM), "\n";
     * }
     */
    public function listContacts(string $audienceId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            AudienceMember::class,
            fn (?string $cursor): AudienceMemberList => $this->single('GET', '/v1/audiences/' . rawurlencode($audienceId) . '/contacts', AudienceMemberList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AudienceMemberList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AudienceMemberList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Add up to 1,000 existing contacts to a static audience by ID. Fails entirely if any contact ID does not exist. To add contacts you have not created yet, use `contacts.batch` with `audience_ids` instead: it matches or creates each contact by email address and assigns it to the audience in one call.
     *
     * @example Add contacts to an audience
     * $bird->audiences->addContacts(
     *     'adn_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new AudienceContactsAddRequest())->setContactIds(['con_01krdgeqcxet5s7t44vh8rt9mg']),
     * );
     */
    public function addContacts(string $audienceId, AudienceContactsAddRequest $params, ?RequestOptions $options = null): void
    {
        $this->none('POST', '/v1/audiences/' . rawurlencode($audienceId) . '/contacts', $params, null, $options);
    }

    /**
     * Remove up to 1,000 contacts from a static audience by ID. Fails entirely if any contact ID does not exist; contacts are not deleted.
     *
     * @example Remove contacts from an audience
     * $bird->audiences->removeContacts(
     *     'adn_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new AudienceContactsRemoveRequest())->setContactIds(['con_01krdgeqcxet5s7t44vh8rt9mg']),
     * );
     */
    public function removeContacts(string $audienceId, AudienceContactsRemoveRequest $params, ?RequestOptions $options = null): void
    {
        $this->none('POST', '/v1/audiences/' . rawurlencode($audienceId) . '/contacts/remove', $params, null, $options);
    }

    /**
     * Remove one contact's membership from an audience. The contact itself is not deleted and stays a member of any other audiences.
     *
     * @example Remove one contact's membership
     * $bird->audiences->removeContact(
     *     'adn_01krdgeqcxet5s7t44vh8rt9mg',
     *     'con_01krdgeqcxet5s7t44vh8rt9mg',
     * );
     */
    public function removeContact(string $audienceId, string $contactId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/audiences/' . rawurlencode($audienceId) . '/contacts/' . rawurlencode($contactId), null, null, $options);
    }
}
