<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Contact;
use MessageBird\Wire\Model\ContactCreateRequest;
use MessageBird\Wire\Model\ContactList;
use MessageBird\Wire\Model\ContactUpdateRequest;
use MessageBird\Wire\Model\ContactUpsertRequest;
use MessageBird\Wire\Model\ContactUpsertResult;

final class Contacts extends Resource
{
    /**
     * List the workspace's contacts as a cursor page, newest first. Look one up by exact email or external_id, or search by email/name substring. Pass include_total for a total count.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<Contact>
     *
     * @example Iterate every contact across pages
     * foreach ($bird->contacts->list(['q' => 'acme.com']) as $contact) {
     *     echo $contact->getId(), ' ', $contact->getEmail(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            Contact::class,
            fn (?string $cursor): ContactList => $this->single('GET', '/v1/contacts', ContactList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof ContactList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof ContactList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get a single contact by ID (`con_`-prefixed). Look up an ID by exact email or external_id with `contacts.list`.
     *
     * @example Fetch a contact by id
     * $contact = $bird->contacts->get('con_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $contact->getEmail(), ' ', $contact->getFirstName();
     */
    public function get(string $contactId, ?RequestOptions $options = null): Contact
    {
        return $this->single('GET', '/v1/contacts/' . rawurlencode($contactId), Contact::class, null, null, $options);
    }

    /**
     * Create a contact by email address in the workspace. Fails with a conflict if the email or external_id is already used by another contact. For bulk import or create-or-update semantics use `contacts.batch`.
     *
     * @example Create a contact
     * $contact = $bird->contacts->create(
     *     (new ContactCreateRequest())
     *         ->setEmail('jane@acme.com')
     *         ->setFirstName('Jane'),
     * );
     * echo $contact->getId(); // "con_…"
     */
    public function create(ContactCreateRequest $params, ?RequestOptions $options = null): Contact
    {
        return $this->single('POST', '/v1/contacts', Contact::class, $params, null, $options);
    }

    /**
     * Update a contact's name, external_id, email, or custom data. Only supplied fields change; custom data keys are merged, with null removing a key.
     *
     * @example Change a contact's fields
     * $contact = $bird->contacts->update(
     *     'con_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new ContactUpdateRequest())->setFirstName('Jane'),
     * );
     * echo $contact->getFirstName();
     */
    public function update(string $contactId, ContactUpdateRequest $params, ?RequestOptions $options = null): Contact
    {
        return $this->single('PATCH', '/v1/contacts/' . rawurlencode($contactId), Contact::class, $params, null, $options);
    }

    /**
     * Delete a contact and remove it from every audience it belongs to. Suppression records for the address are unaffected.
     *
     * @example Delete a contact by id
     * $bird->contacts->delete('con_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function delete(string $contactId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/contacts/' . rawurlencode($contactId), null, null, $options);
    }

    /**
     * Create or update up to 1,000 contacts in one request, matched by email address, and optionally add them all to one or more audiences. Per-contact results are returned in submission order.
     *
     * @example Create or update many contacts at once, matched by email
     * $result = $bird->contacts->batch(
     *     (new ContactUpsertRequest())->setContacts([
     *         (new ContactCreateRequest())->setEmail('jane@acme.com')->setFirstName('Jane'),
     *     ]),
     * );
     * printf("%d contacts upserted\n", count($result->getData() ?? []));
     */
    public function batch(ContactUpsertRequest $params, ?RequestOptions $options = null): ContactUpsertResult
    {
        return $this->single('POST', '/v1/contacts/batch', ContactUpsertResult::class, $params, null, $options);
    }
}
