<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\ContactProperty;
use MessageBird\Wire\Model\ContactPropertyCreateRequest;
use MessageBird\Wire\Model\ContactPropertyList;
use MessageBird\Wire\Model\ContactPropertyUpdateRequest;

final class ContactProperties extends Resource
{
    /**
     * List the workspace's contact properties as a cursor page, newest first. Archived properties are included, marked by their archived flag.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<ContactProperty>
     *
     * @example Iterate every contact property across pages
     * foreach ($bird->contactProperties->list() as $property) {
     *     echo $property->getKey(), ' ', $property->getType(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            ContactProperty::class,
            fn (?string $cursor): ContactPropertyList => $this->single('GET', '/v1/contact-properties', ContactPropertyList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof ContactPropertyList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof ContactPropertyList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get a single contact property by ID: key, type, fallback value, and archived state.
     *
     * @example Fetch a contact property by id
     * $property = $bird->contactProperties->get('cp_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $property->getKey(), ' ', $property->getType();
     */
    public function get(string $propertyId, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('GET', '/v1/contact-properties/' . rawurlencode($propertyId), ContactProperty::class, null, null, $options);
    }

    /**
     * Define a custom contact property (key + value type) that becomes available in contact data and as a broadcast template variable. The key and type cannot change after creation; a workspace holds at most 200 properties, archived included.
     *
     * @example Define a custom property
     * $property = $bird->contactProperties->create(
     *     (new ContactPropertyCreateRequest())->setKey('plan')->setType('string'),
     * );
     * echo $property->getId(); // "cp_…"
     */
    public function create(ContactPropertyCreateRequest $params, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('POST', '/v1/contact-properties', ContactProperty::class, $params, null, $options);
    }

    /**
     * Update a contact property's fallback value. Only the fallback value can change; the key and type are fixed at creation, so a different key or type needs a new property.
     *
     * @example Change a property's fallback value
     * $bird->contactProperties->update(
     *     'cp_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new ContactPropertyUpdateRequest())->setFallbackValue('free'),
     * );
     */
    public function update(string $propertyId, ContactPropertyUpdateRequest $params, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('PATCH', '/v1/contact-properties/' . rawurlencode($propertyId), ContactProperty::class, $params, null, $options);
    }

    /**
     * Archive a contact property: the key is rejected in new contact writes and stops rendering in templates, while stored values remain readable. The key stays reserved and counts toward the 200-property limit; reverse with `contact_properties.unarchive`.
     *
     * @example Archive a property, retiring the field without deleting its data
     * $property = $bird->contactProperties->archive('cp_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $property->getKey(), ' ', var_export($property->getArchived(), true);
     */
    public function archive(string $propertyId, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('POST', '/v1/contact-properties/' . rawurlencode($propertyId) . '/archive', ContactProperty::class, null, null, $options);
    }

    /**
     * Reactivate an archived contact property so its key is accepted in contact writes and renders in templates again. Fails with a conflict if the property is not archived.
     *
     * @example Restore an archived property
     * $bird->contactProperties->unarchive('cp_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function unarchive(string $propertyId, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('POST', '/v1/contact-properties/' . rawurlencode($propertyId) . '/unarchive', ContactProperty::class, null, null, $options);
    }
}
