<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Preference;
use MessageBird\Wire\Model\PreferenceList;

final class ContactsPreferences extends Resource
{
    /**
     * List the recorded messaging preferences for a contact's own handles (their email address and phone number) across every channel, as a cursor page.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<Preference>
     *
     * @example Read a contact's own stated preferences across channels
     * foreach ($bird->contacts->preferences->list('con_01krdgeqcxet5s7t44vh8rt9mg') as $preference) {
     *     echo $preference->getChannel(), ' ', $preference->getStatus(), "\n";
     * }
     */
    public function list(string $contactId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            Preference::class,
            fn (?string $cursor): PreferenceList => $this->single('GET', '/v1/contacts/' . rawurlencode($contactId) . '/preferences', PreferenceList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof PreferenceList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof PreferenceList);

                return $page->getNextCursor();
            },
        );
    }
}
