<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\ContactProperty;
use MessageBird\Wire\Model\ContactPropertyCreateRequest;
use MessageBird\Wire\Model\ContactPropertyList;
use MessageBird\Wire\Model\ContactPropertyUpdateRequest;

final class ContactProperties extends Resource
{
    /**
     * List the workspace's contact properties as a cursor page, newest first. Archived properties are included, marked by their archived flag.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<ContactProperty>
     *
     * @example Iterate every contact property across pages
     * foreach ($bird->contactProperties->list() as $property) {
     *     echo $property->getKey(), ' ', $property->getType(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            ContactProperty::class,
            fn (?string $cursor): ContactPropertyList => $this->single('GET', '/v1/contact-properties', ContactPropertyList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof ContactPropertyList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof ContactPropertyList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get a single contact property by ID: key, type, fallback value, and archived state.
     *
     * @example Fetch a contact property by id
     * $property = $bird->contactProperties->get('cp_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $property->getKey(), ' ', $property->getType();
     */
    public function get(string $propertyId, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('GET', '/v1/contact-properties/' . rawurlencode($propertyId), ContactProperty::class, null, null, $options);
    }

    /**
     * Define a custom contact property (key + value type) that becomes available in contact data and as a broadcast template variable. The key and type cannot change after creation; a workspace holds at most 200 properties, archived included.
     *
     * @example Define a custom property
     * $property = $bird->contactProperties->create(
     *     (new ContactPropertyCreateRequest())->setKey('plan')->setType('string'),
     * );
     * echo $property->getId(); // "cp_…"
     */
    public function create(ContactPropertyCreateRequest $params, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('POST', '/v1/contact-properties', ContactProperty::class, $params, null, $options);
    }

    /**
     * Update a contact property's fallback value. Only the fallback value can change; the key and type are fixed at creation, so a different key or type needs a new property.
     *
     * @example Change a property's fallback value
     * $bird->contactProperties->update(
     *     'cp_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new ContactPropertyUpdateRequest())->setFallbackValue('free'),
     * );
     */
    public function update(string $propertyId, ContactPropertyUpdateRequest $params, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('PATCH', '/v1/contact-properties/' . rawurlencode($propertyId), ContactProperty::class, $params, null, $options);
    }

    /**
     * Archive a contact property to remove it, and restore it with `contact_properties.unarchive`. It disappears from pickers and cannot be used in new template versions. Published templates keep sending. Stored values remain available, and API writes and imports still accept values of the property's type. Returns a 409 conflict if the property is already archived. Also returns a 409 while a published automation, including a paused one, uses the property in a trigger or contact write, or while an active run writes it. Remove the property from those automations or archive them, and let active runs finish or cancel them before retrying. The key stays reserved and counts toward the 200-property limit.
     *
     * @example Remove a property with Archive and keep its values
     * $property = $bird->contactProperties->archive('cp_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $property->getKey(), ' ', var_export($property->getArchived(), true);
     */
    public function archive(string $propertyId, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('POST', '/v1/contact-properties/' . rawurlencode($propertyId) . '/archive', ContactProperty::class, null, null, $options);
    }

    /**
     * Restore an archived contact property with its stored values. It appears in property pickers again and can be used in new template versions. Unarchiving a property that is not archived returns a `409` conflict.
     *
     * @example Restore an archived property
     * $bird->contactProperties->unarchive('cp_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function unarchive(string $propertyId, ?RequestOptions $options = null): ContactProperty
    {
        return $this->single('POST', '/v1/contact-properties/' . rawurlencode($propertyId) . '/unarchive', ContactProperty::class, null, null, $options);
    }
}
