<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Domain;
use MessageBird\Wire\Model\DomainCreate;
use MessageBird\Wire\Model\DomainList;
use MessageBird\Wire\Model\DomainUpdate;

final class Domains extends Resource
{
    /**
     * List the workspace's sending domains with their verification status, as a cursor page.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<Domain>
     *
     * @example Iterate every sending domain across pages
     * foreach ($bird->domains->list() as $domain) {
     *     echo $domain->getId(), ' ', $domain->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            Domain::class,
            fn (?string $cursor): DomainList => $this->single('GET', '/v1/email/domains', DomainList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof DomainList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof DomainList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Fetch one sending domain: verification status and the DNS records with their individual verification states.
     *
     * @example Fetch a sending domain by id
     * $domain = $bird->domains->get('dom_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $domain->getDomain();
     */
    public function get(string $domainId, ?RequestOptions $options = null): Domain
    {
        return $this->single('GET', '/v1/email/domains/' . rawurlencode($domainId), Domain::class, null, null, $options);
    }

    /**
     * Register a new sending domain and get the DNS records to publish. Flow: call this, publish the returned DNS records at your DNS provider, then call email_domains_verify (repeat until status is verified — DNS propagation can take minutes to hours).
     *
     * @example Register a sending domain
     * $domain = $bird->domains->create(
     *     (new DomainCreate())->setDomain('mail.acme.com'),
     * );
     * echo $domain->getId(), ' ', $domain->getStatus(); // "dom_…", "pending"
     */
    public function create(DomainCreate $params, ?RequestOptions $options = null): Domain
    {
        return $this->single('POST', '/v1/email/domains', Domain::class, $params, null, $options);
    }

    /**
     * Trigger a DNS verification check for a sending domain and return the refreshed domain with per-record results. Safe to repeat while waiting for DNS propagation.
     *
     * @example Re-run the DNS verification check
     * $domain = $bird->domains->verify('dom_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $domain->getStatus(); // "verified" once DNS is in place
     */
    public function verify(string $domainId, ?RequestOptions $options = null): Domain
    {
        return $this->single('POST', '/v1/email/domains/' . rawurlencode($domainId) . '/verify', Domain::class, null, null, $options);
    }

    /**
     * Update a sending domain's tracking and inbound configuration. Tracking: toggle click_tracking and open_tracking (applied immediately to new sends), and set, change, or remove the tracking domain (the name part only — Bird appends the sending domain). Enabling either toggle with no tracking domain configured returns 409; removing the tracking domain while either toggle is still on also returns 409. Tracking-domain changes on a verified domain are staged behind DNS verification, so the current config keeps serving until the new records verify. Inbound receiving: set inbound.enabled to start or stop receiving mail for the domain. Enabling requires the domain's DKIM to be verified first (a fresh enable on an unverified domain returns 422), and a domain already receiving inbound for another organization returns 422. The MX records to publish are always listed in dns_records regardless, so enabling — not merely publishing them — is what turns receiving on.
     *
     * @example Enable tracking on a domain
     * $bird->domains->update(
     *     'dom_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new DomainUpdate())
     *         ->setSettings((new DomainSettings())->setClickTracking(true)->setOpenTracking(true))
     *         ->setTracking((new DomainUpdateTracking())->setName('links')),
     * );
     */
    public function update(string $domainId, DomainUpdate $params, ?RequestOptions $options = null): Domain
    {
        return $this->single('PATCH', '/v1/email/domains/' . rawurlencode($domainId), Domain::class, $params, null, $options);
    }

    /**
     * Delete a sending domain by id. Revokes its sender authorization: new sends from the domain are rejected afterward, while historical statistics and events for past sends are preserved. Destructive.
     *
     * @example Delete a sending domain by id
     * $bird->domains->delete('dom_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function delete(string $domainId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/email/domains/' . rawurlencode($domainId), null, null, $options);
    }
}
