<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\ReceiveRule;
use MessageBird\Wire\Model\ReceiveRuleCreate;
use MessageBird\Wire\Model\ReceiveRuleList;

final class EmailMailboxesReceiveRules extends Resource
{
    /**
     * List a mailbox's allow/block receive rules as a cursor page, oldest first. Filter by action.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<ReceiveRule>
     *
     * @example Iterate a mailbox's receive rules
     * foreach ($bird->email->mailboxes->receiveRules->list('mbx_01krdgeqcxet5s7t44vh8rt9mg') as $rule) {
     *     echo $rule->getAction(), ' ', $rule->getEntry(), "\n";
     * }
     */
    public function list(string $mailboxId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            ReceiveRule::class,
            fn (?string $cursor): ReceiveRuleList => $this->single('GET', '/v1/email/mailboxes/' . rawurlencode($mailboxId) . '/receive-rules', ReceiveRuleList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof ReceiveRuleList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof ReceiveRuleList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Add an allow or block rule for a sender address or domain to a mailbox. Block always wins; up to 200 rules per mailbox.
     *
     * @example Block a sender from a mailbox
     * $rule = $bird->email->mailboxes->receiveRules->create(
     *     'mbx_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new ReceiveRuleCreate())
     *         ->setAction('block')
     *         ->setEntry('spam@example.com')
     *         ->setNote('Repeated spam'),
     * );
     * echo $rule->getId();
     */
    public function create(string $mailboxId, ReceiveRuleCreate $params, ?RequestOptions $options = null): ReceiveRule
    {
        return $this->single('POST', '/v1/email/mailboxes/' . rawurlencode($mailboxId) . '/receive-rules', ReceiveRule::class, $params, null, $options);
    }

    /**
     * Remove a receive rule from a mailbox. Delete-and-recreate is how an entry's action is flipped.
     *
     * @example Delete a receive rule
     * $bird->email->mailboxes->receiveRules->delete(
     *     'mbx_01krdgeqcxet5s7t44vh8rt9mg',
     *     'rul_01krdgeqcxet5s7t44vh8rt9mg',
     * );
     */
    public function delete(string $mailboxId, string $ruleId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/email/mailboxes/' . rawurlencode($mailboxId) . '/receive-rules/' . rawurlencode($ruleId), null, null, $options);
    }
}
