<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailInboxInsightsDomainMonitoringResult;

final class EmailInboxInsightsDomainMonitoring extends Resource
{
    /**
     * Set up monitoring for the workspace's main verified sending domain. Takes no body. Existing monitoring returns already_on without changes. Otherwise, the sole verified domain or the domain that sent the most mail in the last 30 days is enabled; an uncertain choice returns choice_required, and no verified domains returns no_verified_domains. Only enabled has a non-null domain. Read the domain list after already_on; ask the user to choose after choice_required. Reuse an idempotency key for retries of the same setup attempt. API-key and service-account calls require Insights preview access for your organization.
     *
     * @example Enable automatic monitoring and inspect the outcome
     * // Requires Insights preview access for the organization.
     * $result = $bird->email->inboxInsights->domainMonitoring->upsert();
     * var_dump($result->getOutcome(), $result->getDomain());
     */
    public function upsert(?RequestOptions $options = null): EmailInboxInsightsDomainMonitoringResult
    {
        return $this->single('POST', '/v1/email/inbox-insights/domain-monitoring', EmailInboxInsightsDomainMonitoringResult::class, null, null, $options);
    }
}
