<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailMailboxComposeRequest;
use MessageBird\Wire\Model\EmailThreadMessage;

final class EmailMailboxesMessages extends Resource
{
    /**
     * Send a new email from this mailbox's own address, starting a new conversation. Replies to it thread back automatically. To reply within an existing conversation, use the reply endpoint on one of its messages.
     */
    public function create(string $mailboxId, EmailMailboxComposeRequest $params, ?RequestOptions $options = null): EmailThreadMessage
    {
        return $this->single('POST', '/v1/email/mailboxes/' . rawurlencode($mailboxId) . '/messages', EmailThreadMessage::class, $params, null, $options);
    }
}
