<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailInboxInsightsAuthentication;
use MessageBird\Wire\Model\EmailInboxInsightsBlocklists;
use MessageBird\Wire\Model\EmailInboxInsightsComplaints;
use MessageBird\Wire\Model\EmailInboxInsightsPlacement;
use MessageBird\Wire\Model\EmailInboxInsightsSpamTraps;

class EmailInboxInsightsBase extends Resource
{
    /**
     * Read placement for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Rates are percentages, and section statuses distinguish missing measurements. Deltas require a requested comparison and comparable prior data; absence does not mean stable placement. Provider filters add series lines without filtering the provider table. The response reports domain-wide panel/seed estimates with audience weighting, not delivery counts or a marketing/transactional split; a domain name alone does not identify a stream. Read rate measures reading, not opens. Label freshness from freshness.as_of; missing days and nulls are not zeros. Associations do not establish a cause. This read does not enable monitoring. Use `email.inbox_insights.seed_tests.list` for individual seed-test results. Google Postmaster connection status remains dashboard-only. These aggregates cannot prove placement for every customer. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read placement with per-section statuses
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->placement(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function placement(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsPlacement
    {
        return $this->single('GET', '/v1/email/inbox-insights/placement', EmailInboxInsightsPlacement::class, null, $query, $options);
    }

    /**
     * Read SPF, DKIM and DMARC results for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Pass rates are percentages. A not_configured section does not establish that DNS records are absent or that authentication failed; the source's coverage must be checked. Read section statuses, sources.latest_data_date and freshness before drawing conclusions. Authentication and placement changes can coincide without establishing cause. This read does not configure authentication or enable monitoring. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read authentication readiness
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->authentication(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function authentication(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsAuthentication
    {
        return $this->single('GET', '/v1/email/inbox-insights/authentication', EmailInboxInsightsAuthentication::class, null, $query, $options);
    }

    /**
     * Read the Google Postmaster user-reported spam rate for a verified owned domain. This percentage differs from spam-folder placement and Bird feedback-loop complaints across providers. Dates are inclusive UTC days, at most 30 days apart; compare=previous_period adds the preceding period. The period rate is an unweighted mean of reported days; sparse days are missing observations, not zero complaints. Freshness identifies the last reported day, not a promised update schedule. Correlation with placement cannot identify causative sends. Sections can report not_configured when setup is incomplete; connection status and setup are available in the dashboard, not through this read. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read Gmail complaint measurements and setup status
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->complaints(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function complaints(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsComplaints
    {
        return $this->single('GET', '/v1/email/inbox-insights/complaints', EmailInboxInsightsComplaints::class, null, $query, $options);
    }

    /**
     * Read spam-trap totals, kinds, networks and sampled hits for a verified owned domain. Dates are inclusive UTC days, at most 30 days apart; compare=previous_period includes the preceding period. hit_rows has its own status and truncated_types; empty rows do not negate a positive total, and row counts cannot reconstruct total hits. A measured zero is valid. Hits alone do not identify the sending campaign or establish why placement changed. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read spam-trap hits including measured zero
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->spamTraps(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function spamTraps(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsSpamTraps
    {
        return $this->single('GET', '/v1/email/inbox-insights/spam-traps', EmailInboxInsightsSpamTraps::class, null, $query, $options);
    }

    /**
     * Check blocklist standing for the sending infrastructure of a verified domain owned by the workspace. This is a current lookup and accepts no date window. Inspect each target status and checked_at; a null active_count means the lookup service supplied no count. Zero and an empty target list do not establish complete coverage. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read the current blocklist result
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->blocklists(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function blocklists(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsBlocklists
    {
        return $this->single('GET', '/v1/email/inbox-insights/blocklists', EmailInboxInsightsBlocklists::class, null, $query, $options);
    }
}
