<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailInboxInsightsDomain;
use MessageBird\Wire\Model\EmailInboxInsightsDomainUpdate;
use MessageBird\Wire\Model\EmailInboxInsightsDomains;

final class EmailInboxInsightsDomainsResource extends Resource
{
    /**
     * List verified sending domains owned by the workspace and their monitoring settings. Follow next_cursor with starting_after, keeping filters and ordering. A monitored value records the workspace setting; it does not establish that vendor measurements exist. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EmailInboxInsightsDomain>
     *
     * @example List verified owned domains and monitoring preferences
     * // Requires Insights preview access for the organization.
     * foreach ($bird->email->inboxInsights->domains->list(['limit' => 25]) as $domain) {
     *     var_dump($domain->getDomain(), $domain->getMonitored());
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EmailInboxInsightsDomain::class,
            fn (?string $cursor): EmailInboxInsightsDomains => $this->single('GET', '/v1/email/inbox-insights/domains', EmailInboxInsightsDomains::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EmailInboxInsightsDomains);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EmailInboxInsightsDomains);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Set monitored explicitly to true or false for a verified domain owned by the workspace. Enabling enrolls the domain with eDataSource and saves the workspace preference. Disabling removes only that preference; vendor enrollment and measurement history remain. Reports still require verified ownership and are not gated by this preference. Repeating the same value is safe. Reuse an idempotency key when retrying the same change. API-key and service-account calls require Insights preview access for your organization.
     *
     * @example Disable the workspace preference while preserving measurement history
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $params = (new \MessageBird\Wire\Model\EmailInboxInsightsDomainUpdate())->setMonitored(false);
     * $report = $bird->email->inboxInsights->domains->update($sendingDomain, $params);
     * var_dump($report->getMonitored());
     */
    public function update(string $sendingDomain, EmailInboxInsightsDomainUpdate $params, ?RequestOptions $options = null): EmailInboxInsightsDomain
    {
        return $this->single('PATCH', '/v1/email/inbox-insights/domains/' . rawurlencode($sendingDomain), EmailInboxInsightsDomain::class, $params, null, $options);
    }
}
