<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailMailboxLabelList;
use MessageBird\Wire\Model\Mailbox;
use MessageBird\Wire\Model\MailboxCreate;
use MessageBird\Wire\Model\MailboxList;
use MessageBird\Wire\Model\MailboxStatsResponse;
use MessageBird\Wire\Model\MailboxUpdate;

class EmailMailboxesBase extends Resource
{
    /**
     * List the workspace's mailboxes as a cursor page, newest first. Search addresses and display names with q, or filter by exact address, state, or domain.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<Mailbox>
     *
     * @example Iterate every mailbox across pages
     * foreach ($bird->email->mailboxes->list() as $mailbox) {
     *     echo $mailbox->getId(), ' ', $mailbox->getAddress(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            Mailbox::class,
            fn (?string $cursor): MailboxList => $this->single('GET', '/v1/email/mailboxes', MailboxList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof MailboxList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof MailboxList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Create a mailbox: a durable agent identity that owns an email address, groups mail into conversations, and remembers conversations for its retention tier.
     *
     * @example Create a mailbox, letting Bird mint the address
     * $mailbox = $bird->email->mailboxes->create(
     *     (new MailboxCreate())
     *         ->setDisplayName('Acme Support'),
     * );
     * echo $mailbox->getId(), ' ', $mailbox->getAddress();
     */
    public function create(MailboxCreate $params, ?RequestOptions $options = null): Mailbox
    {
        return $this->single('POST', '/v1/email/mailboxes', Mailbox::class, $params, null, $options);
    }

    /**
     * Read one mailbox by ID. A mailbox deleted within its 30-day restore window is still returned, with `deleted_at` set. Once that window closes it is gone and this returns `404`.
     *
     * @example Fetch a mailbox by id
     * $mailbox = $bird->email->mailboxes->get('mbx_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $mailbox->getAddress(), ' ', $mailbox->getState();
     */
    public function get(string $mailboxId, ?RequestOptions $options = null): Mailbox
    {
        return $this->single('GET', '/v1/email/mailboxes/' . rawurlencode($mailboxId), Mailbox::class, null, null, $options);
    }

    /**
     * Update a mailbox's display name, reply-to, receive policy, retention tier, IP pool, or metadata. Lowering the retention tier requires `confirm=true` when it would make remembered messages older than the new cutoff eligible for deletion. Retention tier changes apply in the background, and lowering the tier again before the first change finishes is refused.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Change a mailbox's display name
     * $bird->email->mailboxes->update(
     *     'mbx_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new MailboxUpdate())->setDisplayName('Acme Help'),
     * );
     */
    public function update(string $mailboxId, MailboxUpdate $params, ?array $query = null, ?RequestOptions $options = null): Mailbox
    {
        return $this->single('PATCH', '/v1/email/mailboxes/' . rawurlencode($mailboxId), Mailbox::class, $params, $query, $options);
    }

    /**
     * Delete a mailbox. The address stops receiving immediately and is quarantined. The mailbox can be restored for 30 days, while normal message-retention expiry continues. After 30 days, the mailbox and its remaining messages are permanently deleted.
     *
     * @example Delete a mailbox, keeping its messages until the retention window closes
     * $bird->email->mailboxes->delete('mbx_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function delete(string $mailboxId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/email/mailboxes/' . rawurlencode($mailboxId), null, null, $options);
    }

    /**
     * Restore receiving and access to unexpired messages. Returns `404` if deletion was 30 or more days ago or permanent erasure has started, and `409` if the mailbox is not deleted or its address is unavailable.
     *
     * @example Restore a deleted mailbox before its retention window closes
     * $mailbox = $bird->email->mailboxes->restore('mbx_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $mailbox->getState();
     */
    public function restore(string $mailboxId, ?RequestOptions $options = null): Mailbox
    {
        return $this->single('POST', '/v1/email/mailboxes/' . rawurlencode($mailboxId) . '/restore', Mailbox::class, null, null, $options);
    }

    /**
     * Resume a suspended mailbox so it can send and receive again and its conversations become visible. Fails if your plan does not have room for another active mailbox (or another custom inbox.ai handle). Delete an active mailbox or upgrade first. A mailbox that is not suspended returns `409`.
     *
     * @example Resume a mailbox that stopped receiving
     * $mailbox = $bird->email->mailboxes->resume('mbx_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $mailbox->getState();
     */
    public function resume(string $mailboxId, ?RequestOptions $options = null): Mailbox
    {
        return $this->single('POST', '/v1/email/mailboxes/' . rawurlencode($mailboxId) . '/resume', Mailbox::class, null, null, $options);
    }

    /**
     * Read a mailbox's sent and received email statistics over a window: a period summary plus a bucketed series. Rows are bucketed by event time rather than send time, so engagement that arrived during the period for messages sent earlier is counted here. Both window bounds must use the same form, calendar days or RFC 3339 instants, matching the granularity.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Traffic for one mailbox over a month
     * $stats = $bird->email->mailboxes->stats(
     *     'mbx_01krdgeqcxet5s7t44vh8rt9mg',
     *     ['from' => '2026-05-01', 'to' => '2026-05-31'],
     * );
     * echo $stats->getSummary()?->getReceived();
     */
    public function stats(string $mailboxId, ?array $query = null, ?RequestOptions $options = null): MailboxStatsResponse
    {
        return $this->single('GET', '/v1/email/mailboxes/' . rawurlencode($mailboxId) . '/stats', MailboxStatsResponse::class, null, $query, $options);
    }

    /**
     * List the labels available in a mailbox: the built-in system labels (inbox, archive, spam, blocked, sent, trash, unread) plus every custom label in use.
     *
     * @example List the labels a mailbox's threads can carry
     * $labels = $bird->email->mailboxes->labels('mbx_01krdgeqcxet5s7t44vh8rt9mg');
     * foreach ($labels->getData() ?? [] as $label) {
     *     echo $label->getName(), "\n";
     * }
     */
    public function labels(string $mailboxId, ?RequestOptions $options = null): EmailMailboxLabelList
    {
        return $this->single('GET', '/v1/email/mailboxes/' . rawurlencode($mailboxId) . '/labels', EmailMailboxLabelList::class, null, null, $options);
    }
}
