<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailInboxInsightsAuthentication;
use MessageBird\Wire\Model\EmailInboxInsightsBlocklists;
use MessageBird\Wire\Model\EmailInboxInsightsComplaints;
use MessageBird\Wire\Model\EmailInboxInsightsPlacement;
use MessageBird\Wire\Model\EmailInboxInsightsSpamTraps;

class EmailInboxInsightsBase extends Resource
{
    /**
     * Read placement for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Rates are percentages, and section statuses distinguish missing measurements. Provider filters add series lines without filtering the provider table. This read does not enable monitoring. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read placement with per-section statuses
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->placement(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function placement(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsPlacement
    {
        return $this->single('GET', '/v1/email/inbox-insights/placement', EmailInboxInsightsPlacement::class, null, $query, $options);
    }

    /**
     * Read SPF, DKIM and DMARC results for a verified domain owned by the workspace. Dates are inclusive UTC days, with at most 30 days between from and to. Sections can report not_configured when their data source is not connected. This read does not configure authentication or enable monitoring. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read authentication readiness
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->authentication(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function authentication(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsAuthentication
    {
        return $this->single('GET', '/v1/email/inbox-insights/authentication', EmailInboxInsightsAuthentication::class, null, $query, $options);
    }

    /**
     * Read the Google Postmaster spam rate for a verified domain owned by the workspace. This percentage covers Gmail-received mail, not Bird feedback-loop complaints across providers. Dates are inclusive UTC days with at most 30 days between from and to. Use group_by for the series grain and compare=previous_period for the preceding period. Sections can report not_configured when Google Postmaster setup is incomplete. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read Gmail complaint measurements and setup status
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->complaints(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function complaints(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsComplaints
    {
        return $this->single('GET', '/v1/email/inbox-insights/complaints', EmailInboxInsightsComplaints::class, null, $query, $options);
    }

    /**
     * Read spam-trap hits for a verified domain owned by the workspace, with totals, trap kinds, networks and individual hits. Dates are inclusive UTC days with at most 30 days between from and to; compare=previous_period includes the preceding period. A measured zero is a valid result. Use the response status to distinguish measurements from unavailable data. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read spam-trap hits including measured zero
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->spamTraps(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function spamTraps(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsSpamTraps
    {
        return $this->single('GET', '/v1/email/inbox-insights/spam-traps', EmailInboxInsightsSpamTraps::class, null, $query, $options);
    }

    /**
     * Check blocklist standing for the sending infrastructure of a verified domain owned by the workspace. This is a current lookup and accepts no date window. Inspect each target status and checked_at; a null active_count means the lookup service supplied no count. Zero and an empty target list do not establish complete coverage. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read the current blocklist result
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->blocklists(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function blocklists(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsBlocklists
    {
        return $this->single('GET', '/v1/email/inbox-insights/blocklists', EmailInboxInsightsBlocklists::class, null, $query, $options);
    }
}
