<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailCompetitiveNotableFeed;
use MessageBird\Wire\Model\EmailCompetitiveWatchlist;

class EmailCompetitiveWatchlistResourceBase extends Resource
{
    /**
     * Read the complete watchlist report for the requested range. Competitor rows carry `watchlist_brand_id` values for `email.competitive.watchlist.brands.get` and sampled panel figures; an unavailable figure is null rather than zero. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read watchlist figures without replacing missing values
     * // Requires Insights preview access for the organization.
     * $report = $bird->email->competitive->watchlist->get(['range' => 30]);
     * var_dump($report->getData());
     */
    public function get(?array $query = null, ?RequestOptions $options = null): EmailCompetitiveWatchlist
    {
        return $this->single('GET', '/v1/email/competitive/watchlist', EmailCompetitiveWatchlist::class, null, $query, $options);
    }

    /**
     * Returns up to 100 findings across watched brands for the requested range. A campaign can appear for multiple signals, each with its own evidence. truncated reports omitted eligible findings; this report has no cursor pages. Each finding carries the watched-brand and campaign IDs for `email.competitive.watchlist.brands.campaigns.get`. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read notable campaigns
     * // Requires Insights preview access for the organization.
     * $report = $bird->email->competitive->watchlist->notable(['range' => 30]);
     * var_dump($report);
     */
    public function notable(?array $query = null, ?RequestOptions $options = null): EmailCompetitiveNotableFeed
    {
        return $this->single('GET', '/v1/email/competitive/watchlist/notable', EmailCompetitiveNotableFeed::class, null, $query, $options);
    }
}
