<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailCompetitiveBrandProfile;
use MessageBird\Wire\Model\EmailCompetitiveSendTimeGrid;
use MessageBird\Wire\Model\EmailCompetitiveWatchlistBrand;
use MessageBird\Wire\Model\EmailCompetitiveWatchlistBrandCreate;

class EmailCompetitiveWatchlistBrandsBase extends Resource
{
    /**
     * Add a brand using the panel brand_id returned by brand search. The response id identifies the new workspace watchlist entry for reads and removal. Each entry uses one place in the organization-wide allowance and tracks the brand's highest-volume sending domain. Reuse an idempotency key when retrying the same addition. API-key, OAuth, and service-account calls require Insights preview access for your organization.
     *
     * @example Add the brand returned by search
     * // Requires Insights preview access for the organization.
     * $matches = $bird->email->competitive->brands->search(['q' => 'Everlane']);
     * $brandId = null;
     * foreach ($matches->getData() ?? [] as $match) {
     *     if ($match->getName() === 'Everlane') {
     *         $brandId = $match->getBrandId();
     *         break;
     *     }
     * }
     * if ($brandId === null) {
     *     throw new \RuntimeException('No exact Everlane match');
     * }
     * $params = (new \MessageBird\Wire\Model\EmailCompetitiveWatchlistBrandCreate())->setBrandId($brandId);
     * $entry = $bird->email->competitive->watchlist->brands->create($params);
     * echo $entry->getId();
     */
    public function create(EmailCompetitiveWatchlistBrandCreate $params, ?RequestOptions $options = null): EmailCompetitiveWatchlistBrand
    {
        return $this->single('POST', '/v1/email/competitive/watchlist/brands', EmailCompetitiveWatchlistBrand::class, $params, null, $options);
    }

    /**
     * Remove the workspace watchlist entry using its cwb_ ID. This frees one place in the organization-wide allowance. Adding the brand again creates a new entry; removal does not delete campaign data from eDataSource. API-key calls require Insights preview access for your organization.
     *
     * @example Remove the selected competitor
     * // Requires Insights preview access for the organization.
     * $watchlist = $bird->email->competitive->watchlist->get(['range' => 30]);
     * $watchlistBrandId = null;
     * foreach ($watchlist->getData() ?? [] as $row) {
     *     if ($row->getName() === 'Everlane' && $row->getWatchlistBrandId() !== null) {
     *         $watchlistBrandId = $row->getWatchlistBrandId();
     *         break;
     *     }
     * }
     * if ($watchlistBrandId === null) {
     *     throw new \RuntimeException('Add Everlane to the watchlist first');
     * }
     * $bird->email->competitive->watchlist->brands->delete($watchlistBrandId);
     */
    public function delete(string $watchlistBrandId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/email/competitive/watchlist/brands/' . rawurlencode($watchlistBrandId), null, null, $options);
    }

    /**
     * Read one watched brand using the `watchlist_brand_id` from `email.competitive.watchlist.get`; the panel `brand_id` returned by `email.competitive.brands.search` is not accepted. The response includes headline figures and a mailbox-provider breakdown. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read one watched brand
     * // Requires Insights preview access for the organization.
     * $watchlist = $bird->email->competitive->watchlist->get(['range' => 30]);
     * $watchlistBrandId = null;
     * foreach ($watchlist->getData() ?? [] as $row) {
     *     if ($row->getName() === 'Everlane' && $row->getWatchlistBrandId() !== null) {
     *         $watchlistBrandId = $row->getWatchlistBrandId();
     *         break;
     *     }
     * }
     * if ($watchlistBrandId === null) {
     *     throw new \RuntimeException('Add Everlane to the watchlist first');
     * }
     * $report = $bird->email->competitive->watchlist->brands->get($watchlistBrandId, ['range' => 30]);
     * var_dump($report);
     */
    public function get(string $watchlistBrandId, ?array $query = null, ?RequestOptions $options = null): EmailCompetitiveBrandProfile
    {
        return $this->single('GET', '/v1/email/competitive/watchlist/brands/' . rawurlencode($watchlistBrandId), EmailCompetitiveBrandProfile::class, null, $query, $options);
    }

    /**
     * Takes a watchlist_brand_id from `email.competitive.watchlist.get` and an optional IANA timezone. Covers the last 90 days, with no range parameter. Cells describe sending activity by weekday and hour. The returned timezone labels the grid; peak_send_window can be null when no sending was observed. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read its send-time distribution
     * // Requires Insights preview access for the organization.
     * $watchlist = $bird->email->competitive->watchlist->get(['range' => 30]);
     * $watchlistBrandId = null;
     * foreach ($watchlist->getData() ?? [] as $row) {
     *     if ($row->getName() === 'Everlane' && $row->getWatchlistBrandId() !== null) {
     *         $watchlistBrandId = $row->getWatchlistBrandId();
     *         break;
     *     }
     * }
     * if ($watchlistBrandId === null) {
     *     throw new \RuntimeException('Add Everlane to the watchlist first');
     * }
     * $report = $bird->email->competitive->watchlist->brands->sendTime($watchlistBrandId, ['timezone' => 'UTC']);
     * var_dump($report);
     */
    public function sendTime(string $watchlistBrandId, ?array $query = null, ?RequestOptions $options = null): EmailCompetitiveSendTimeGrid
    {
        return $this->single('GET', '/v1/email/competitive/watchlist/brands/' . rawurlencode($watchlistBrandId) . '/send-time', EmailCompetitiveSendTimeGrid::class, null, $query, $options);
    }
}
