<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailTemplateBroadcastList;
use MessageBird\Wire\Model\EmailTemplateBroadcastSummary;

final class EmailTemplatesBroadcasts extends Resource
{
    /**
     * List the broadcasts that block deleting a template, newest first.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EmailTemplateBroadcastSummary>
     */
    public function list(string $templateRef, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EmailTemplateBroadcastSummary::class,
            fn (?string $cursor): EmailTemplateBroadcastList => $this->single('GET', '/v1/email/templates/' . rawurlencode($templateRef) . '/broadcasts', EmailTemplateBroadcastList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EmailTemplateBroadcastList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EmailTemplateBroadcastList);

                return $page->getNextCursor();
            },
        );
    }
}
