<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailThreadMessage;
use MessageBird\Wire\Model\EmailThreadMessageAttachmentList;
use MessageBird\Wire\Model\EmailThreadMessageBody;
use MessageBird\Wire\Model\EmailThreadMessageList;
use MessageBird\Wire\Model\EmailThreadMessageReplyRequest;

final class EmailThreadsMessages extends Resource
{
    /**
     * List the messages in a conversation newest first, both directions. Page older messages with `starting_after`, and pass `include=extracted_text` to inline each message's extracted plain text.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EmailThreadMessage>
     *
     * @example Iterate the messages in a thread
     * foreach ($bird->email->threads->messages->list('thr_01krdgeqcxet5s7t44vh8rt9mg') as $message) {
     *     echo $message->getId(), ' ', $message->getDirection(), "\n";
     * }
     */
    public function list(string $threadId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EmailThreadMessage::class,
            fn (?string $cursor): EmailThreadMessageList => $this->single('GET', '/v1/email/threads/' . rawurlencode($threadId) . '/messages', EmailThreadMessageList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EmailThreadMessageList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EmailThreadMessageList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get one conversation message with its extracted plain text, readable for the mailbox's full retention tier without MIME parsing.
     *
     * @example Fetch one message in a thread
     * $message = $bird->email->threads->messages->get(
     *     'thr_01krdgeqcxet5s7t44vh8rt9mg',
     *     'rem_01krdgeqcxet5s7t44vh8rt9mg',
     * );
     * echo $message->getFrom(), ' ', $message->getSubject();
     */
    public function get(string $threadId, string $messageId, ?RequestOptions $options = null): EmailThreadMessage
    {
        return $this->single('GET', '/v1/email/threads/' . rawurlencode($threadId) . '/messages/' . rawurlencode($messageId), EmailThreadMessage::class, null, null, $options);
    }

    /**
     * Get the original rendered HTML and plain-text body of a conversation message. Available for 30 days. After that, use the message's extracted_text.
     *
     * @example Read a message's rendered body
     * $body = $bird->email->threads->messages->body(
     *     'thr_01krdgeqcxet5s7t44vh8rt9mg',
     *     'rem_01krdgeqcxet5s7t44vh8rt9mg',
     * );
     * echo $body->getText() ?? $body->getHtml();
     */
    public function body(string $threadId, string $messageId, ?RequestOptions $options = null): EmailThreadMessageBody
    {
        return $this->single('GET', '/v1/email/threads/' . rawurlencode($threadId) . '/messages/' . rawurlencode($messageId) . '/body', EmailThreadMessageBody::class, null, null, $options);
    }

    /**
     * Reply to a specific conversation message from the mailbox's own address. To reply to a conversation, target its newest received message. Recipients, subject, and threading headers are derived automatically.
     *
     * @example Reply to everyone on a message
     * $reply = $bird->email->threads->messages->reply(
     *     'thr_01krdgeqcxet5s7t44vh8rt9mg',
     *     'rem_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new EmailThreadMessageReplyRequest())
     *         ->setText('Thanks, looking into it now.')
     *         ->setReplyAll(true),
     * );
     * echo $reply->getId();
     */
    public function reply(string $threadId, string $messageId, EmailThreadMessageReplyRequest $params, ?RequestOptions $options = null): EmailThreadMessage
    {
        return $this->single('POST', '/v1/email/threads/' . rawurlencode($threadId) . '/messages/' . rawurlencode($messageId) . '/reply', EmailThreadMessage::class, $params, null, $options);
    }

    /**
     * List the attachments on a conversation message. Bytes are downloadable for the mailbox's retention tier, and the metadata stays readable afterward on the message's attachment_manifest.
     *
     * @example List a message's attachments
     * $attachments = $bird->email->threads->messages->attachments(
     *     'thr_01krdgeqcxet5s7t44vh8rt9mg',
     *     'rem_01krdgeqcxet5s7t44vh8rt9mg',
     * );
     * foreach ($attachments->getData() ?? [] as $attachment) {
     *     echo $attachment->getFilename(), "\n";
     * }
     */
    public function attachments(string $threadId, string $messageId, ?RequestOptions $options = null): EmailThreadMessageAttachmentList
    {
        return $this->single('GET', '/v1/email/threads/' . rawurlencode($threadId) . '/messages/' . rawurlencode($messageId) . '/attachments', EmailThreadMessageAttachmentList::class, null, null, $options);
    }
}
