<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailCompetitiveBrandSearchResults;

final class EmailCompetitiveBrands extends Resource
{
    /**
     * Search by brand name or sending domain. Each match returns the panel's `brand_id`, which is different from the `watchlist_brand_id` returned by `email.competitive.watchlist.get`. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Find a competitor brand
     * // Requires Insights preview access for the organization.
     * $report = $bird->email->competitive->brands->search(['q' => 'Everlane']);
     * var_dump($report->getData());
     */
    public function search(?array $query = null, ?RequestOptions $options = null): EmailCompetitiveBrandSearchResults
    {
        return $this->single('GET', '/v1/email/competitive/brands/search', EmailCompetitiveBrandSearchResults::class, null, $query, $options);
    }
}
