<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailTemplateList;
use MessageBird\Wire\Model\EmailTemplateSummary;

final class EmailTemplates extends Resource
{
    /**
     * List email templates as a cursor page. The list covers both the workspace's own templates and our built-in `system` templates. Filter to one tier with `scope`, and filter further by category, source, theme, or a search across slug, name, and description. A theme narrows the built-in catalog to one of its five visual themes, so naming one returns built-ins alone.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EmailTemplateSummary>
     *
     * @example Find the templates a send can name
     * foreach ($bird->email->templates->list(['scope' => 'workspace']) as $template) {
     *     echo $template->getSlug(), ' ', $template->getName(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EmailTemplateSummary::class,
            fn (?string $cursor): EmailTemplateList => $this->single('GET', '/v1/email/templates', EmailTemplateList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EmailTemplateList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EmailTemplateList);

                return $page->getNextCursor();
            },
        );
    }
}
