<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailMessage;
use MessageBird\Wire\Model\EmailMessageList;

class EmailBase extends Resource
{
    /**
     * Fetch one email message by `id`, with aggregate delivery status and per-state recipient counts. The message body (`html`, `text`) is not returned. Per-recipient delivery statuses and the event log are separate sub-resources: `GET /v1/email/messages/{message_id}/recipients` and `GET /v1/email/messages/{message_id}/events`.
     *
     * @example Fetch a message by id
     * $message = $bird->email->get('em_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $message->getStatus();
     */
    public function get(string $messageId, ?RequestOptions $options = null): EmailMessage
    {
        return $this->single('GET', '/v1/email/messages/' . rawurlencode($messageId), EmailMessage::class, null, null, $options);
    }

    /**
     * List sent email messages, newest first, as a cursor page (`{data, next_cursor, …}`). Pass `next_cursor` back as `starting_after` to fetch the next page. Filter by creation time with the half-open range `created_after` (inclusive) and `created_before` (exclusive). For a single UTC day, `created_after` is that day at 00:00:00Z and `created_before` is the next day at 00:00:00Z.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EmailMessage>
     *
     * @example Iterate delivered messages across pages
     * foreach ($bird->email->list(['status' => 'delivered']) as $message) {
     *     echo $message->getId(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EmailMessage::class,
            fn (?string $cursor): EmailMessageList => $this->single('GET', '/v1/email/messages', EmailMessageList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EmailMessageList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EmailMessageList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Cancel a scheduled email before it sends. Only works while the message's `status` is still `scheduled`. Once it starts sending, or was already canceled, the call returns a conflict error. Canceling does not return consumed scheduled-send quota.
     *
     * @example Cancel a scheduled message
     * $bird->email->cancel('em_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function cancel(string $messageId, ?RequestOptions $options = null): void
    {
        $this->none('POST', '/v1/email/messages/' . rawurlencode($messageId) . '/cancel', null, null, $options);
    }
}
