<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailTemplateLanguage;
use MessageBird\Wire\Model\EmailTemplateLanguageList;
use MessageBird\Wire\Model\EmailTemplateLanguageSaved;
use MessageBird\Wire\Model\EmailTemplateLanguageUpdate;
use MessageBird\Wire\Model\EmailTemplateLanguageUpsert;

final class EmailTemplatesVersionsLanguages extends Resource
{
    /**
     * List the languages a template version holds, with each language's revision and fingerprint but not its content.
     */
    public function list(string $templateRef, string $versionId, ?RequestOptions $options = null): EmailTemplateLanguageList
    {
        return $this->single('GET', '/v1/email/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages', EmailTemplateLanguageList::class, null, null, $options);
    }

    /**
     * Read one language's subject and bodies from a template version. The response carries `compatibility`: what the stored HTML uses that mail clients remove, ignore, or render inconsistently, and `compatibility_severity` reducing it to `problem`, `warning`, or `none`.
     */
    public function get(string $templateRef, string $versionId, string $language, ?RequestOptions $options = null): EmailTemplateLanguage
    {
        return $this->single('GET', '/v1/email/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages/' . rawurlencode($language), EmailTemplateLanguage::class, null, null, $options);
    }

    /**
     * Save one language's full content on a template's draft, creating the language if the draft does not have it yet. The response carries `compatibility`: what the saved HTML uses that mail clients remove, ignore, or render inconsistently, each finding naming the pattern, its line and column, and what to use instead. Advisory: the language is saved either way, and `compatibility_severity` of `problem` means part of the content does nothing at all in the clients the finding names.
     */
    public function set(string $templateRef, string $versionId, string $language, EmailTemplateLanguageUpsert $params, ?RequestOptions $options = null): EmailTemplateLanguageSaved
    {
        return $this->single('PUT', '/v1/email/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages/' . rawurlencode($language), EmailTemplateLanguageSaved::class, $params, null, $options);
    }

    /**
     * Change some fields of one language on a template's draft, leaving the rest as they are. The response carries `compatibility` for the language as saved, the same advisory report the full save returns.
     */
    public function update(string $templateRef, string $versionId, string $language, EmailTemplateLanguageUpdate $params, ?RequestOptions $options = null): EmailTemplateLanguageSaved
    {
        return $this->single('PATCH', '/v1/email/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages/' . rawurlencode($language), EmailTemplateLanguageSaved::class, $params, null, $options);
    }

    /**
     * Remove one language from a template's draft. The current default cannot be removed on its own; update the template to point the default at a different language first, then remove the old one.
     */
    public function delete(string $templateRef, string $versionId, string $language, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/email/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages/' . rawurlencode($language), null, null, $options);
    }
}
