<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailThread;
use MessageBird\Wire\Model\EmailThreadList;
use MessageBird\Wire\Model\EmailThreadUpdateRequest;

class EmailThreadsBase extends Resource
{
    /**
     * List mailbox conversations as a cursor page, most recently active first. `label` selects the view: inbox (default), archive, spam, blocked, or a custom label. Filter by mailbox, contact, participant address, or subject substring.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EmailThread>
     *
     * @example Iterate threads across pages
     * foreach ($bird->email->threads->list(['mailbox_id' => 'mbx_01krdgeqcxet5s7t44vh8rt9mg']) as $thread) {
     *     echo $thread->getId(), ' ', $thread->getSubject(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EmailThread::class,
            fn (?string $cursor): EmailThreadList => $this->single('GET', '/v1/email/threads', EmailThreadList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EmailThreadList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EmailThreadList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get one conversation: participants, counts, labels, read state. Fetch its messages with the thread messages endpoint.
     *
     * @example Fetch a thread by id
     * $thread = $bird->email->threads->get('thr_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $thread->getSubject(), ' ', $thread->getMessageCount();
     */
    public function get(string $threadId, ?RequestOptions $options = null): EmailThread
    {
        return $this->single('GET', '/v1/email/threads/' . rawurlencode($threadId), EmailThread::class, null, null, $options);
    }

    /**
     * Add or remove labels on a conversation, or link and unlink a contact. Adding `spam` files it as spam, `archive` clears it out of the inbox, and `inbox` brings it back.
     *
     * @example Relabel a thread and link it to a contact
     * $bird->email->threads->update(
     *     'thr_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new EmailThreadUpdateRequest())
     *         ->setLabels((new EmailLabelsUpdate())->setAdd(['escalated']))
     *         ->setContactId('con_01krdgeqcxet5s7t44vh8rt9mg'),
     * );
     */
    public function update(string $threadId, EmailThreadUpdateRequest $params, ?RequestOptions $options = null): EmailThread
    {
        return $this->single('PATCH', '/v1/email/threads/' . rawurlencode($threadId), EmailThread::class, $params, null, $options);
    }

    /**
     * Move a conversation and all its messages to trash (purged after 30 days), or delete permanently with `?permanent=true`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Delete a thread
     * $bird->email->threads->delete('thr_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function delete(string $threadId, ?array $query = null, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/email/threads/' . rawurlencode($threadId), null, $query, $options);
    }
}
