<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailCompetitiveBrandSearchResults;

final class EmailCompetitiveBrands extends Resource
{
    /**
     * Find a competitor by brand name or sending domain without adding it. For existing competitors, `email.competitive.watchlist.get` already returns names, tracked domains and watchlist IDs. Search returns at most eight matches, each with its highest-volume sending domain, not every domain a brand uses. Resolve ambiguous names against the intended domain before any authorized addition. An empty or limited result describes this search, not exhaustive panel coverage. The returned panel `brand_id` differs from a saved `watchlist_brand_id`. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Find a competitor brand
     * // Requires Insights preview access for the organization.
     * $report = $bird->email->competitive->brands->search(['q' => 'Everlane']);
     * var_dump($report->getData());
     */
    public function search(?array $query = null, ?RequestOptions $options = null): EmailCompetitiveBrandSearchResults
    {
        return $this->single('GET', '/v1/email/competitive/brands/search', EmailCompetitiveBrandSearchResults::class, null, $query, $options);
    }
}
