<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailCompetitiveCampaign;
use MessageBird\Wire\Model\EmailCompetitiveCampaignFeed;

final class EmailCompetitiveWatchlistBrandsCampaigns extends Resource
{
    /**
     * Takes a watchlist_brand_id from `email.competitive.watchlist.get`. Returns a cursor page, default 25 rows and maximum 100. Cursors retain the brand, range and ordering: next_cursor advances with starting_after; prev_cursor or refresh_cursor reads preceding rows with ending_before. captured and promo_rate describe a sample independently of this page. next_cursor controls continuation; truncated can also describe the sample. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EmailCompetitiveCampaign>
     *
     * @example Iterate campaigns across cursor pages
     * // Requires Insights preview access for the organization.
     * $watchlist = $bird->email->competitive->watchlist->get(['range' => 30]);
     * $watchlistBrandId = null;
     * foreach ($watchlist->getData() ?? [] as $row) {
     *     if ($row->getName() === 'Everlane' && $row->getWatchlistBrandId() !== null) {
     *         $watchlistBrandId = $row->getWatchlistBrandId();
     *         break;
     *     }
     * }
     * if ($watchlistBrandId === null) {
     *     throw new \RuntimeException('Add Everlane to the watchlist first');
     * }
     * foreach ($bird->email->competitive->watchlist->brands->campaigns->list($watchlistBrandId, ['range' => 30, 'limit' => 25]) as $campaign) {
     *     echo $campaign->getId(), "\n";
     * }
     */
    public function list(string $watchlistBrandId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EmailCompetitiveCampaign::class,
            fn (?string $cursor): EmailCompetitiveCampaignFeed => $this->single('GET', '/v1/email/competitive/watchlist/brands/' . rawurlencode($watchlistBrandId) . '/campaigns', EmailCompetitiveCampaignFeed::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EmailCompetitiveCampaignFeed);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EmailCompetitiveCampaignFeed);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Takes a watchlist_brand_id and a campaign_id from `email.competitive.watchlist.brands.campaigns.list`. campaign_id is text to preserve its digits. Returns the campaign's figures and nullable creative URL; a campaign outside that watched brand returns not found. API-key calls require Insights preview access for your organization.
     *
     * @example Use a campaign ID without converting it to a number
     * // Requires Insights preview access for the organization.
     * $watchlist = $bird->email->competitive->watchlist->get(['range' => 30]);
     * $watchlistBrandId = null;
     * foreach ($watchlist->getData() ?? [] as $row) {
     *     if ($row->getName() === 'Everlane' && $row->getWatchlistBrandId() !== null) {
     *         $watchlistBrandId = $row->getWatchlistBrandId();
     *         break;
     *     }
     * }
     * if ($watchlistBrandId === null) {
     *     throw new \RuntimeException('Add Everlane to the watchlist first');
     * }
     * $page = $bird->email->competitive->watchlist->brands->campaigns->list($watchlistBrandId, ['range' => 30, 'limit' => 1])->fetch();
     * $campaignId = ($page->data[0] ?? null)?->getId();
     * if ($campaignId === null) {
     *     throw new \RuntimeException('No captured campaigns');
     * }
     * $report = $bird->email->competitive->watchlist->brands->campaigns->get($watchlistBrandId, $campaignId);
     * var_dump($report);
     */
    public function get(string $watchlistBrandId, string $campaignId, ?RequestOptions $options = null): EmailCompetitiveCampaign
    {
        return $this->single('GET', '/v1/email/competitive/watchlist/brands/' . rawurlencode($watchlistBrandId) . '/campaigns/' . rawurlencode($campaignId), EmailCompetitiveCampaign::class, null, null, $options);
    }
}
