<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailCompetitiveVolumeSeries;

class EmailCompetitiveBase extends Resource
{
    /**
     * Accepts up to 20 distinct watchlist entry IDs from `email.competitive.watchlist.get`. Omitting brand_ids requests the workspace's own line. Competitor lines retain the requested order after the workspace line, when present. Each line's source distinguishes estimated panel volume from the workspace's accepted sends. Returns daily series without pagination. API-key calls require Insights preview access for your organization.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Compare daily volume with a watched brand
     * // Requires Insights preview access for the organization.
     * $watchlist = $bird->email->competitive->watchlist->get(['range' => 30]);
     * $watchlistBrandId = null;
     * foreach ($watchlist->getData() ?? [] as $row) {
     *     if ($row->getName() === 'Everlane' && $row->getWatchlistBrandId() !== null) {
     *         $watchlistBrandId = $row->getWatchlistBrandId();
     *         break;
     *     }
     * }
     * if ($watchlistBrandId === null) {
     *     throw new \RuntimeException('Add Everlane to the watchlist first');
     * }
     * $report = $bird->email->competitive->volumeSeries(['range' => 30, 'brand_ids' => [$watchlistBrandId]]);
     * var_dump($report);
     */
    public function volumeSeries(?array $query = null, ?RequestOptions $options = null): EmailCompetitiveVolumeSeries
    {
        $query = self::joinCsv($query, ['brand_ids']);

        return $this->single('GET', '/v1/email/competitive/volume-series', EmailCompetitiveVolumeSeries::class, null, $query, $options);
    }
}
