<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailInboxInsightsSeedTestCreate;
use MessageBird\Wire\Model\EmailInboxInsightsSeedTestRegistration;
use MessageBird\Wire\Model\EmailInboxInsightsSeedTests;

class EmailInboxInsightsSeedTestsResourceBase extends Resource
{
    /**
     * Register only when the intended send is ready. Read `email.inbox_insights.seed_tests.configuration.get` for supported options. CLI and MCP registration require OAuth login and browser confirmation: a signed-in person registers the test from the review page. Direct API and SDK calls register immediately. Registration spends organization-wide allowance and returns addresses; it sends no email. Use a separately authorized send to deliver the intended message to those addresses. Keep the same explicit Idempotency-Key and body after a lost response. On 409 E27008, contact support with the request ID and domain before starting another test. A new CLI or MCP invocation can create another proposal; executing it can register another batch. registration_id is for support, not a history lookup. The person reviewing a CLI or MCP proposal needs write access to the workspace.
     *
     * @example Register addresses for a ready send
     * // Requires Insights preview access for the organization.
     * $idempotencyKey = getenv('IDEMPOTENCY_KEY');
     * if ($idempotencyKey === false || $idempotencyKey === '') {
     *     throw new \RuntimeException('Set IDEMPOTENCY_KEY to a unique key for this registration and retain it for retries');
     * }
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $configuration = $bird->email->inboxInsights->seedTests->configuration->get(['sending_domain' => $sendingDomain]);
     * $pools = array_values(array_filter($configuration->getListTypes() ?? [], static fn ($choice) => $choice->getAvailable() === true));
     * $profiles = array_values(array_filter($configuration->getEngagementProfiles() ?? [], static fn ($choice) => $choice->getAvailable() === true));
     * $regions = $configuration->getRegions() ?? [];
     * $region = ($regions[0] ?? null)?->getValue();
     * if ($pools === [] || $profiles === [] || $region === null) {
     *     throw new \RuntimeException('No seed-test options available');
     * }
     * $params = (new \MessageBird\Wire\Model\EmailInboxInsightsSeedTestCreate())
     *     ->setSendingDomain($sendingDomain)
     *     ->setListType($pools[0]->getValue())
     *     ->setEngagementProfile($profiles[0]->getValue())
     *     ->setRegions([$region]);
     *
     * $report = $bird->email->inboxInsights->seedTests->create($params, new RequestOptions(idempotencyKey: $idempotencyKey));
     * var_dump($report);
     */
    public function create(EmailInboxInsightsSeedTestCreate $params, ?RequestOptions $options = null): EmailInboxInsightsSeedTestRegistration
    {
        return $this->single('POST', '/v1/email/inbox-insights/seed-tests', EmailInboxInsightsSeedTestRegistration::class, $params, null, $options);
    }

    /**
     * Read seed-test history for an owned sending domain and the organization-wide allowance. Results are capped at 100; narrow the date window if tests.truncated is true. Only the newest test has full detail. registration_id cannot locate a history row, and absent history does not prove a registration failed. Scoped API keys, OAuth and service accounts require organization preview access.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read seed-test history and allowance
     * // Requires Insights preview access for the organization.
     * $sendingDomain = null;
     * foreach ($bird->email->inboxInsights->domains->list(['search' => 'mail.example.com']) as $domain) {
     *     if ($domain->getDomain() === 'mail.example.com') {
     *         $sendingDomain = $domain->getDomain();
     *         break;
     *     }
     * }
     * if ($sendingDomain === null) {
     *     throw new \RuntimeException('Verify mail.example.com in this workspace first');
     * }
     * $report = $bird->email->inboxInsights->seedTests->list(['sending_domain' => $sendingDomain]);
     * var_dump($report);
     */
    public function list(?array $query = null, ?RequestOptions $options = null): EmailInboxInsightsSeedTests
    {
        return $this->single('GET', '/v1/email/inbox-insights/seed-tests', EmailInboxInsightsSeedTests::class, null, $query, $options);
    }
}
