<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailStatsByBounceCodeResponse;
use MessageBird\Wire\Model\EmailStatsByBroadcastResponse;
use MessageBird\Wire\Model\EmailStatsByCategoryResponse;
use MessageBird\Wire\Model\EmailStatsByClientResponse;
use MessageBird\Wire\Model\EmailStatsByComplaintTypeResponse;
use MessageBird\Wire\Model\EmailStatsByLocationResponse;
use MessageBird\Wire\Model\EmailStatsByMailboxProviderRegionResponse;
use MessageBird\Wire\Model\EmailStatsByMailboxProviderResponse;
use MessageBird\Wire\Model\EmailStatsByRecipientDomainResponse;
use MessageBird\Wire\Model\EmailStatsBySendingDomainResponse;
use MessageBird\Wire\Model\EmailStatsBySendingIpResponse;
use MessageBird\Wire\Model\EmailStatsByTemplateResponse;
use MessageBird\Wire\Model\EmailStatsResponse;
use MessageBird\Wire\Model\EmailStatsSummary;
use MessageBird\Wire\Model\EmailStatsTagsResponse;

final class EmailStats extends Resource
{
    /**
     * Aggregate email KPIs for one period: sends, delivered, bounces, complaints, opens, clicks, their rates, and latency percentiles. `from`/`to` are both YYYY-MM-DD days or both RFC 3339 instants (hour grain); add `compare=previous_period` for deltas versus the prior window. For a per-day or per-hour series use `email.stats.daily` or `email.stats.hourly`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Summary for a month
     * $summary = $bird->email->stats->summary(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * echo $summary->getSendsAccepted(), ' ', $summary->getDelivery()?->getDelivered();
     */
    public function summary(?array $query = null, ?RequestOptions $options = null): EmailStatsSummary
    {
        return $this->single('GET', '/v1/email/stats/summary', EmailStatsSummary::class, null, $query, $options);
    }

    /**
     * Per-day email stats series (counts, rates, latency percentiles), gap-filled with zero rows, max 365 days. At most one filter of `category`, `sending_domain`, `tag`, `sending_ip`, `recipient_domain`, `template`. For hour resolution use `email.stats.hourly`; for one aggregate row use `email.stats.summary`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Daily series for a month
     * $series = $bird->email->stats->daily(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($series->getData() ?? [] as $row) {
     *     echo $row->getBucket(), ' ', $row->getDelivery()?->getDelivered(), "\n";
     * }
     */
    public function daily(?array $query = null, ?RequestOptions $options = null): EmailStatsResponse
    {
        return $this->single('GET', '/v1/email/stats/daily', EmailStatsResponse::class, null, $query, $options);
    }

    /**
     * Per-hour email stats series, gap-filled with zero rows, max 720 hours (30 days). Takes the same single-dimension filters as `email.stats.daily`; for longer ranges use `email.stats.daily`, for one aggregate row use `email.stats.summary`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Hourly series for a day
     * $series = $bird->email->stats->hourly(['from' => '2026-05-01', 'to' => '2026-05-02']);
     * foreach ($series->getData() ?? [] as $row) {
     *     echo $row->getBucket(), ' ', $row->getDelivery()?->getDelivered(), "\n";
     * }
     */
    public function hourly(?array $query = null, ?RequestOptions $options = null): EmailStatsResponse
    {
        return $this->single('GET', '/v1/email/stats/hourly', EmailStatsResponse::class, null, $query, $options);
    }

    /**
     * Email delivery and engagement stats grouped by tag, one row per `name:value` pair set at send time. Rows are ranked by `sort`, `processed` by default. Set `include_trend=true` to add a per-bucket rate series to each row.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Top 10 tags by delivered
     * $stats = $bird->email->stats->byTag([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'sort' => 'delivered',
     *     'limit' => 10,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getTag(), ' ', $row->getDelivery()?->getDelivered(), "\n";
     * }
     */
    public function byTag(?array $query = null, ?RequestOptions $options = null): EmailStatsTagsResponse
    {
        return $this->single('GET', '/v1/email/stats/tags', EmailStatsTagsResponse::class, null, $query, $options);
    }

    /**
     * Email delivery and engagement stats grouped by category, meaning `transactional` compared with `marketing`. Rows are ranked by `sort`, `processed` by default. Set `include_trend=true` to add a per-bucket rate series to each row.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Delivered per category
     * $stats = $bird->email->stats->byCategory(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getCategory(), ' ', $row->getDelivery()?->getDelivered(), "\n";
     * }
     */
    public function byCategory(?array $query = null, ?RequestOptions $options = null): EmailStatsByCategoryResponse
    {
        return $this->single('GET', '/v1/email/stats/categories', EmailStatsByCategoryResponse::class, null, $query, $options);
    }

    /**
     * Delivery and bounce stats grouped by sending IP, with deferral counts alongside them. `sort=bounces.block` surfaces reputation-damaged IPs first. Engagement, accepted, and processed counts aren't available per IP, and complaint and out-of-band bounce counts always read 0 here. For workspace-wide figures, use `email.stats.daily`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Sending IPs with the most blocks
     * $stats = $bird->email->stats->bySendingIp([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'sort' => 'bounces.block',
     *     'limit' => 20,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getSendingIp(), ' ', $row->getDelivery()?->getDelivered(), "\n";
     * }
     */
    public function bySendingIp(?array $query = null, ?RequestOptions $options = null): EmailStatsBySendingIpResponse
    {
        return $this->single('GET', '/v1/email/stats/sending-ips', EmailStatsBySendingIpResponse::class, null, $query, $options);
    }

    /**
     * Email delivery and engagement stats grouped by sending (`From`) domain, so you can compare deliverability across your workspace's verified domains. For per-IP reputation instead, use `email.stats.by_sending_ip`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Sending domains by delivery rate
     * $stats = $bird->email->stats->bySendingDomain([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'sort' => 'delivery_rate',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getSendingDomain(), ' ', $row->getDelivery()?->getDeliveryRate(), "\n";
     * }
     */
    public function bySendingDomain(?array $query = null, ?RequestOptions $options = null): EmailStatsBySendingDomainResponse
    {
        return $this->single('GET', '/v1/email/stats/sending-domains', EmailStatsBySendingDomainResponse::class, null, $query, $options);
    }

    /**
     * Email delivery and engagement stats grouped by exact recipient mailbox domain, for example `gmail.com`. Finer-grained than `email.stats.by_mailbox_provider`, which buckets domains into providers.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Recipient domains bouncing the most
     * $stats = $bird->email->stats->byRecipientDomain([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'sort' => 'bounce_rate',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getRecipientDomain(), ' ', $row->getDelivery()?->getBounceRate(), "\n";
     * }
     */
    public function byRecipientDomain(?array $query = null, ?RequestOptions $options = null): EmailStatsByRecipientDomainResponse
    {
        return $this->single('GET', '/v1/email/stats/recipient-domains', EmailStatsByRecipientDomainResponse::class, null, $query, $options);
    }

    /**
     * Email delivery and engagement stats grouped by recipient mailbox provider, for example `gmail`, `microsoft`, or `yahoo`. It covers the delivery stage onward, so there are no accepted or processed counts. For a per-region split within a provider, use `email.stats.by_mailbox_provider_region`; for exact destination domains instead, use `email.stats.by_recipient_domain`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Delivered per mailbox provider
     * $stats = $bird->email->stats->byMailboxProvider([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getMailboxProvider(), ' ', $row->getDelivery()?->getDelivered(), "\n";
     * }
     */
    public function byMailboxProvider(?array $query = null, ?RequestOptions $options = null): EmailStatsByMailboxProviderResponse
    {
        return $this->single('GET', '/v1/email/stats/mailbox-providers', EmailStatsByMailboxProviderResponse::class, null, $query, $options);
    }

    /**
     * Email delivery and engagement stats grouped by a mailbox provider and provider region pair, for example `gmail` in `NA`. It covers the delivery stage onward, so there are no accepted or processed counts. For the provider-level view without the region split, use `email.stats.by_mailbox_provider`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Delivered per provider region
     * $stats = $bird->email->stats->byMailboxProviderRegion([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getMailboxProvider(), ' ', $row->getMailboxProviderRegion(), ' ', $row->getDelivery()?->getDelivered(), "\n";
     * }
     */
    public function byMailboxProviderRegion(?array $query = null, ?RequestOptions $options = null): EmailStatsByMailboxProviderRegionResponse
    {
        return $this->single('GET', '/v1/email/stats/mailbox-provider-regions', EmailStatsByMailboxProviderRegionResponse::class, null, $query, $options);
    }

    /**
     * Email delivery and engagement stats grouped by the template used at send time, keyed by template id (`emt_…`); only templated sends appear. A single template's trend over time comes from `email.stats.daily` with its `template` filter.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Templates by open rate
     * $stats = $bird->email->stats->byTemplate([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'sort' => 'open_rate',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getTemplateId(), ' ', $row->getEngagement()?->getOpenRate(), "\n";
     * }
     */
    public function byTemplate(?array $query = null, ?RequestOptions $options = null): EmailStatsByTemplateResponse
    {
        return $this->single('GET', '/v1/email/stats/templates', EmailStatsByTemplateResponse::class, null, $query, $options);
    }

    /**
     * Opens and clicks grouped by country, region, or city, whichever you choose with `group_by`. It only has engagement counts, no delivery counts or rates. For engagement grouped by mail client or device instead, use `email.stats.by_client`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Unique opens per country
     * $stats = $bird->email->stats->byLocation([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getCountry(), ' ', $row->getEngagement()?->getUniqueOpens(), "\n";
     * }
     */
    public function byLocation(?array $query = null, ?RequestOptions $options = null): EmailStatsByLocationResponse
    {
        return $this->single('GET', '/v1/email/stats/locations', EmailStatsByLocationResponse::class, null, $query, $options);
    }

    /**
     * Opens and clicks grouped by mail client, operating system, or device type, whichever you choose with `group_by`. It only has engagement counts, no delivery counts or rates. For engagement grouped by geography instead, use `email.stats.by_location`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Unique opens per email client
     * $stats = $bird->email->stats->byClient([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getEmailClient(), ' ', $row->getEngagement()?->getUniqueOpens(), "\n";
     * }
     */
    public function byClient(?array $query = null, ?RequestOptions $options = null): EmailStatsByClientResponse
    {
        return $this->single('GET', '/v1/email/stats/clients', EmailStatsByClientResponse::class, null, $query, $options);
    }

    /**
     * Bounce counts grouped by the SMTP error code the receiving mail server returned. Each row also breaks the bounce down into its hard, soft, admin, block, and undetermined split. There are no delivered, open, or click counts here, because a bounce code only appears on a bounce event. For bounces broken down by destination instead, use `email.stats.by_recipient_domain` or `email.stats.by_mailbox_provider`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Which SMTP codes are bouncing
     * $stats = $bird->email->stats->byBounceCode([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'sort' => 'bounced',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getSmtpErrorCode(), ' ', $row->getBounced(), "\n";
     * }
     */
    public function byBounceCode(?array $query = null, ?RequestOptions $options = null): EmailStatsByBounceCodeResponse
    {
        return $this->single('GET', '/v1/email/stats/bounce-codes', EmailStatsByBounceCodeResponse::class, null, $query, $options);
    }

    /**
     * Spam-complaint counts grouped by the feedback-loop complaint type, for example `abuse`, `fraud`, or `virus`. Complaint side only, so there are no delivery or engagement counts. For complaints broken down by destination instead, use `email.stats.by_mailbox_provider` or `email.stats.by_recipient_domain`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Complaints per feedback type
     * $stats = $bird->email->stats->byComplaintType(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getFeedbackType(), ' ', $row->getComplained(), "\n";
     * }
     */
    public function byComplaintType(?array $query = null, ?RequestOptions $options = null): EmailStatsByComplaintTypeResponse
    {
        return $this->single('GET', '/v1/email/stats/complaint-types', EmailStatsByComplaintTypeResponse::class, null, $query, $options);
    }

    /**
     * Email delivery and engagement stats grouped by broadcast. Only broadcast sends appear. Reflects roughly the last 30 days of activity.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Broadcasts by click rate
     * $stats = $bird->email->stats->byBroadcast([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'sort' => 'click_rate',
     *     'limit' => 25,
     * ]);
     * foreach ($stats->getData() ?? [] as $row) {
     *     echo $row->getBroadcastId(), ' ', $row->getEngagement()?->getClickRate(), "\n";
     * }
     */
    public function byBroadcast(?array $query = null, ?RequestOptions $options = null): EmailStatsByBroadcastResponse
    {
        return $this->single('GET', '/v1/email/stats/broadcasts', EmailStatsByBroadcastResponse::class, null, $query, $options);
    }
}
