<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimSettings;
use MessageBird\Wire\Model\EsimSettingsUpdate;

final class EsimSettingsResource extends Resource
{
    /**
     * Read the workspace's effective eSIM settings, including whether Bird sends install credentials to travelers. Check this before sending credentials: a workspace that has turned delivery off refuses the send.
     */
    public function get(?RequestOptions $options = null): EsimSettings
    {
        return $this->single('GET', '/v1/esim/settings', EsimSettings::class, null, null, $options);
    }

    /**
     * Change the workspace's eSIM settings and return the effective result. Turning `credential_delivery_enabled` off stops Bird sending install credentials to travelers over either channel; the credentials stay readable from the API. Omitted fields keep their current value.
     */
    public function update(EsimSettingsUpdate $params, ?RequestOptions $options = null): EsimSettings
    {
        return $this->single('PATCH', '/v1/esim/settings', EsimSettings::class, $params, null, $options);
    }
}
