<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimCheckoutOptions;
use MessageBird\Wire\Model\EsimOffer;
use MessageBird\Wire\Model\EsimOfferList;
use MessageBird\Wire\Model\EsimOfferRequirements;
use MessageBird\Wire\Model\EsimOfferSummary;
use MessageBird\Wire\Model\EsimRecurringOffer;

final class EsimOffers extends Resource
{
    /**
     * List the prepaid travel eSIM offers available to this workspace as a cursor page ({data, next_cursor, ...}). Filter by country (ISO 3166-1 alpha-2) to find offers that cover a destination, or by zone_id for one coverage footprint. Each row carries the offer's pricing (data allowance, validity, and the price billed per provisioned package) and its zone_id; fetch the offer or the zone for the country list.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EsimOfferSummary>
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EsimOfferSummary::class,
            fn (?string $cursor): EsimOfferList => $this->single('GET', '/v1/esim/offers', EsimOfferList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EsimOfferList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EsimOfferList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Returns one eSIM offer with its pricing and embedded coverage zone.
     */
    public function get(string $offerId, ?RequestOptions $options = null): EsimOffer
    {
        return $this->single('GET', '/v1/esim/offers/' . rawurlencode($offerId), EsimOffer::class, null, null, $options);
    }

    /**
     * Returns a complete JSON Schema for each country in the offer coverage zone. First name, last name, and email are always required, including where no country definition exists. Customers collect and validate information themselves; enable JSON Schema format assertion for email and dates. Bird receives no answers and does not use these schemas to authorize purchase or assignment.
     */
    public function requirements(string $offerId, ?RequestOptions $options = null): EsimOfferRequirements
    {
        return $this->single('GET', '/v1/esim/offers/' . rawurlencode($offerId) . '/requirements', EsimOfferRequirements::class, null, null, $options);
    }

    /**
     * Returns published one-time terms and automatic renewal availability for a new eSIM. Automatic renewal includes its own price and cadence when an eligible mobile network is available. Availability is checked again when purchasing; this read does not reserve a package.
     */
    public function checkoutOptions(string $offerId, ?RequestOptions $options = null): EsimCheckoutOptions
    {
        return $this->single('GET', '/v1/esim/offers/' . rawurlencode($offerId) . '/checkout', EsimCheckoutOptions::class, null, null, $options);
    }

    /**
     * Returns the published whole-package recurring price and calendar-month or fixed-day cadence. Enrollment additionally checks that the assigned eSIM mobile network supports these terms.
     */
    public function recurrence(string $offerId, ?RequestOptions $options = null): EsimRecurringOffer
    {
        return $this->single('GET', '/v1/esim/offers/' . rawurlencode($offerId) . '/recurrence', EsimRecurringOffer::class, null, null, $options);
    }
}
