<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimZone;
use MessageBird\Wire\Model\EsimZoneList;

final class EsimZones extends Resource
{
    /**
     * List the coverage zones eSIM offers sell, as a cursor page ({data, next_cursor, ...}). Each zone carries its authoritative country list. Filter by country (ISO 3166-1 alpha-2) to find zones covering a destination, then list offers by zone_id to see what can be ordered there.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EsimZone>
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EsimZone::class,
            fn (?string $cursor): EsimZoneList => $this->single('GET', '/v1/esim/zones', EsimZoneList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EsimZoneList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EsimZoneList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Returns one coverage zone with its authoritative country list.
     */
    public function get(string $zoneId, ?RequestOptions $options = null): EsimZone
    {
        return $this->single('GET', '/v1/esim/zones/' . rawurlencode($zoneId), EsimZone::class, null, null, $options);
    }
}
