<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Esim;
use MessageBird\Wire\Model\EsimCompatibleOfferList;
use MessageBird\Wire\Model\EsimList;
use MessageBird\Wire\Model\EsimSummary;
use MessageBird\Wire\Model\EsimUpdate;

class EsimResourceBase extends Resource
{
    /**
     * List the workspace's eSIMs, newest first, as a cursor page ({data, next_cursor, ...}). Filter by status, iccid, or tag, or search by iccid_prefix, display_name, or phone_number. Each row is a compact summary; fetch a single eSIM for its packages and balances.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EsimSummary>
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EsimSummary::class,
            fn (?string $cursor): EsimList => $this->single('GET', '/v1/esim/sims', EsimList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EsimList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EsimList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get one eSIM with its lifecycle status, installation state, current data packages and balances, service-period timestamps, and last network attachment.
     */
    public function get(string $esimId, ?RequestOptions $options = null): Esim
    {
        return $this->single('GET', '/v1/esim/sims/' . rawurlencode($esimId), Esim::class, null, null, $options);
    }

    /**
     * Updates the eSIM's display name, tags, or metadata. Lifecycle and connectivity are managed through the dedicated endpoints.
     */
    public function update(string $esimId, EsimUpdate $params, ?RequestOptions $options = null): Esim
    {
        return $this->single('PATCH', '/v1/esim/sims/' . rawurlencode($esimId), Esim::class, $params, null, $options);
    }

    /**
     * Permanently release an eSIM. Irreversible: it can never be installed or used again, remaining package balances are forfeited, and release never credits anything back. Use release when responding to fraud or closing out a trip; to pause service temporarily use suspend instead.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     */
    public function release(string $esimId, ?array $query = null, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/esim/sims/' . rawurlencode($esimId), null, $query, $options);
    }

    /**
     * Suspend an eSIM's data service (reversible; validity keeps running). Confirmed by the esim.suspended event. Use resume to restore service.
     */
    public function suspend(string $esimId, ?RequestOptions $options = null): Esim
    {
        return $this->single('POST', '/v1/esim/sims/' . rawurlencode($esimId) . '/suspend', Esim::class, null, null, $options);
    }

    /**
     * Resume a suspended eSIM so it can use data again. Confirmed by the esim.resumed event.
     */
    public function resume(string $esimId, ?RequestOptions $options = null): Esim
    {
        return $this->single('POST', '/v1/esim/sims/' . rawurlencode($esimId) . '/resume', Esim::class, null, null, $options);
    }

    /**
     * List the offers that can be ordered as a top-up for this specific eSIM right now. Use this before creating a top-up order: the general offer catalog is not the answer, because a top-up must be servable by the eSIM's own mobile network and fit its package_limit.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     */
    public function compatibleOffers(string $esimId, ?array $query = null, ?RequestOptions $options = null): EsimCompatibleOfferList
    {
        return $this->single('GET', '/v1/esim/sims/' . rawurlencode($esimId) . '/compatible-offers', EsimCompatibleOfferList::class, null, $query, $options);
    }
}
