<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimPackage;
use MessageBird\Wire\Model\EsimPackageList;

final class EsimPackages extends Resource
{
    /**
     * Returns the eSIM's data packages with per-zone balances, validity, and status, newest first and in full: an eSIM holds at most package_limit concurrent packages. Balances update as mobile networks report usage; `balance.as_of` tells you how fresh they are.
     */
    public function list(string $esimId, ?RequestOptions $options = null): EsimPackageList
    {
        return $this->single('GET', '/v1/esim/sims/' . rawurlencode($esimId) . '/packages', EsimPackageList::class, null, null, $options);
    }

    /**
     * Returns one data package with its balance, validity, speed class, and status.
     */
    public function get(string $esimId, string $packageId, ?RequestOptions $options = null): EsimPackage
    {
        return $this->single('GET', '/v1/esim/sims/' . rawurlencode($esimId) . '/packages/' . rawurlencode($packageId), EsimPackage::class, null, null, $options);
    }

    /**
     * Remove a data package from an eSIM, freeing room under its package_limit. DESTRUCTIVE: any remaining balance is forfeited and removal itself never credits anything back; requires acknowledge_balance_forfeit=true when balance remains.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     */
    public function delete(string $esimId, string $packageId, ?array $query = null, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/esim/sims/' . rawurlencode($esimId) . '/packages/' . rawurlencode($packageId), null, $query, $options);
    }
}
