<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimCredentials;
use MessageBird\Wire\Model\EsimCredentialsDelivery;
use MessageBird\Wire\Model\EsimDelivery;

final class EsimCredentialsResource extends Resource
{
    /**
     * Read private installation credentials and device instructions. Requires esim_credentials permission. iOS links and manual details are supported; Android installation links and hosted QR image URLs return null. Returns a conflict for an uninstallable profile and service unavailable when credentials cannot be retrieved.
     */
    public function get(string $esimId, ?RequestOptions $options = null): EsimCredentials
    {
        return $this->single('GET', '/v1/esim/sims/' . rawurlencode($esimId) . '/credentials', EsimCredentials::class, null, null, $options);
    }

    /**
     * Send an eSIM's install credentials to the traveler by email or SMS, in English. Use after purchase or to resend installation details.
     */
    public function deliver(string $esimId, EsimDelivery $params, ?RequestOptions $options = null): EsimCredentialsDelivery
    {
        return $this->single('POST', '/v1/esim/sims/' . rawurlencode($esimId) . '/credentials/deliver', EsimCredentialsDelivery::class, $params, null, $options);
    }
}
