<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimInstallLink;

final class EsimInstallLinks extends Resource
{
    /**
     * Create a private hosted installation link for one eSIM. The recipient needs no Bird login. Links expire after seven days; earlier links remain valid until expiry or revocation. Requires esim_credentials permission. Returns 501 when new hosted links are unavailable.
     */
    public function create(string $esimId, ?RequestOptions $options = null): EsimInstallLink
    {
        return $this->single('POST', '/v1/esim/sims/' . rawurlencode($esimId) . '/install-links', EsimInstallLink::class, null, null, $options);
    }

    /**
     * Revoke a hosted install link so its url stops installing the eSIM. Use it when a link went to the wrong person. Already-revoked and expired links succeed. Requires the esim_credentials scope.
     */
    public function delete(string $esimId, string $installLinkId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/esim/sims/' . rawurlencode($esimId) . '/install-links/' . rawurlencode($installLinkId), null, null, $options);
    }
}
