<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimRecurringPeriod;
use MessageBird\Wire\Model\EsimRecurringPeriodList;
use MessageBird\Wire\Model\EsimRecurringSubscription;
use MessageBird\Wire\Model\EsimRecurringSubscriptionCreate;
use MessageBird\Wire\Model\EsimRecurringSubscriptionList;

final class EsimRecurringSubscriptions extends Resource
{
    /**
     * Purchase the first recurring period on an assigned eSIM. Reuse the required Idempotency-Key and identical request to recover enrollment. Check subscription and period history for payment and delivery outcomes. Changed prices, unfunded renewal, or confirmed delivery failure stop future renewal.
     */
    public function create(EsimRecurringSubscriptionCreate $params, ?RequestOptions $options = null): EsimRecurringSubscription
    {
        return $this->single('POST', '/v1/esim/subscriptions', EsimRecurringSubscription::class, $params, null, $options);
    }

    /**
     * Returns recurring services for assigned eSIMs in this workspace.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EsimRecurringSubscription>
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EsimRecurringSubscription::class,
            fn (?string $cursor): EsimRecurringSubscriptionList => $this->single('GET', '/v1/esim/subscriptions', EsimRecurringSubscriptionList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EsimRecurringSubscriptionList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EsimRecurringSubscriptionList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Returns the current paid period separately from package delivery and cancellation state.
     */
    public function get(string $subscriptionId, ?RequestOptions $options = null): EsimRecurringSubscription
    {
        return $this->single('GET', '/v1/esim/subscriptions/' . rawurlencode($subscriptionId), EsimRecurringSubscription::class, null, null, $options);
    }

    /**
     * Stops future package renewal at the current paid boundary. A period already committed remains payable. The installed profile and separately purchased packages are preserved.
     */
    public function cancel(string $subscriptionId, ?RequestOptions $options = null): EsimRecurringSubscription
    {
        return $this->single('POST', '/v1/esim/subscriptions/' . rawurlencode($subscriptionId) . '/cancel', EsimRecurringSubscription::class, null, null, $options);
    }

    /**
     * Returns funded periods with their original charges, confirmed credits, and delivery orders. Unfunded renewals do not create a paid period.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EsimRecurringPeriod>
     */
    public function periods(string $subscriptionId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EsimRecurringPeriod::class,
            fn (?string $cursor): EsimRecurringPeriodList => $this->single('GET', '/v1/esim/subscriptions/' . rawurlencode($subscriptionId) . '/periods', EsimRecurringPeriodList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EsimRecurringPeriodList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EsimRecurringPeriodList);

                return $page->getNextCursor();
            },
        );
    }
}
