<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimDeliveryList;

final class EsimDeliveries extends Resource
{
    /**
     * List the install-credential deliveries sent for this eSIM, newest first, with each delivery's status and failure code. Use this to answer "did the traveler get the email or SMS" without having consumed the webhook events.
     */
    public function list(string $esimId, ?RequestOptions $options = null): EsimDeliveryList
    {
        return $this->single('GET', '/v1/esim/sims/' . rawurlencode($esimId) . '/deliveries', EsimDeliveryList::class, null, null, $options);
    }
}
