<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimAssignment;
use MessageBird\Wire\Model\EsimAssignmentCreate;

final class EsimAssignmentResource extends Resource
{
    /**
     * Returns the assigned person. An unassigned eSIM or a resource outside this workspace returns 404.
     */
    public function get(string $esimId, ?RequestOptions $options = null): EsimAssignment
    {
        return $this->single('GET', '/v1/esim/sims/' . rawurlencode($esimId) . '/assignment', EsimAssignment::class, null, null, $options);
    }

    /**
     * Assigns an existing, allocated eSIM to a subscriber in the same workspace. Unavailable profile states return 409. Identification guidance does not gate assignment; customers handle identification collection and compliance. Repeating the same assignment returns its existing record; assigning a different person returns 409. This does not change paid packages, deliver credentials, or grant access to them.
     */
    public function create(string $esimId, EsimAssignmentCreate $params, ?RequestOptions $options = null): EsimAssignment
    {
        return $this->single('POST', '/v1/esim/sims/' . rawurlencode($esimId) . '/assignment', EsimAssignment::class, $params, null, $options);
    }
}
