<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EsimOrder;
use MessageBird\Wire\Model\EsimOrderCreate;
use MessageBird\Wire\Model\EsimOrderList;

final class EsimOrders extends Resource
{
    /**
     * Purchase an eSIM data package. Without esim_id a new eSIM is provisioned with the package; with esim_id the package is added to that eSIM. The order locks the offer's price at creation. Inspect status even on HTTP 201: the order can be completed or failed. On HTTP 202, poll until completed or failed. Omit delivery; after completion use `esim.credentials.deliver` to send install credentials to the traveler.
     */
    public function create(EsimOrderCreate $params, ?RequestOptions $options = null): EsimOrder
    {
        return $this->single('POST', '/v1/esim/orders', EsimOrder::class, $params, null, $options);
    }

    /**
     * Returns the workspace's orders as a cursor-paginated list, newest first. Filter by `status` to find in-flight or failed purchases, by `esim_id` for one eSIM's purchase history, or by `mode` to separate test purchases from real ones. Test orders are listed alongside real ones by default, each carrying its own `mode`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<EsimOrder>
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            EsimOrder::class,
            fn (?string $cursor): EsimOrderList => $this->single('GET', '/v1/esim/orders', EsimOrderList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof EsimOrderList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof EsimOrderList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Returns one order. Poll until `status` is `completed` or `failed`; a completed order names the eSIM and package it produced.
     */
    public function get(string $orderId, ?RequestOptions $options = null): EsimOrder
    {
        return $this->single('GET', '/v1/esim/orders/' . rawurlencode($orderId), EsimOrder::class, null, null, $options);
    }

    /**
     * Cancel an order waiting for funds. Inspect the returned status: an unfunded order fails with failure_code canceled; an initial recurring order whose payment was recovered continues delivery with future renewal stopped. One-time orders already funded return a conflict.
     */
    public function cancel(string $orderId, ?RequestOptions $options = null): EsimOrder
    {
        return $this->single('POST', '/v1/esim/orders/' . rawurlencode($orderId) . '/cancel', EsimOrder::class, null, null, $options);
    }
}
