<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailLookup;
use MessageBird\Wire\Model\EmailLookupRequest;
use MessageBird\Wire\Model\PhoneNumberLookup;
use MessageBird\Wire\Model\PhoneNumberLookupRequest;

final class Lookup extends Resource
{
    /**
     * Create a lookup for a phone number's networks, porting state, country, and line type. Pass `type` to request separately billed `classification`, `porting`, `presence`, `roaming`, `sim_swap`, or `score` blocks. Each block reports its own status, and only blocks with an `ok` status add a charge; the lookup does not contact the number.
     *
     * @example Look up a number, buying two extra blocks
     * $answer = $bird->lookup->phoneNumber(
     *     (new PhoneNumberLookupRequest())
     *         ->setPhoneNumber('+31612345678')
     *         ->setType(['classification', 'score']),
     * );
     * echo $answer->getCountryCode(), ' ', $answer->getLineType();
     * // Only a block whose status is ok carries a value, and only that one is billed.
     * if ($answer->getScore()?->getStatus() === 'ok') {
     *     echo $answer->getScore()->getValue();
     * }
     */
    public function phoneNumber(PhoneNumberLookupRequest $params, ?RequestOptions $options = null): PhoneNumberLookup
    {
        return $this->single('POST', '/v1/lookup/phone-number', PhoneNumberLookup::class, $params, null, $options);
    }

    /**
     * Create a deliverability lookup for one email address. Returns `result`, `delivery_confidence`, address `flags`, an undeliverable `reason`, and `did_you_mean` when a correction is available. Treat unknown `result` and `reason` values as valid additions and use `delivery_confidence` as the fallback; each completed lookup incurs the same charge.
     *
     * @example Check whether an address is worth sending to
     * $answer = $bird->lookup->email(
     *     (new EmailLookupRequest())->setEmail('aisha.khan@example.com'),
     * );
     * // result is an open vocabulary; delivery_confidence is always comparable.
     * echo $answer->getResult(), ' ', $answer->getDeliveryConfidence();
     */
    public function email(EmailLookupRequest $params, ?RequestOptions $options = null): EmailLookup
    {
        return $this->single('POST', '/v1/lookup/email', EmailLookup::class, $params, null, $options);
    }
}
