<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\EmailLookup;
use MessageBird\Wire\Model\EmailLookupRequest;
use MessageBird\Wire\Model\PhoneNumberLookup;
use MessageBird\Wire\Model\PhoneNumberLookupRequest;

final class Lookup extends Resource
{
    /**
     * Look up what a phone number is. Returns the serving network, the issuing network, whether the number was ported, its country, and its line type, free with every call. Pass `type` to buy extra blocks: `classification` (the allocated service of the range, from an intelligence source, reported beside the free `line_type` rather than replacing it), `porting` (whether the number ever moved network, when, and its full history), `presence` (reachable on the network right now), `roaming`, `sim_swap` (when the SIM last changed), and `score` (0-100 credibility). Every requested block reports its own status, and only the ones reading `ok` are billed on top of the lookup. Nothing is sent to the number.
     *
     * @example Look up a number, buying two extra blocks
     * $answer = $bird->lookup->phoneNumber(
     *     (new PhoneNumberLookupRequest())
     *         ->setPhoneNumber('+31612345678')
     *         ->setType(['classification', 'score']),
     * );
     * echo $answer->getCountryCode(), ' ', $answer->getLineType();
     * // Only a block whose status is ok carries a value, and only that one is billed.
     * if ($answer->getScore()?->getStatus() === 'ok') {
     *     echo $answer->getScore()->getValue();
     * }
     */
    public function phoneNumber(PhoneNumberLookupRequest $params, ?RequestOptions $options = null): PhoneNumberLookup
    {
        return $this->single('POST', '/v1/lookup/phone-number', PhoneNumberLookup::class, $params, null, $options);
    }

    /**
     * Look up whether an email address is worth sending to. Returns `result` (the verdict: `valid`; `neutral`, meaning it could not be confirmed either way; `risky`, meaning it will probably accept mail but is likelier than most to bounce or complain; `undeliverable`; or `typo`), `delivery_confidence` (0-100), `flags` (`role`, `disposable`, `free_provider`), `reason` on an undeliverable address (`invalid_syntax`, `invalid_domain`, `invalid_recipient`), and `did_you_mean` when the address looks like a misspelling of a real one. `result` and `reason` are OPEN vocabularies: the values listed here are today's and more may be added, so treat an unrecognized value as a future one rather than an error, falling back on `delivery_confidence`. One address per call. Every answered lookup is billed the same flat amount whatever the verdict, so treat it as a paid call rather than a free check, and use an `Idempotency-Key` so a retry does not buy a second answer. Nothing is sent to the address.
     *
     * @example Check whether an address is worth sending to
     * $answer = $bird->lookup->email(
     *     (new EmailLookupRequest())->setEmail('aisha.khan@example.com'),
     * );
     * // result is an open vocabulary; delivery_confidence is always comparable.
     * echo $answer->getResult(), ' ', $answer->getDeliveryConfidence();
     */
    public function email(EmailLookupRequest $params, ?RequestOptions $options = null): EmailLookup
    {
        return $this->single('POST', '/v1/lookup/email', EmailLookup::class, $params, null, $options);
    }
}
