<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Number;
use MessageBird\Wire\Model\NumberList;

class NumbersBase extends Resource
{
    /**
     * Pages the numbers allocated to the workspace, dedicated and shared alike. Narrows on country, type, prefix and capability, so one number is reached without walking every page.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<Number>
     *
     * @example List the numbers allocated to you
     * $page = $bird->numbers->list(['country_code' => 'GB']);
     * foreach ($page as $allocated) {
     *     // kind distinguishes a number you bought from one Bird manages.
     *     echo $allocated->getNumber(), ' ', $allocated->getKind(), ' ', $allocated->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            Number::class,
            fn (?string $cursor): NumberList => $this->single('GET', '/v1/numbers', NumberList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof NumberList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof NumberList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Reads one allocated number by the id `numbers.list` returns. Carries its status and, where a country demands ownership paperwork, what is still outstanding on it.
     *
     * @example Read one number allocated to you
     * $allocated = $bird->numbers->get('nda_01krdgeqcxet5s7t44vh8rt9mg');
     * // A country that asks for ownership paperwork answers here; most answer null.
     * echo $allocated->getStatus(), "\n";
     */
    public function get(string $numberId, ?RequestOptions $options = null): Number
    {
        return $this->single('GET', '/v1/numbers/' . rawurlencode($numberId), Number::class, null, null, $options);
    }

    /**
     * Gives a dedicated number back and stops its monthly charge. Irreversible: the number leaves the workspace and the channels built on it stop sending. A shared number cannot be released.
     *
     * @example Give a dedicated number back
     * // Releasing stops the monthly charge and the number stops working for you.
     * // Only a dedicated number can be released; a shared one answers E14002.
     * $bird->numbers->release('nda_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function release(string $numberId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/numbers/' . rawurlencode($numberId), null, null, $options);
    }
}
