<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\NumbersOrder;
use MessageBird\Wire\Model\NumbersOrderCreate;
use MessageBird\Wire\Model\NumbersOrderList;

final class NumbersOrders extends Resource
{
    /**
     * Buys a number and starts its monthly charge. Most orders settle inline; one waiting on a carrier comes back pending and is followed with `numbers.orders.get`. A setup fee already taken is not refunded if the order then fails.
     *
     * @example Buy a number
     * $order = $bird->numbers->orders->create(
     *     (new NumbersOrderCreate())->setNumber('+447700900201'),
     * );
     * // Most orders finish inside the request. One that has to wait on a carrier
     * // comes back without a number_id. Poll it until it is completed or failed.
     * if ($order->getStatus() === 'completed') {
     *     echo 'allocated as ', $order->getNumberId(), "\n";
     * } else {
     *     echo 'still ', $order->getStatus(), '; poll ', $order->getId(), "\n";
     * }
     */
    public function create(NumbersOrderCreate $params, ?RequestOptions $options = null): NumbersOrder
    {
        return $this->single('POST', '/v1/numbers/orders', NumbersOrder::class, $params, null, $options);
    }

    /**
     * Pages the workspace's purchase attempts, newest first, filtered by status. An order outlives its attempt, so a failure stays readable with the reason it carried.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<NumbersOrder>
     *
     * @example Find the purchases that did not complete
     * $page = $bird->numbers->orders->list(['status' => 'failed']);
     * foreach ($page as $order) {
     *     echo $order->getNumber(), ' ', $order->getFailureReason() ?? '', "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            NumbersOrder::class,
            fn (?string $cursor): NumbersOrderList => $this->single('GET', '/v1/numbers/orders', NumbersOrderList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof NumbersOrderList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof NumbersOrderList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Reads one order's current state, and the number it produced once completed. This is the poll for an order that came back pending.
     *
     * @example Poll an order that did not finish inline
     * $order = $bird->numbers->orders->get('nor_01krdgeqcxet5s7t44vh8rt9mg');
     * // failure_reason says what went wrong, and only ever on a failed order.
     * echo $order->getStatus(), ' ', $order->getFailureReason() ?? '', "\n";
     */
    public function get(string $orderId, ?RequestOptions $options = null): NumbersOrder
    {
        return $this->single('GET', '/v1/numbers/orders/' . rawurlencode($orderId), NumbersOrder::class, null, null, $options);
    }
}
