<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\AvailableNumber;
use MessageBird\Wire\Model\AvailableNumberList;

final class NumbersAvailable extends Resource
{
    /**
     * Searches one country's numbers on sale. Our own inventory answers first and pages; the last page can carry a live carrier snapshot, so a number seen here may be gone by the time it is ordered.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<AvailableNumber>
     *
     * @example Find a number to buy in one country
     * // The search is always country-scoped, so country_code is required.
     * $page = $bird->numbers->available->list([
     *     'country_code' => 'GB',
     *     'capabilities' => ['sms', 'voice'],
     * ]);
     * foreach ($page as $candidate) {
     *     echo $candidate->getNumber(), ' ', $candidate->getNumberType(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            AvailableNumber::class,
            fn (?string $cursor): AvailableNumberList => $this->single('GET', '/v1/numbers/available', AvailableNumberList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof AvailableNumberList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof AvailableNumberList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Re-checks one number from `numbers.available.list` against the carrier, so a stale search result is caught before it is ordered.
     *
     * @example Check one number is still for sale
     * // A number a carrier supplies is only on sale while the carrier still has it,
     * // so a 404 here means someone else took it.
     * $candidate = $bird->numbers->available->get('+447700900201');
     * echo $candidate->getCountryCode(), "\n";
     */
    public function get(string $number, ?RequestOptions $options = null): AvailableNumber
    {
        return $this->single('GET', '/v1/numbers/available/' . rawurlencode($number), AvailableNumber::class, null, null, $options);
    }
}
