<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Preference;
use MessageBird\Wire\Model\PreferenceList;

class PreferencesBase extends Resource
{
    /**
     * List the workspace's stated messaging preferences (consent grants and opt-outs) as a cursor page. Filter by channel, and by handle within a channel, to look up one person before messaging them.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<Preference>
     *
     * @example Iterate stated preferences for a handle
     * foreach ($bird->preferences->list(['channel' => 'sms', 'handle' => '+15550001234']) as $preference) {
     *     echo $preference->getStatus(), ' ', $preference->getCoverage(), PHP_EOL;
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            Preference::class,
            fn (?string $cursor): PreferenceList => $this->single('GET', '/v1/preferences', PreferenceList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof PreferenceList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof PreferenceList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Read one recorded preference by ID: the channel and handle it is about, whether it grants or revokes, how much traffic it covers, and where the statement came from.
     *
     * @example Read one recorded preference by id
     * $preference = $bird->preferences->get('prf_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $preference->getChannel(), ' ', $preference->getStatus();
     */
    public function get(string $preferenceId, ?RequestOptions $options = null): Preference
    {
        return $this->single('GET', '/v1/preferences/' . rawurlencode($preferenceId), Preference::class, null, null, $options);
    }
}
