<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\RealtimeChannelInfo;
use MessageBird\Wire\Model\RealtimeChannelMembers;
use MessageBird\Wire\Model\RealtimeChannelsList;

final class RealtimeChannels extends Resource
{
    /**
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example List active channels
     * foreach ($bird->realtime->channels->list($appId, ['prefix' => 'room-'])->getData() ?? [] as $channel) {
     *     echo $channel->getName(), ' ', $channel->getMemberCount(), "\n";
     * }
     */
    public function list(string $realtimeAppId, ?array $query = null, ?RequestOptions $options = null): RealtimeChannelsList
    {
        return $this->single('GET', '/v1/realtime/apps/' . rawurlencode($realtimeAppId) . '/channels', RealtimeChannelsList::class, null, $query, $options, ['RealtimeKey', 'RealtimeSecret']);
    }

    /**
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Inspect one channel
     * $channel = $bird->realtime->channels->get($appId, 'room-42');
     * echo $channel->getMemberCount(), ' members';
     */
    public function get(string $realtimeAppId, string $channelName, ?array $query = null, ?RequestOptions $options = null): RealtimeChannelInfo
    {
        return $this->single('GET', '/v1/realtime/apps/' . rawurlencode($realtimeAppId) . '/channels/' . rawurlencode($channelName), RealtimeChannelInfo::class, null, $query, $options, ['RealtimeKey', 'RealtimeSecret']);
    }

    /**
     * @example List a channel's members
     * foreach ($bird->realtime->channels->members($appId, 'room-42')->getMembers() ?? [] as $member) {
     *     echo $member->getMemberId(), "\n";
     * }
     */
    public function members(string $realtimeAppId, string $channelName, ?RequestOptions $options = null): RealtimeChannelMembers
    {
        return $this->single('GET', '/v1/realtime/apps/' . rawurlencode($realtimeAppId) . '/channels/' . rawurlencode($channelName) . '/members', RealtimeChannelMembers::class, null, null, $options, ['RealtimeKey', 'RealtimeSecret']);
    }
}
