<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\RealtimeBatchPublish;
use MessageBird\Wire\Model\RealtimeBatchPublishResult;
use MessageBird\Wire\Model\RealtimePublish;
use MessageBird\Wire\Model\RealtimePublishResult;

class RealtimeBase extends Resource
{
    /**
     * @example Publish an event to channels
     * $result = $bird->realtime->publish($appId, (new RealtimePublish())
     *     ->setEvent('message.created')
     *     ->setChannels(['room-42'])
     *     ->setData(['text' => 'Hello, room!']));
     * echo count($result->getData() ?? []), ' channel(s)';
     */
    public function publish(string $realtimeAppId, RealtimePublish $params, ?RequestOptions $options = null): RealtimePublishResult
    {
        return $this->single('POST', '/v1/realtime/apps/' . rawurlencode($realtimeAppId) . '/events', RealtimePublishResult::class, $params, null, $options, ['RealtimeKey', 'RealtimeSecret']);
    }

    /**
     * @example Publish several events at once
     * $batch = $bird->realtime->publishBatch($appId, (new RealtimeBatchPublish())
     *     ->setEvents([
     *         (new RealtimeBatchEvent())->setEvent('message.created')->setChannel('room-1')->setData(['text' => 'hi']),
     *         (new RealtimeBatchEvent())->setEvent('message.created')->setChannel('room-2')->setData(['text' => 'yo']),
     *     ]));
     * echo count($batch->getData() ?? []), ' event(s)';
     */
    public function publishBatch(string $realtimeAppId, RealtimeBatchPublish $params, ?RequestOptions $options = null): RealtimeBatchPublishResult
    {
        return $this->single('POST', '/v1/realtime/apps/' . rawurlencode($realtimeAppId) . '/batch-events', RealtimeBatchPublishResult::class, $params, null, $options, ['RealtimeKey', 'RealtimeSecret']);
    }
}
