<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\RealtimeMemberPublish;

final class RealtimeMembers extends Resource
{
    /**
     * @example Send an event to a single member
     * $bird->realtime->members->send($appId, 'usr_01krdgeqcxet5s7t44vh8rt9mg', (new RealtimeMemberPublish())
     *     ->setEvent('order-shipped')
     *     ->setData(['order_id' => 'ord_123']));
     */
    public function send(string $realtimeAppId, string $memberId, RealtimeMemberPublish $params, ?RequestOptions $options = null): void
    {
        $this->none('POST', '/v1/realtime/apps/' . rawurlencode($realtimeAppId) . '/members/' . rawurlencode($memberId) . '/events', $params, null, $options, ['RealtimeKey', 'RealtimeSecret']);
    }

    /**
     * @example Disconnect a member
     * $bird->realtime->members->disconnect($appId, 'usr_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function disconnect(string $realtimeAppId, string $memberId, ?RequestOptions $options = null): void
    {
        $this->none('POST', '/v1/realtime/apps/' . rawurlencode($realtimeAppId) . '/members/' . rawurlencode($memberId) . '/disconnect', null, null, $options, ['RealtimeKey', 'RealtimeSecret']);
    }
}
