<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSMessage;
use MessageBird\Wire\Model\SMSMessageList;

class SmsBase extends Resource
{
    /**
     * Get one SMS message by id: its current delivery status, segment breakdown, cost, and failure detail if it failed.
     *
     * @example Read a message back
     * $message = $bird->sms->get('sms_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $message->getStatus();
     */
    public function get(string $messageId, ?RequestOptions $options = null): SMSMessage
    {
        return $this->single('GET', '/v1/sms/messages/' . rawurlencode($messageId), SMSMessage::class, null, null, $options);
    }

    /**
     * List SMS messages, newest first, as a cursor page ({data, next_cursor, …}). Pass next_cursor back as starting_after to fetch the next page. Filter by direction, status, category, recipient, sender, or tag.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<SMSMessage>
     *
     * @example Iterate outbound messages
     * foreach ($bird->sms->list(['direction' => 'outbound']) as $message) {
     *     echo $message->getId(), ' ', $message->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            SMSMessage::class,
            fn (?string $cursor): SMSMessageList => $this->single('GET', '/v1/sms/messages', SMSMessageList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof SMSMessageList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof SMSMessageList);

                return $page->getNextCursor();
            },
        );
    }
}
