<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSKeywordRule;
use MessageBird\Wire\Model\SMSKeywordRuleCreate;
use MessageBird\Wire\Model\SMSKeywordRuleList;
use MessageBird\Wire\Model\SMSKeywordRuleUpdate;

final class SmsKeywordRules extends Resource
{
    /**
     * List the default and workspace keyword rules that apply to inbound messages, most specific first. Filter by `country`, `number`, `operation`, or `scope`. Pass `number` to see one number's rules in evaluation order. Default coverage varies by country.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     */
    public function list(?array $query = null, ?RequestOptions $options = null): SMSKeywordRuleList
    {
        return $this->single('GET', '/v1/sms/keyword-rules', SMSKeywordRuleList::class, null, $query, $options);
    }

    /**
     * Read one default or workspace keyword rule. Its ID prefix identifies which kind: a workspace rule can be changed with `sms_keyword_rules.update`, a Bird default cannot.
     */
    public function get(string $id, ?RequestOptions $options = null): SMSKeywordRule
    {
        return $this->single('GET', '/v1/sms/keyword-rules/' . rawurlencode($id), SMSKeywordRule::class, null, null, $options);
    }

    /**
     * Replace the default opt-out, opt-in, or help reply for one country, or add a `custom` keyword. A workspace rule takes precedence over the default for that country. Opt-out and opt-in keywords cannot be assigned to another operation.
     */
    public function create(SMSKeywordRuleCreate $params, ?RequestOptions $options = null): SMSKeywordRule
    {
        return $this->single('POST', '/v1/sms/keyword-rules', SMSKeywordRule::class, $params, null, $options);
    }

    /**
     * Change one of your own keyword rules: its reply, its extra keywords, or its self-managed attestation. Bird's default rules cannot be updated; create your own for that country instead with `sms_keyword_rules.create`. Omitting `keywords` leaves the set alone, while sending an empty list clears your additions back to Bird's.
     */
    public function update(string $id, SMSKeywordRuleUpdate $params, ?RequestOptions $options = null): SMSKeywordRule
    {
        return $this->single('PATCH', '/v1/sms/keyword-rules/' . rawurlencode($id), SMSKeywordRule::class, $params, null, $options);
    }

    /**
     * Delete one of your own keyword rules, which restores Bird's default for that country and operation. Bird's own rules cannot be deleted.
     */
    public function delete(string $id, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/sms/keyword-rules/' . rawurlencode($id), null, null, $options);
    }
}
