<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSStatsByCarrierResponse;
use MessageBird\Wire\Model\SMSStatsByCategoryResponse;
use MessageBird\Wire\Model\SMSStatsByCountryResponse;
use MessageBird\Wire\Model\SMSStatsByErrorCodeResponse;
use MessageBird\Wire\Model\SMSStatsByOriginatorResponse;
use MessageBird\Wire\Model\SMSStatsByStatusResponse;
use MessageBird\Wire\Model\SMSStatsByTagResponse;
use MessageBird\Wire\Model\SMSStatsResponse;
use MessageBird\Wire\Model\SMSStatsSummary;

class SmsStatsBase extends Resource
{
    /**
     * Aggregate SMS KPIs for one period: accepted, sent, delivered, undelivered, failed, rejected and expired counts, the derived delivery and failure rates, and latency percentiles. The `from` and `to` values are both YYYY-MM-DD days or both RFC 3339 instants (hour grain). Add `compare=previous_period` for deltas against the preceding window. For a per-day or per-hour series use `sms.stats.daily` or `sms.stats.hourly`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Aggregate KPIs for a window
     * $summary = $bird->sms->stats->summary(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * echo $summary->getDelivery()?->getAccepted(), ' ', $summary->getDelivery()?->getDeliveryRate();
     */
    public function summary(?array $query = null, ?RequestOptions $options = null): SMSStatsSummary
    {
        return $this->single('GET', '/v1/sms/stats/summary', SMSStatsSummary::class, null, $query, $options);
    }

    /**
     * One row of SMS lifecycle counts per calendar day, for charts and trend lines. The window is at most 365 days; set `timezone` to get local calendar days instead of UTC. Rates and latency percentiles are whole-window figures, so read those from `sms.stats.summary`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example One row per calendar day
     * $daily = $bird->sms->stats->daily(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($daily->getData() ?? [] as $point) {
     *     echo $point->getBucket(), PHP_EOL;
     * }
     */
    public function daily(?array $query = null, ?RequestOptions $options = null): SMSStatsResponse
    {
        return $this->single('GET', '/v1/sms/stats/daily', SMSStatsResponse::class, null, $query, $options);
    }

    /**
     * One row of SMS lifecycle counts per hour, for inspecting send rate and deliverability inside a single day. The window is at most 30 days (720 rows) and both bounds round down to the hour. For longer ranges use `sms.stats.daily`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example One row per hour, up to 30 days
     * $hourly = $bird->sms->stats->hourly(['from' => '2026-05-30T00:00:00Z', 'to' => '2026-05-31T00:00:00Z']);
     * foreach ($hourly->getData() ?? [] as $point) {
     *     echo $point->getBucket(), PHP_EOL;
     * }
     */
    public function hourly(?array $query = null, ?RequestOptions $options = null): SMSStatsResponse
    {
        return $this->single('GET', '/v1/sms/stats/hourly', SMSStatsResponse::class, null, $query, $options);
    }

    /**
     * SMS delivery and latency stats grouped by destination country, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to find where delivery is worst before drilling into `sms.stats.by_error_code`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Find where delivery is worst
     * $byCountry = $bird->sms->stats->byCountry([
     *     'from' => '2026-05-01',
     *     'to' => '2026-05-31',
     *     'sort' => 'delivery_rate',
     * ]);
     * foreach ($byCountry->getData() ?? [] as $row) {
     *     echo $row->getCountry(), ' ', $row->getDelivery()?->getDeliveryRate(), PHP_EOL;
     * }
     */
    public function byCountry(?array $query = null, ?RequestOptions $options = null): SMSStatsByCountryResponse
    {
        return $this->single('GET', '/v1/sms/stats/countries', SMSStatsByCountryResponse::class, null, $query, $options);
    }

    /**
     * SMS delivery and latency stats grouped by the carrier that handled the message, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to compare delivery performance across carriers.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Compare delivery across carriers
     * $byCarrier = $bird->sms->stats->byCarrier(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($byCarrier->getData() ?? [] as $row) {
     *     echo $row->getCarrier(), ' ', $row->getDelivery()?->getDelivered(), PHP_EOL;
     * }
     */
    public function byCarrier(?array $query = null, ?RequestOptions $options = null): SMSStatsByCarrierResponse
    {
        return $this->single('GET', '/v1/sms/stats/carriers', SMSStatsByCarrierResponse::class, null, $query, $options);
    }

    /**
     * SMS delivery and latency stats grouped by the category you sent under, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200).
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Split a window by category
     * $byCategory = $bird->sms->stats->byCategory(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($byCategory->getData() ?? [] as $row) {
     *     echo $row->getCategory(), ' ', $row->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function byCategory(?array $query = null, ?RequestOptions $options = null): SMSStatsByCategoryResponse
    {
        return $this->single('GET', '/v1/sms/stats/categories', SMSStatsByCategoryResponse::class, null, $query, $options);
    }

    /**
     * SMS delivery and latency stats grouped by originator, the sender address messages went out from, ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Use it to compare how your senders perform.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Compare how each sender performs
     * $byOriginator = $bird->sms->stats->byOriginator(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($byOriginator->getData() ?? [] as $row) {
     *     echo $row->getOriginator(), ' ', $row->getDelivery()?->getDeliveryRate(), PHP_EOL;
     * }
     */
    public function byOriginator(?array $query = null, ?RequestOptions $options = null): SMSStatsByOriginatorResponse
    {
        return $this->single('GET', '/v1/sms/stats/originators', SMSStatsByOriginatorResponse::class, null, $query, $options);
    }

    /**
     * How many messages ended the period in each lifecycle status: accepted, sent, delivered, undelivered, failed, rejected, expired, ordered by count. The "where did my messages end up" view, suitable for a status-distribution chart.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Where the window's messages ended up
     * $byStatus = $bird->sms->stats->byStatus(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($byStatus->getData() ?? [] as $row) {
     *     echo $row->getStatus(), ' ', $row->getCount(), PHP_EOL;
     * }
     */
    public function byStatus(?array $query = null, ?RequestOptions $options = null): SMSStatsByStatusResponse
    {
        return $this->single('GET', '/v1/sms/stats/statuses', SMSStatsByStatusResponse::class, null, $query, $options);
    }

    /**
     * SMS stats grouped by our normalized failure reason, which answers which reasons are driving your failures. The grouping key is the same value as the `error_code` filter on `sms.list`, so a row joins straight to the messages behind it. Ranked by the `sort` metric (default `failed`) and capped by `limit`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Which reasons drive failures
     * $byErrorCode = $bird->sms->stats->byErrorCode(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($byErrorCode->getData() ?? [] as $row) {
     *     // The same value as the error_code filter on $bird->sms->list().
     *     echo $row->getErrorCode(), ' ', $row->getDelivery()?->getFailed(), PHP_EOL;
     * }
     */
    public function byErrorCode(?array $query = null, ?RequestOptions $options = null): SMSStatsByErrorCodeResponse
    {
        return $this->single('GET', '/v1/sms/stats/error-codes', SMSStatsByErrorCodeResponse::class, null, $query, $options);
    }

    /**
     * SMS delivery and latency stats grouped by tag (`name:value`), ranked by the `sort` metric (default `accepted`) and capped by `limit` (default 50, maximum 200). Only tagged messages appear, and one carrying several tags counts once under each, so rows do not sum to the period total.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Compare campaigns and segments
     * $byTag = $bird->sms->stats->byTag(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($byTag->getData() ?? [] as $row) {
     *     // A message carrying several tags counts once under each, so rows do not sum
     *     // to the period total.
     *     echo $row->getTag(), ' ', $row->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function byTag(?array $query = null, ?RequestOptions $options = null): SMSStatsByTagResponse
    {
        return $this->single('GET', '/v1/sms/stats/tags', SMSStatsByTagResponse::class, null, $query, $options);
    }
}
