<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSInboundStatsByCountryResponse;
use MessageBird\Wire\Model\SMSInboundStatsByNumberResponse;
use MessageBird\Wire\Model\SMSInboundStatsByOperatorResponse;
use MessageBird\Wire\Model\SMSInboundStatsResponse;
use MessageBird\Wire\Model\SMSInboundStatsSummaryResponse;

final class SmsStatsInbound extends Resource
{
    /**
     * Total messages your numbers received over a period. For a breakdown use `sms.stats.inbound.by_country`, `sms.stats.inbound.by_operator`, or `sms.stats.inbound.by_number`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Total messages received
     * $inbound = $bird->sms->stats->inbound->summary(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * echo $inbound->getReceived();
     */
    public function summary(?array $query = null, ?RequestOptions $options = null): SMSInboundStatsSummaryResponse
    {
        return $this->single('GET', '/v1/sms/stats/inbound/summary', SMSInboundStatsSummaryResponse::class, null, $query, $options);
    }

    /**
     * Messages your numbers received, one row per calendar day. Set `timezone` to get local calendar days instead of UTC.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Received messages per day
     * $inboundDaily = $bird->sms->stats->inbound->daily(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($inboundDaily->getData() ?? [] as $point) {
     *     echo $point->getBucket(), ' ', $point->getReceived(), PHP_EOL;
     * }
     */
    public function daily(?array $query = null, ?RequestOptions $options = null): SMSInboundStatsResponse
    {
        return $this->single('GET', '/v1/sms/stats/inbound/daily', SMSInboundStatsResponse::class, null, $query, $options);
    }

    /**
     * Messages your numbers received, one row per hour, for inspecting inbound volume inside a single day.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Received messages per hour
     * $inboundHourly = $bird->sms->stats->inbound->hourly([
     *     'from' => '2026-05-30T00:00:00Z',
     *     'to' => '2026-05-31T00:00:00Z',
     * ]);
     * foreach ($inboundHourly->getData() ?? [] as $point) {
     *     echo $point->getBucket(), ' ', $point->getReceived(), PHP_EOL;
     * }
     */
    public function hourly(?array $query = null, ?RequestOptions $options = null): SMSInboundStatsResponse
    {
        return $this->single('GET', '/v1/sms/stats/inbound/hourly', SMSInboundStatsResponse::class, null, $query, $options);
    }

    /**
     * Messages your numbers received, grouped by the country of the receiving number.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Where senders messaged from
     * $inboundByCountry = $bird->sms->stats->inbound->byCountry(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($inboundByCountry->getData() ?? [] as $row) {
     *     echo $row->getCountry(), ' ', $row->getReceived(), PHP_EOL;
     * }
     */
    public function byCountry(?array $query = null, ?RequestOptions $options = null): SMSInboundStatsByCountryResponse
    {
        return $this->single('GET', '/v1/sms/stats/inbound/countries', SMSInboundStatsByCountryResponse::class, null, $query, $options);
    }

    /**
     * Messages your numbers received, grouped by the sender's mobile operator. Messages whose operator the carrier did not report are excluded, so these rows can sum to less than `sms.stats.inbound.summary` for the same period.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Received messages per operator
     * $inboundByOperator = $bird->sms->stats->inbound->byOperator(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($inboundByOperator->getData() ?? [] as $row) {
     *     // Messages whose operator the carrier did not report are excluded, so these
     *     // rows can sum to less than the inbound summary for the same period.
     *     echo $row->getMccMnc(), ' ', $row->getReceived(), PHP_EOL;
     * }
     */
    public function byOperator(?array $query = null, ?RequestOptions $options = null): SMSInboundStatsByOperatorResponse
    {
        return $this->single('GET', '/v1/sms/stats/inbound/operators', SMSInboundStatsByOperatorResponse::class, null, $query, $options);
    }

    /**
     * How many messages each of your numbers received, which is the view that shows whether a campaign's reply traffic is landing on the number you expect.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Which number took the traffic
     * $inboundByNumber = $bird->sms->stats->inbound->byNumber(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($inboundByNumber->getData() ?? [] as $row) {
     *     echo $row->getNumber(), ' ', $row->getReceived(), PHP_EOL;
     * }
     */
    public function byNumber(?array $query = null, ?RequestOptions $options = null): SMSInboundStatsByNumberResponse
    {
        return $this->single('GET', '/v1/sms/stats/inbound/numbers', SMSInboundStatsByNumberResponse::class, null, $query, $options);
    }
}
