<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSSuppression;
use MessageBird\Wire\Model\SMSSuppressionCreate;
use MessageBird\Wire\Model\SMSSuppressionList;

final class SmsSuppressions extends Resource
{
    /**
     * List the workspace's SMS suppressions (sender-and-subscriber pairs blocked from delivery) as a cursor page.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<SMSSuppression>
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            SMSSuppression::class,
            fn (?string $cursor): SMSSuppressionList => $this->single('GET', '/v1/sms/suppressions', SMSSuppressionList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof SMSSuppressionList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof SMSSuppressionList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Read one SMS suppression: the sender and subscriber it covers, why messages are stopped, what it blocks, and whether it is still in force. To check whether you may message someone, filter `sms_suppressions.list` by their number instead.
     */
    public function get(string $suppressionId, ?RequestOptions $options = null): SMSSuppression
    {
        return $this->single('GET', '/v1/sms/suppressions/' . rawurlencode($suppressionId), SMSSuppression::class, null, null, $options);
    }

    /**
     * Stop one of your senders from messaging one subscriber. Covers that sender only; your other senders keep reaching them.
     */
    public function add(SMSSuppressionCreate $params, ?RequestOptions $options = null): SMSSuppression
    {
        return $this->single('POST', '/v1/sms/suppressions', SMSSuppression::class, $params, null, $options);
    }

    /**
     * End a manual SMS suppression, letting that sender message that subscriber again. Only reason `manual` can be ended this way: a subscriber's own stop keyword and a carrier's opt-out are refused.
     */
    public function remove(string $suppressionId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/sms/suppressions/' . rawurlencode($suppressionId), null, null, $options);
    }
}
