<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSTemplateVersion;
use MessageBird\Wire\Model\SMSTemplateVersionList;
use MessageBird\Wire\Model\SMSTemplateVersionSummary;

class SmsTemplatesVersionsBase extends Resource
{
    /**
     * List a template's permanent draft and immutable published versions, newest first. Built-in templates expose their current catalogue content as one synthetic published version.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<SMSTemplateVersionSummary>
     *
     * @example Walk a template's versions
     * foreach ($bird->smsTemplates->versions->list('bird_otp_verification') as $version) {
     *     echo $version->getId(), ' ', $version->getVersionNumber(), "\n";
     * }
     */
    public function list(string $templateRef, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            SMSTemplateVersionSummary::class,
            fn (?string $cursor): SMSTemplateVersionList => $this->single('GET', '/v1/sms/templates/' . rawurlencode($templateRef) . '/versions', SMSTemplateVersionList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof SMSTemplateVersionList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof SMSTemplateVersionList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Read one draft or published SMS template version, including its variables and text in every language. Built-in templates expose their current catalogue content through a synthetic published version.
     *
     * @example Read a version's content
     * $version = $bird->smsTemplates->versions->get(
     *     'bird_otp_verification',
     *     'smv_01ky4x8e4genzb7way45txfkm1',
     * );
     * echo $version->getId(), ' ', count($version->getLanguages() ?? []);
     */
    public function get(string $templateRef, string $versionId, ?RequestOptions $options = null): SMSTemplateVersion
    {
        return $this->single('GET', '/v1/sms/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId), SMSTemplateVersion::class, null, null, $options);
    }
}
