<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSTemplateLanguage;
use MessageBird\Wire\Model\SMSTemplateLanguageList;

final class SmsTemplatesVersionsLanguages extends Resource
{
    /**
     * List a version's languages without their text. Each summary includes its revision, content hash, and last update time. Read a language item to retrieve its text.
     *
     * @example List a version's languages
     * $languages = $bird->smsTemplates->versions->languages->list(
     *     'bird_otp_verification',
     *     'smv_01ky4x8e4genzb7way45txfkm1',
     * );
     * foreach ($languages->getData() ?? [] as $language) {
     *     echo $language->getLanguage(), ' ', $language->getRevision(), "\n";
     * }
     */
    public function list(string $templateRef, string $versionId, ?RequestOptions $options = null): SMSTemplateLanguageList
    {
        return $this->single('GET', '/v1/sms/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages', SMSTemplateLanguageList::class, null, null, $options);
    }

    /**
     * Read one language's full text, revision, content hash, and update time from a draft, published version, or built-in template's synthetic version.
     *
     * @example Read one language's text
     * $language = $bird->smsTemplates->versions->languages->get(
     *     'bird_otp_verification',
     *     'smv_01ky4x8e4genzb7way45txfkm1',
     *     'en',
     * );
     * echo $language->getLanguage(), ' ', $language->getText();
     */
    public function get(string $templateRef, string $versionId, string $language, ?RequestOptions $options = null): SMSTemplateLanguage
    {
        return $this->single('GET', '/v1/sms/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages/' . rawurlencode($language), SMSTemplateLanguage::class, null, null, $options);
    }
}
