<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSTemplate;
use MessageBird\Wire\Model\SMSTemplateList;
use MessageBird\Wire\Model\SMSTemplateSummary;

class SmsTemplatesBase extends Resource
{
    /**
     * List workspace and built-in SMS templates as a cursor page. Filter by scope, category, status, language, or a search across slug, name, and description. Read a version to retrieve content and variables.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<SMSTemplateSummary>
     *
     * @example List the built-in templates
     * foreach ($bird->smsTemplates->list(['scope' => 'system']) as $template) {
     *     echo $template->getId(), ' ', $template->getSlug(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            SMSTemplateSummary::class,
            fn (?string $cursor): SMSTemplateList => $this->single('GET', '/v1/sms/templates', SMSTemplateList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof SMSTemplateList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof SMSTemplateList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Read one SMS template's metadata, language states, draft revision, and draft and live version IDs. The response omits content and variables; read a version to retrieve them.
     *
     * @example Read a template's live version
     * $template = $bird->smsTemplates->get('bird_otp_verification');
     * echo $template->getDefaultLanguage(), ' ', $template->getLiveVersionId();
     */
    public function get(string $templateRef, ?RequestOptions $options = null): SMSTemplate
    {
        return $this->single('GET', '/v1/sms/templates/' . rawurlencode($templateRef), SMSTemplate::class, null, null, $options);
    }
}
