<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\SMSTemplate;
use MessageBird\Wire\Model\SMSTemplateList;

final class SmsTemplates extends Resource
{
    /**
     * List the SMS templates available to your workspace, including our built-in templates. Filter by scope, category, or language. The catalog is small and returned in full; this list is not paginated. Use `sms_templates.get` to read one template's variables before sending with it.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example List the built-in templates
     * $templates = $bird->smsTemplates->list(['scope' => 'system']);
     * foreach ($templates->getData() ?? [] as $template) {
     *     echo $template->getId(), ' ', $template->getSlug(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): SMSTemplateList
    {
        return $this->single('GET', '/v1/sms/templates', SMSTemplateList::class, null, $query, $options);
    }

    /**
     * Get one SMS template by its slug or ID, including its body and the variables it expects. Fetch it before `sms.send` to see which parameter keys a template send requires.
     *
     * @example Read one template by slug or id
     * $template = $bird->smsTemplates->get('bird_otp_verification');
     * echo $template->getBody();
     */
    public function get(string $templateRef, ?RequestOptions $options = null): SMSTemplate
    {
        return $this->single('GET', '/v1/sms/templates/' . rawurlencode($templateRef), SMSTemplate::class, null, null, $options);
    }
}
