<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Verification;
use MessageBird\Wire\Model\VerificationCheckRequest;
use MessageBird\Wire\Model\VerificationCheckResult;
use MessageBird\Wire\Model\VerificationCreateRequest;
use MessageBird\Wire\Model\VerificationNextChannelRequest;

final class VerifyVerifications extends Resource
{
    /**
     * Start a verification and send a one-time passcode to the email address, phone number, or both in `to`. Delivery uses one planned channel at a time and fails over when necessary. Calling again for the same recipient reuses the verification in progress and sends after the resend cooldown. The passcode is never returned; submit the recipient's code with `verify.verifications.check`. SMS, WhatsApp, and Telegram delivery draw on the workspace's balance.
     *
     * @example Start a verification over SMS
     * $verification = $bird->verify->verifications->create(
     *     (new VerificationCreateRequest())->setTo((new VerificationTo())->setPhoneNumber('+15551234567')),
     * );
     * echo $verification->getId(), ' ', $verification->getStatus();
     */
    public function create(VerificationCreateRequest $params, ?RequestOptions $options = null): Verification
    {
        return $this->single('POST', '/v1/verify/verifications', Verification::class, $params, null, $options);
    }

    /**
     * Check a passcode a recipient submitted. Identify the verification by the same `to` recipient used to start it; no verification ID is needed. A wrong or expired code returns HTTP 200 with `success: false` and a `reason` (for example `incorrect_code` or `expired`). A verification that has already reached a final state is no longer checkable and returns 404, as does a missing verification; malformed input or rate limiting is also an error status.
     *
     * @example Check a submitted passcode
     * $result = $bird->verify->verifications->check(
     *     (new VerificationCheckRequest())
     *         ->setTo((new VerificationTo())->setPhoneNumber('+15551234567'))
     *         ->setCode('123456'),
     * );
     * echo $result->getSuccess() ? 'verified' : 'failed';
     */
    public function check(VerificationCheckRequest $params, ?RequestOptions $options = null): VerificationCheckResult
    {
        return $this->single('POST', '/v1/verify/verifications/check', VerificationCheckResult::class, $params, null, $options);
    }

    /**
     * Advance an in-progress verification to its next channel and send a fresh passcode. Identify it with the same `to` recipient used to create it; no verification ID is required. This bypasses the resend cooldown, and earlier passcodes remain valid. `last_channel` identifies the most recent completed send. `422 NoNextChannel` means the plan is exhausted; create the verification again to resend on the current channel.
     *
     * @example Retry on the next channel
     * $verification = $bird->verify->verifications->nextChannel(
     *     (new VerificationNextChannelRequest())->setTo((new VerificationTo())->setPhoneNumber('+15551234567')),
     * );
     * echo $verification->getLastChannel();
     */
    public function nextChannel(VerificationNextChannelRequest $params, ?RequestOptions $options = null): Verification
    {
        return $this->single('POST', '/v1/verify/verifications/next-channel', Verification::class, $params, null, $options);
    }
}
