<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Verification;
use MessageBird\Wire\Model\VerificationCheckRequest;
use MessageBird\Wire\Model\VerificationCheckResult;
use MessageBird\Wire\Model\VerificationCreateRequest;

final class VerifyVerifications extends Resource
{
    /**
     * Start a verification: generate a one-time passcode and send it to the recipient in `to` (a phone number over SMS, an email address over email, or both; with both, it is sent over one channel and fails over to the other, not to both at once). Calling again for the same recipient reuses the in-progress verification and sends a fresh code after the resend cooldown; it does not start a second one, so use this both to send and to resend. The passcode is never returned; submit what the recipient enters with verify_verifications_check. SMS delivery draws on the workspace's SMS balance.
     *
     * @example Start a verification over SMS
     * $verification = $bird->verify->verifications->create(
     *     (new VerificationCreateRequest())->setTo((new VerificationTo())->setPhoneNumber('+15551234567')),
     * );
     * echo $verification->getId(), ' ', $verification->getStatus();
     */
    public function create(VerificationCreateRequest $params, ?RequestOptions $options = null): Verification
    {
        return $this->single('POST', '/v1/verify/verifications', Verification::class, $params, null, $options);
    }

    /**
     * Check a passcode a recipient submitted. Identify the verification by the same `to` recipient used to start it; no verification id needed. A wrong or expired code returns HTTP 200 with `success: false` and a `reason` (for example `incorrect_code` or `expired`), not an error. A verification that has already reached a final state is no longer checkable and returns 404, as does a missing verification; malformed input or rate limiting is also an error status.
     *
     * @example Check a submitted passcode
     * $result = $bird->verify->verifications->check(
     *     (new VerificationCheckRequest())
     *         ->setTo((new VerificationTo())->setPhoneNumber('+15551234567'))
     *         ->setCode('123456'),
     * );
     * echo $result->getSuccess() ? 'verified' : 'failed';
     */
    public function check(VerificationCheckRequest $params, ?RequestOptions $options = null): VerificationCheckResult
    {
        return $this->single('POST', '/v1/verify/verifications/check', VerificationCheckResult::class, $params, null, $options);
    }
}
