<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Verification;
use MessageBird\Wire\Model\VerificationCheckRequest;
use MessageBird\Wire\Model\VerificationCheckResult;
use MessageBird\Wire\Model\VerificationCreateRequest;
use MessageBird\Wire\Model\VerificationNextChannelRequest;

final class VerifyVerifications extends Resource
{
    /**
     * Start a verification: generate a one-time passcode and send it to the recipient in `to` (a phone number over the phone channels enabled for its destination country; an email address over email; or both). It is sent over one channel at a time and fails over to the next in the plan, never over two at once. Calling again for the same recipient reuses the in-progress verification and sends a fresh code after the resend cooldown; it does not start a second one, so use this both to send and to resend. The passcode is never returned; submit what the recipient enters with verify_verifications_check. SMS delivery draws on the workspace's SMS balance.
     *
     * @example Start a verification over SMS
     * $verification = $bird->verify->verifications->create(
     *     (new VerificationCreateRequest())->setTo((new VerificationTo())->setPhoneNumber('+15551234567')),
     * );
     * echo $verification->getId(), ' ', $verification->getStatus();
     */
    public function create(VerificationCreateRequest $params, ?RequestOptions $options = null): Verification
    {
        return $this->single('POST', '/v1/verify/verifications', Verification::class, $params, null, $options);
    }

    /**
     * Check a passcode a recipient submitted. Identify the verification by the same `to` recipient used to start it; no verification id needed. A wrong or expired code returns HTTP 200 with `success: false` and a `reason` (for example `incorrect_code` or `expired`), not an error. A verification that has already reached a final state is no longer checkable and returns 404, as does a missing verification; malformed input or rate limiting is also an error status.
     *
     * @example Check a submitted passcode
     * $result = $bird->verify->verifications->check(
     *     (new VerificationCheckRequest())
     *         ->setTo((new VerificationTo())->setPhoneNumber('+15551234567'))
     *         ->setCode('123456'),
     * );
     * echo $result->getSuccess() ? 'verified' : 'failed';
     */
    public function check(VerificationCheckRequest $params, ?RequestOptions $options = null): VerificationCheckResult
    {
        return $this->single('POST', '/v1/verify/verifications/check', VerificationCheckResult::class, $params, null, $options);
    }

    /**
     * Advance an in-progress verification to the next channel in its plan and send a fresh passcode there: the "I didn't receive my code" action. The verification is identified by the same `to` recipient used to start it, with no verification id needed. The send bypasses the resend cooldown, and earlier passcodes stay valid. Returns the verification with `last_channel` set to the channel the new code went to; when concurrent advances race for the same recipient, the response reflects committed state: `last_channel` names the most recent completed send, and the racing call that completed the newer send is authoritative. A plan with no further channel returns a 422 named NoNextChannel, after which only re-creating the verification will resend.
     */
    public function nextChannel(VerificationNextChannelRequest $params, ?RequestOptions $options = null): Verification
    {
        return $this->single('POST', '/v1/verify/verifications/next-channel', Verification::class, $params, null, $options);
    }
}
