<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceTrunk;
use MessageBird\Wire\Model\VoiceTrunkCreate;
use MessageBird\Wire\Model\VoiceTrunkList;
use MessageBird\Wire\Model\VoiceTrunkUpdate;

class VoiceTrunksBase extends Resource
{
    /**
     * List the workspace's SIP trunks as a cursor page. Each carries the Bird-assigned `domain` the customer's equipment sends calls to. The `ip_acls` and `allowed_api_key_ids` fields control which calls are admitted; a trunk with both empty admits nothing when `session_credentials_enabled` is false. Keys listed in `ineligible_api_key_ids` cannot authenticate even though they remain bound to the trunk.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<VoiceTrunk>
     *
     * @example Find the trunk a call arrives on
     * foreach ($bird->voice->trunks->list() as $trunk) {
     *     // A trunk with no allow list and no session credentials admits nothing.
     *     echo $trunk->getId(), ' ', $trunk->getDomain() ?? 'no domain yet', "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            VoiceTrunk::class,
            fn (?string $cursor): VoiceTrunkList => $this->single('GET', '/v1/voice/trunks', VoiceTrunkList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof VoiceTrunkList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof VoiceTrunkList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Fetch one SIP trunk by ID: its `domain`, `ip_acls`, and `allowed_api_key_ids`. Use `voice.trunks.list` to find the ID.
     *
     * @example Read one trunk's configuration
     * $trunk = $bird->voice->trunks->get('trunk-id');
     * echo $trunk->getName(), ' ', $trunk->getInboundEnabled() ? 'in' : '-', "\n";
     */
    public function get(string $trunkId, ?RequestOptions $options = null): VoiceTrunk
    {
        return $this->single('GET', '/v1/voice/trunks/' . rawurlencode($trunkId), VoiceTrunk::class, null, null, $options);
    }

    /**
     * Create a new SIP trunk for the workspace. Returns the Bird-assigned domain to configure in the customer's PBX or SIP client.
     *
     * @example Register a SIP trunk
     * $trunk = $bird->voice->trunks->create(
     *     (new VoiceTrunkCreate())->setName('Lisbon office')->setOutboundEnabled(true)->setInboundEnabled(true),
     * );
     * echo $trunk->getId(), ' ', $trunk->getDomain(), "\n";
     */
    public function create(VoiceTrunkCreate $params, ?RequestOptions $options = null): VoiceTrunk
    {
        return $this->single('POST', '/v1/voice/trunks', VoiceTrunk::class, $params, null, $options);
    }

    /**
     * Change a SIP trunk's directions, name, access control and Digest offer. A direction has to be enabled before its settings can be set, and one update can do both, so this is the operation that clears `VoiceTrunkOutboundNotEnabled` and `VoiceTrunkInboundNotEnabled`. The `ip_acls`, `allowed_api_key_ids` and `digest_algorithms` fields each REPLACE their whole list, so read `voice.trunks.get` first and send the list you want to end up with. An empty array clears an allow list; an empty `digest_algorithms` array restores the default offer. Turning `inbound_enabled` off resets number routes that use this trunk to reject incoming calls. Turning it back on does not restore those routes, so confirm that change with the user first.
     *
     * @example Replace a trunk's IP allow list
     * $trunk = $bird->voice->trunks->update(
     *     'spt_01krdgeqcxet5s7t44vh8rt9mg',
     *     // Each list replaces the previous one, so send what you want to end up with.
     *     (new VoiceTrunkUpdate())->setIpAcls([
     *         (new VoiceTrunkIPACLCreate())->setCidr('203.0.113.0/24')->setDescription('Amsterdam PBX'),
     *     ]),
     * );
     * echo count($trunk->getIpAcls() ?? []), "\n";
     */
    public function update(string $trunkId, VoiceTrunkUpdate $params, ?RequestOptions $options = null): VoiceTrunk
    {
        return $this->single('PATCH', '/v1/voice/trunks/' . rawurlencode($trunkId), VoiceTrunk::class, $params, null, $options);
    }

    /**
     * Delete a SIP trunk by ID. Calls in progress are not affected; new calls cannot use the trunk. Its generated domain is not reused.
     *
     * @example Remove a trunk
     * $bird->voice->trunks->delete('trunk-id');
     */
    public function delete(string $trunkId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/voice/trunks/' . rawurlencode($trunkId), null, null, $options);
    }
}
