<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceSessionCredential;

final class VoiceSessionCredentials extends Resource
{
    /**
     * Mint a short-lived SIP digest credential a calling client authenticates with. The password is returned once and cannot be retrieved again.
     *
     * @example Mint a SIP credential
     * $credential = $bird->voice->sessionCredentials->create();
     * // The password is returned once. Until expires_at it can place billed calls.
     * echo $credential->getUsername(), ' ', $credential->getRealm(), "\n";
     */
    public function create(?RequestOptions $options = null): VoiceSessionCredential
    {
        return $this->single('POST', '/v1/voice/session-credentials', VoiceSessionCredential::class, null, null, $options);
    }
}
