<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceSettings;
use MessageBird\Wire\Model\VoiceSettingsUpdate;

final class VoiceSettingsResource extends Resource
{
    /**
     * Read the workspace's voice settings: the default inbound route that every Bird number without its own route follows, and the daily spend limit with today's usage toward it. Bird numbers whose `inbound_configuration.route` is null use this route; verified caller IDs receive no calls and never do.
     */
    public function get(?RequestOptions $options = null): VoiceSettings
    {
        return $this->single('GET', '/v1/voice/settings', VoiceSettings::class, null, null, $options);
    }

    /**
     * Change the workspace's default inbound route. Every Bird number whose own route is null follows it from the next call (verified caller IDs receive no calls): `reject` refuses those calls, `trunk` with a trunk_id delivers them to one of your SIP trunks, and `forward` with a forward_to and a forward_as connects them to one of your verified caller IDs. Numbers with a route of their own are unaffected. `daily_spend_limit.workspace_limit` sets the workspace's daily spend limit in the wallet currency, anywhere up to its `max_limit`, or null returns it to the default; calls in progress keep running. Read the wallet currency and `max_limit` with the get voice settings operation first.
     */
    public function update(VoiceSettingsUpdate $params, ?RequestOptions $options = null): VoiceSettings
    {
        return $this->single('PATCH', '/v1/voice/settings', VoiceSettings::class, $params, null, $options);
    }
}
