<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceTrunkGateway;
use MessageBird\Wire\Model\VoiceTrunkGatewayCreate;
use MessageBird\Wire\Model\VoiceTrunkGatewayList;
use MessageBird\Wire\Model\VoiceTrunkGatewayUpdate;

final class VoiceTrunksGateways extends Resource
{
    /**
     * Read the complete inbound gateway list for a trunk, ordered by priority. Available even when inbound calling is disabled.
     *
     * @example List a trunk's gateways
     * $gateways = $bird->voice->trunks->gateways->list('TRUNK_ID');
     * foreach ($gateways->getData() ?? [] as $gateway) {
     *     echo $gateway->getId(), ' ', $gateway->getPriority(), "\n";
     * }
     */
    public function list(string $trunkId, ?RequestOptions $options = null): VoiceTrunkGatewayList
    {
        return $this->single('GET', '/v1/voice/trunks/' . rawurlencode($trunkId) . '/gateways', VoiceTrunkGatewayList::class, null, null, $options);
    }

    /**
     * Read one inbound gateway and its SIP address, priority, and number formats. The gateway must belong to the specified trunk in this workspace.
     *
     * @example Read one gateway
     * $gateway = $bird->voice->trunks->gateways->get('TRUNK_ID', 'GATEWAY_ID');
     * echo $gateway->getId(), ' ', $gateway->getPriority(), "\n";
     */
    public function get(string $trunkId, string $gatewayId, ?RequestOptions $options = null): VoiceTrunkGateway
    {
        return $this->single('GET', '/v1/voice/trunks/' . rawurlencode($trunkId) . '/gateways/' . rawurlencode($gatewayId), VoiceTrunkGateway::class, null, null, $options);
    }

    /**
     * Add an address for inbound call delivery. Enable inbound calling on the trunk first; a trunk supports up to 20 gateways.
     *
     * @example Add a gateway to a trunk
     * $gateway = $bird->voice->trunks->gateways->create(
     *     'TRUNK_ID',
     *     (new VoiceTrunkGatewayCreate())
     *         ->setSipUri('sip:pbx.example.com:5060')
     *         ->setPriority(0)
     *         ->setDestinationFormat('1234#{number}'),
     * );
     * echo $gateway->getId(), ' ', $gateway->getPriority(), "\n";
     */
    public function create(string $trunkId, VoiceTrunkGatewayCreate $params, ?RequestOptions $options = null): VoiceTrunkGateway
    {
        return $this->single('POST', '/v1/voice/trunks/' . rawurlencode($trunkId) . '/gateways', VoiceTrunkGateway::class, $params, null, $options);
    }

    /**
     * Change an inbound gateway address, priority, or number formats. Omitted fields stay unchanged; an empty format restores E.164. Requires inbound calling enabled.
     *
     * @example Change a gateway's priority
     * $gateway = $bird->voice->trunks->gateways->update(
     *     'TRUNK_ID', 'GATEWAY_ID', (new VoiceTrunkGatewayUpdate())->setPriority(10),
     * );
     * echo $gateway->getId(), ' ', $gateway->getPriority(), "\n";
     */
    public function update(string $trunkId, string $gatewayId, VoiceTrunkGatewayUpdate $params, ?RequestOptions $options = null): VoiceTrunkGateway
    {
        return $this->single('PATCH', '/v1/voice/trunks/' . rawurlencode($trunkId) . '/gateways/' . rawurlencode($gatewayId), VoiceTrunkGateway::class, $params, null, $options);
    }

    /**
     * Remove an inbound gateway. Removing the last gateway stops new inbound delivery through the trunk. Requires inbound calling enabled.
     *
     * @example Remove a gateway
     * $bird->voice->trunks->gateways->delete('TRUNK_ID', 'GATEWAY_ID');
     */
    public function delete(string $trunkId, string $gatewayId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/voice/trunks/' . rawurlencode($trunkId) . '/gateways/' . rawurlencode($gatewayId), null, null, $options);
    }
}
