<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceCallerID;
use MessageBird\Wire\Model\VoiceCallerIDList;
use MessageBird\Wire\Model\VoiceCallerIDVerifyRequest;

final class VoiceCallerIds extends Resource
{
    /**
     * List the workspace's caller IDs and their verification status, as a cursor page. Only a verified caller ID may be presented on an outbound call, so an unverified or missing entry here is a common reason a call is refused.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<VoiceCallerID>
     *
     * @example List your verified caller IDs
     * foreach ($bird->voice->callerIds->list() as $callerId) {
     *     echo $callerId->getId(), ' ', $callerId->getPhoneNumber(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            VoiceCallerID::class,
            fn (?string $cursor): VoiceCallerIDList => $this->single('GET', '/v1/voice/caller-ids', VoiceCallerIDList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof VoiceCallerIDList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof VoiceCallerIDList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Fetch one caller ID by ID, with its verification status. Use `voice.caller_ids.list` to find the ID.
     *
     * @example Read one caller ID
     * $callerId = $bird->voice->callerIds->get('caller-id');
     * echo $callerId->getPhoneNumber(), ' ', $callerId->getStatus(), "\n";
     */
    public function get(string $callerId, ?RequestOptions $options = null): VoiceCallerID
    {
        return $this->single('GET', '/v1/voice/caller-ids/' . rawurlencode($callerId), VoiceCallerID::class, null, null, $options);
    }

    /**
     * Complete a caller-ID verification challenge started in the dashboard. Recovery may place another verification call and requires registration eligibility. Submit the code while ownership proof is pending. If proof was saved but outbound activation returned 412 or 503, resolve the issue and resubmit an empty object to reuse the proof. For expired or exhausted challenges, use Get a new code in the dashboard and list caller IDs to obtain the replacement ID.
     *
     * @example Submit a caller-ID verification code
     * $callerId = $bird->voice->callerIds->verify(
     *     'CALLER_ID', (new VoiceCallerIDVerifyRequest())->setCode('123456'),
     * );
     * echo $callerId->getId(), ' ', $callerId->getStatus(), "\n";
     */
    public function verify(string $callerId, VoiceCallerIDVerifyRequest $params, ?RequestOptions $options = null): VoiceCallerID
    {
        return $this->single('POST', '/v1/voice/caller-ids/' . rawurlencode($callerId) . '/verify', VoiceCallerID::class, $params, null, $options);
    }
}
