<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceCall;
use MessageBird\Wire\Model\VoiceCallList;

final class Voice extends Resource
{
    /**
     * List the workspace's calls, newest first. Filter to `ringing`/`in_progress` for the calls in progress right now, to final statuses for completed records, or to any mix of the two. Use `from`/`to` for one known party number in international form, and `number` to search either side by fragment. These are per-call records: for rates and totals over a period use voice_stats_summary rather than summing them here, and voice_get to follow one call to settlement.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<VoiceCall>
     *
     * @example Iterate the calls happening right now
     * foreach ($bird->voice->list(['status' => ['ringing', 'in_progress']]) as $call) {
     *     echo $call->getId(), ' ', $call->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        $query = self::joinCsv($query, ['status']);

        return $this->paginate(
            VoiceCall::class,
            fn (?string $cursor): VoiceCallList => $this->single('GET', '/v1/voice/calls', VoiceCallList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof VoiceCallList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof VoiceCallList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Fetch one call by id, at any point in its lifecycle. A call still ringing or connected carries no economics yet: `duration_ms`, `billable_ms`, `ended_at`, and `cost` are null until it ends, and this same id then answers with the settled record. Poll here to watch one known call; use voice_list to find calls in the first place. When a call was refused, `rejection_reason` names the gate that turned it away.
     *
     * @example Read one call back
     * $call = $bird->voice->get('vcl_01k0p3v9wera3v6q6xw3e9y2mh');
     * // A call still ringing or connected carries no economics yet.
     * echo $call->getStatus(), ' ', $call->getDurationMs() ?? 'in flight';
     */
    public function get(string $callId, ?RequestOptions $options = null): VoiceCall
    {
        return $this->single('GET', '/v1/voice/calls/' . rawurlencode($callId), VoiceCall::class, null, null, $options);
    }
}
