<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\CreateVoiceCallRequest;
use MessageBird\Wire\Model\VoiceCall;

final class VoiceCalls extends Resource
{
    /**
     * Places a real outbound call and starts the active published sequence after the recipient answers. Requires both voice management write and voice calling write permissions. Normal calling charges apply. Retain the acceptance IDs to inspect the run and initial leg.
     *
     * @example Start a published sequence call
     * $call = $bird->voice->calls->create(
     *     (new CreateVoiceCallRequest())
     *         ->setFrom('+12025550100')
     *         ->setTo('+12025550101')
     *         ->setSequence(
     *             (new CreateVoiceCallSequenceRequest())
     *                 ->setId('vsq_01krdgeqcxet5s7t44vh8rt9mg')
     *                 ->setEntryNodeId('start')
     *                 ->setTriggerData([]),
     *         ),
     * );
     * echo $call->getId(), ' ', $call->getInitialLegId();
     */
    public function create(CreateVoiceCallRequest $params, ?RequestOptions $options = null): VoiceCall
    {
        return $this->single('POST', '/v1/voice/calls', VoiceCall::class, $params, null, $options);
    }
}
