<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceDestinationList;
use MessageBird\Wire\Model\VoiceDestinationsUpdate;

final class VoiceDestinations extends Resource
{
    /**
     * Every country the Voice service supports, each marked with whether the workspace has enabled it and whether it is currently callable. A call to a country the workspace has not enabled is refused, so check here when a specific destination fails while others succeed.
     *
     * @example See which countries you may call
     * $destinations = $bird->voice->destinations->list();
     * foreach ($destinations->getData() ?? [] as $destination) {
     *     echo $destination->getCountryCode(), ' ', $destination->getEnabled() ? 'on' : 'off', "\n";
     * }
     */
    public function list(?RequestOptions $options = null): VoiceDestinationList
    {
        return $this->single('GET', '/v1/voice/destinations', VoiceDestinationList::class, null, null, $options);
    }

    /**
     * Enable or disable the countries this workspace may place voice calls to. Only the countries you list change; any country you omit keeps its current setting. Enabling one is what lets a call to it past the destination gate; disabling one refuses every call there, so confirm a disable with the user first. Read `voice.destinations.list` first for the current settings and whether Bird carries calls to the country at all.
     *
     * @example Choose which countries you may call
     * $destinations = $bird->voice->destinations->update(
     *     (new VoiceDestinationsUpdate())->setDestinations([
     *         (new DestinationSetting())->setCountryCode('PT')->setEnabled(true),
     *     ]),
     * );
     * echo count($destinations->getData() ?? []), "\n";
     */
    public function update(VoiceDestinationsUpdate $params, ?RequestOptions $options = null): VoiceDestinationList
    {
        return $this->single('PATCH', '/v1/voice/destinations', VoiceDestinationList::class, $params, null, $options);
    }
}
