<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceNumber;
use MessageBird\Wire\Model\VoiceNumberList;
use MessageBird\Wire\Model\VoiceNumberUpdate;

final class VoiceNumbers extends Resource
{
    /**
     * List every phone number the workspace can use for voice, as a cursor page ordered by number. Each entry is one phone number, with where its calls go and whether it may be presented on an outbound call.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<VoiceNumber>
     *
     * @example List the numbers you can use for voice
     * foreach ($bird->voice->numbers->list() as $number) {
     *     echo $number->getId(), ' ', $number->getPhoneNumber(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            VoiceNumber::class,
            fn (?string $cursor): VoiceNumberList => $this->single('GET', '/v1/voice/numbers', VoiceNumberList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof VoiceNumberList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof VoiceNumberList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Fetch one phone number the workspace can use for voice by id: where its calls go, whether it may be presented on an outbound call, and where it came from. Use `voice.numbers.list` to find the id.
     *
     * @example Read one number
     * $number = $bird->voice->numbers->get('number-id');
     * echo $number->getPhoneNumber(), "\n";
     */
    public function get(string $numberId, ?RequestOptions $options = null): VoiceNumber
    {
        return $this->single('GET', '/v1/voice/numbers/' . rawurlencode($numberId), VoiceNumber::class, null, null, $options);
    }

    /**
     * Change what happens to calls arriving for one number, or the workspace's own label for it. Set the route to `reject` to stop it answering, to `trunk` with a trunk_id to deliver to one of your SIP trunks, or to `forward` with a forward_to and a forward_as to place a call to one of your verified caller IDs. The route replaces whatever was set before, because a number has exactly one answer at a time, and `forward_as` must be stated on every forward. Only a number whose calls arrive at Bird can carry a route.
     *
     * @example Rename a number
     * $number = $bird->voice->numbers->update('number-id', (new VoiceNumberUpdate())->setName('Support line'));
     * echo $number->getId(), ' ', $number->getName() ?? '', "\n";
     */
    public function update(string $numberId, VoiceNumberUpdate $params, ?RequestOptions $options = null): VoiceNumber
    {
        return $this->single('PATCH', '/v1/voice/numbers/' . rawurlencode($numberId), VoiceNumber::class, $params, null, $options);
    }
}
