<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\CreateVoiceCallRequest;
use MessageBird\Wire\Model\VoiceCall;

final class VoiceCalls extends Resource
{
    /**
     * Proposes a real outbound call for browser confirmation. Requires voice_management:write and voice:write; normal calling charges apply. Set `sequence.id` to run a saved sequence's active publication, or `sequence.definition` to run a complete definition once without saving it; never both. An inline definition must pass publication checks; an invalid one is refused with a 422 naming its first problem under `/sequence/definition` only when the person runs the call. An inline run executes at most 16 commands. Supply a stable idempotency_key and reuse it with identical input for retries. The confirmation expires after 90 minutes. After the person places the call, a 202 response reserves call, leg and run IDs; it does not prove connection. Use `voice.legs.get` with `initial_leg_id` to inspect the leg outcome, and inspect the sequence run in the dashboard. Never use a new key merely because an earlier result is missing.
     *
     * @example Start a published sequence call
     * $call = $bird->voice->calls->create(
     *     (new CreateVoiceCallRequest())
     *         ->setFrom('+12025550100')
     *         ->setTo('+12025550101')
     *         ->setSequence(
     *             (new CreateVoiceCallSequenceRequest())
     *                 ->setId('vsq_01krdgeqcxet5s7t44vh8rt9mg')
     *                 ->setEntryNodeId('start')
     *                 ->setTriggerData([]),
     *         ),
     * );
     * echo $call->getId(), ' ', $call->getInitialLegId();
     */
    public function create(CreateVoiceCallRequest $params, ?RequestOptions $options = null): VoiceCall
    {
        return $this->single('POST', '/v1/voice/calls', VoiceCall::class, $params, null, $options);
    }
}
