<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceLeg;
use MessageBird\Wire\Model\VoiceLegList;

final class VoiceLegs extends Resource
{
    /**
     * List the workspace's legs, newest first. Filter to `ringing`/`in_progress` for the legs in progress right now, to final statuses for completed records, or to any mix of the two. Use `from`/`to` for one known party number in international form, and `number` to search either side by fragment. These are per-leg records and do not include aggregate rates or totals. Use `voice.legs.get` to follow one leg to settlement.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<VoiceLeg>
     *
     * @example Iterate completed legs
     * foreach ($bird->voice->legs->list() as $leg) {
     *     echo $leg->getId(), ' ', $leg->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        $query = self::joinCsv($query, ['status']);

        return $this->paginate(
            VoiceLeg::class,
            fn (?string $cursor): VoiceLegList => $this->single('GET', '/v1/voice/legs', VoiceLegList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof VoiceLegList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof VoiceLegList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Fetch one leg by ID, at any point in its lifecycle. A leg still ringing or connected carries no economics yet: `duration_ms`, `billable_ms`, `ended_at`, and `cost` are null until it ends, and the same ID then returns the settled record. Poll here to watch one known leg; use `voice.legs.list` to find legs in the first place. When a leg was refused, `rejection_reason` names the gate that turned it away.
     *
     * @example Read one call back
     * $call = $bird->voice->legs->get('vcl_01k0p3v9wera3v6q6xw3e9y2mh');
     * // A call still ringing or connected carries no economics yet.
     * echo $call->getStatus(), ' ', $call->getDurationMs() ?? 'in flight';
     */
    public function get(string $legId, ?RequestOptions $options = null): VoiceLeg
    {
        return $this->single('GET', '/v1/voice/legs/' . rawurlencode($legId), VoiceLeg::class, null, null, $options);
    }
}
