<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\VoiceVerifiedNumber;
use MessageBird\Wire\Model\VoiceVerifiedNumberList;
use MessageBird\Wire\Model\VoiceVerifiedNumberVerifyRequest;

final class VoiceVerifiedNumbers extends Resource
{
    /**
     * List the workspace's verified numbers and their verification status, as a cursor page. Only a verified number may be presented on an outbound call, so an unverified or missing entry here is a common reason a call is refused.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<VoiceVerifiedNumber>
     *
     * @example List your registered numbers
     * foreach ($bird->voice->verifiedNumbers->list() as $verifiedNumber) {
     *     echo $verifiedNumber->getId(), ' ', $verifiedNumber->getPhoneNumber(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            VoiceVerifiedNumber::class,
            fn (?string $cursor): VoiceVerifiedNumberList => $this->single('GET', '/v1/voice/verified-numbers', VoiceVerifiedNumberList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof VoiceVerifiedNumberList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof VoiceVerifiedNumberList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Fetch one verified number by ID, with its verification status. Use `voice.verified_numbers.list` to find the ID.
     *
     * @example Read one verified number
     * $verifiedNumber = $bird->voice->verifiedNumbers->get('vvn_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $verifiedNumber->getPhoneNumber(), ' ', $verifiedNumber->getStatus(), "\n";
     */
    public function get(string $verifiedNumberId, ?RequestOptions $options = null): VoiceVerifiedNumber
    {
        return $this->single('GET', '/v1/voice/verified-numbers/' . rawurlencode($verifiedNumberId), VoiceVerifiedNumber::class, null, null, $options);
    }

    /**
     * Complete a number ownership verification challenge started in the dashboard. Recovery may place another verification call and requires registration eligibility. Submit the code while ownership proof is pending. If proof was saved but outbound activation returned 412 or 503, resolve the issue and resubmit an empty object to reuse the proof. For expired or exhausted challenges, use Get a new code in the dashboard and list verified numbers to obtain the replacement ID.
     *
     * @example Submit a number verification code
     * $verifiedNumber = $bird->voice->verifiedNumbers->verify(
     *     'vvn_01krdgeqcxet5s7t44vh8rt9mg', (new VoiceVerifiedNumberVerifyRequest())->setCode('123456'),
     * );
     * echo $verifiedNumber->getId(), ' ', $verifiedNumber->getStatus(), "\n";
     */
    public function verify(string $verifiedNumberId, VoiceVerifiedNumberVerifyRequest $params, ?RequestOptions $options = null): VoiceVerifiedNumber
    {
        return $this->single('POST', '/v1/voice/verified-numbers/' . rawurlencode($verifiedNumberId) . '/verify', VoiceVerifiedNumber::class, $params, null, $options);
    }
}
