<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppNumber;
use MessageBird\Wire\Model\WhatsAppNumberEvent;
use MessageBird\Wire\Model\WhatsAppNumberEventList;
use MessageBird\Wire\Model\WhatsAppNumberList;

class WhatsappNumbersBase extends Resource
{
    /**
     * List the WhatsApp numbers the workspace can send from as a cursor page, with each number's WhatsApp state, quality rating, messaging limit, throughput, and Official Business Account status.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppNumber>
     *
     * @example See the numbers a send can go out from
     * foreach ($bird->whatsapp->numbers->list(['status' => ['connected']]) as $number) {
     *     echo $number->getId(), ' ', $number->getPhoneNumber(), ' ', $number->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppNumber::class,
            fn (?string $cursor): WhatsAppNumberList => $this->single('GET', '/v1/whatsapp/numbers', WhatsAppNumberList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppNumberList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppNumberList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Read a WhatsApp number and the state WhatsApp reports for it. `next` says what to do about that state, including the browser step that finishes a connection while `status` is `awaiting_signup`.
     *
     * @example Read one number and what WhatsApp allows it
     * $number = $bird->whatsapp->numbers->get('wan_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $number->getStatus(), ' ', $number->getQualityRating(), "\n";
     */
    public function get(string $numberId, ?RequestOptions $options = null): WhatsAppNumber
    {
        return $this->single('GET', '/v1/whatsapp/numbers/' . rawurlencode($numberId), WhatsAppNumber::class, null, null, $options);
    }

    /**
     * The activity history of one WhatsApp number as a cursor page, newest first: when it was added, every change of its status, its messaging-limit and quality-rating changes, and each display-name review decision. This is the read that answers "why did this number's status, limit, or name change"; `whatsapp.numbers.get` gives only the current values. An unknown number ID returns `404`.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppNumberEvent>
     *
     * @example Follow how a number reached its state
     * foreach ($bird->whatsapp->numbers->listEvents('wan_01krdgeqcxet5s7t44vh8rt9mg') as $event) {
     *     echo $event->getCreatedAt()?->format(DATE_ATOM), ' ', $event->getType(), "\n";
     * }
     */
    public function listEvents(string $numberId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppNumberEvent::class,
            fn (?string $cursor): WhatsAppNumberEventList => $this->single('GET', '/v1/whatsapp/numbers/' . rawurlencode($numberId) . '/events', WhatsAppNumberEventList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppNumberEventList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppNumberEventList);

                return $page->getNextCursor();
            },
        );
    }
}
