<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppInboundStatsByPhoneNumberResponse;
use MessageBird\Wire\Model\WhatsAppInboundStatsResponse;
use MessageBird\Wire\Model\WhatsAppInboundStatsSummaryResponse;

final class WhatsappStatsInbound extends Resource
{
    /**
     * Aggregate count of the WhatsApp messages your workspace received in one window, with the delta against the window immediately before when `compare` is set to `previous_period`. Inbound is counted separately from outbound: this answers "how much are customers writing to us", where `whatsapp.stats.summary` answers "how much are we sending".
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Total messages received
     * $inbound = $bird->whatsapp->stats->inbound->summary(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * echo $inbound->getReceived();
     */
    public function summary(?array $query = null, ?RequestOptions $options = null): WhatsAppInboundStatsSummaryResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/inbound/summary', WhatsAppInboundStatsSummaryResponse::class, null, $query, $options);
    }

    /**
     * Received WhatsApp message counts, one row per calendar day of the window, gap-filled so a silent day is a zero row. Days are calendar days in `timezone`, or UTC when it is omitted. Max window 365 days; `from` and `to` default to the trailing 30 days.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Received messages per day
     * $inboundDaily = $bird->whatsapp->stats->inbound->daily(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($inboundDaily->getData() ?? [] as $point) {
     *     echo $point->getBucket(), ' ', $point->getReceived(), PHP_EOL;
     * }
     */
    public function daily(?array $query = null, ?RequestOptions $options = null): WhatsAppInboundStatsResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/inbound/daily', WhatsAppInboundStatsResponse::class, null, $query, $options);
    }

    /**
     * Received WhatsApp message counts, one row per hour, gap-filled. A window spans at most 720 hours (30 days); for anything longer use `whatsapp.stats.inbound.daily`. `from` and `to` are optional RFC 3339 instants.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Received messages per hour
     * $inboundHourly = $bird->whatsapp->stats->inbound->hourly([
     *     'from' => '2026-05-30T00:00:00Z',
     *     'to' => '2026-05-31T00:00:00Z',
     * ]);
     * foreach ($inboundHourly->getData() ?? [] as $point) {
     *     echo $point->getBucket(), ' ', $point->getReceived(), PHP_EOL;
     * }
     */
    public function hourly(?array $query = null, ?RequestOptions $options = null): WhatsAppInboundStatsResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/inbound/hourly', WhatsAppInboundStatsResponse::class, null, $query, $options);
    }

    /**
     * Received WhatsApp message counts grouped by the business number that received them, ranked by volume. Use it to see which of your numbers customers actually write to. Cap the rows with `limit` (default 50, max 200).
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Which number took the traffic
     * $inboundByPhoneNumber = $bird->whatsapp->stats->inbound->byPhoneNumber(['from' => '2026-05-01', 'to' => '2026-05-31']);
     * foreach ($inboundByPhoneNumber->getData() ?? [] as $row) {
     *     echo $row->getPhoneNumber(), ' ', $row->getReceived(), PHP_EOL;
     * }
     */
    public function byPhoneNumber(?array $query = null, ?RequestOptions $options = null): WhatsAppInboundStatsByPhoneNumberResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/inbound/phone-numbers', WhatsAppInboundStatsByPhoneNumberResponse::class, null, $query, $options);
    }
}
