<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppTemplate;
use MessageBird\Wire\Model\WhatsAppTemplateList;

class WhatsappTemplatesBase extends Resource
{
    /**
     * List the workspace's WhatsApp templates: each template's handle, its lifecycle, and where each of its languages stands. Content is not included; use `whatsapp.templates.versions.get` for that.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppTemplate>
     *
     * @example Find the templates a send can name
     * foreach ($bird->whatsapp->templates->list() as $template) {
     *     echo $template->getSlug(), ' ', $template->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppTemplate::class,
            fn (?string $cursor): WhatsAppTemplateList => $this->single('GET', '/v1/whatsapp/templates', WhatsAppTemplateList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppTemplateList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppTemplateList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get one WhatsApp template by slug or ID: its handle, its lifecycle, and where each of its languages stands. Content is not included; use `whatsapp.templates.versions.get` for that.
     *
     * @example Read one template by slug
     * $template = $bird->whatsapp->templates->get('bird_otp');
     * echo $template->getDefaultLanguage();
     */
    public function get(string $templateRef, ?RequestOptions $options = null): WhatsAppTemplate
    {
        return $this->single('GET', '/v1/whatsapp/templates/' . rawurlencode($templateRef), WhatsAppTemplate::class, null, null, $options);
    }
}
