<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppKeywordRule;
use MessageBird\Wire\Model\WhatsAppKeywordRuleCreate;
use MessageBird\Wire\Model\WhatsAppKeywordRuleList;
use MessageBird\Wire\Model\WhatsAppKeywordRuleUpdate;

final class WhatsappKeywordRules extends Resource
{
    /**
     * List the keyword rules that apply to inbound WhatsApp messages, most specific first. Filter by `country`, `waba`, `operation`, or `scope`. Opt-out and opt-in work with no setup, so this returns Bird's own rules even before the workspace has configured anything.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example See what a STOP reply does
     * $rules = $bird->whatsapp->keywordRules->list(['operation' => 'opt_out']);
     * foreach ($rules->getData() ?? [] as $rule) {
     *     echo $rule->getScope(), ' ', implode(',', $rule->getEffectiveKeywords() ?? []), PHP_EOL;
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): WhatsAppKeywordRuleList
    {
        return $this->single('GET', '/v1/whatsapp/keyword-rules', WhatsAppKeywordRuleList::class, null, $query, $options);
    }

    /**
     * Read one keyword rule, Bird's own or your workspace's. Its `scope` says which: a `workspace` rule can be changed with `whatsapp.keyword_rules.update`, one of Bird's cannot.
     *
     * @example Read one rule
     * // Bird's rules and yours share the wkr_ id space; getScope() tells them apart.
     * $rule = $bird->whatsapp->keywordRules->get('wkr_01m2kj8x4te9p0rr7e5w2n1abc');
     * echo $rule->getScope(), ' ', $rule->getReply();
     */
    public function get(string $id, ?RequestOptions $options = null): WhatsAppKeywordRule
    {
        return $this->single('GET', '/v1/whatsapp/keyword-rules/' . rawurlencode($id), WhatsAppKeywordRule::class, null, null, $options);
    }

    /**
     * Replace the reply Bird sends for opt-out or opt-in, or add keywords of your own. Your rule takes precedence over Bird's at the same grain and keeps Bird's keywords unless you add more. A keyword Bird has bound to one operation cannot be reused for the other.
     *
     * @example Override Bird's opt-out reply
     * $rule = $bird->whatsapp->keywordRules->create(
     *     (new WhatsAppKeywordRuleCreate())
     *         ->setOperation('opt_out')
     *         ->setCountry('US')
     *         ->setReply("You're off the list. ACME Courier won't message you again."),
     * );
     * // getEffectiveKeywords() is Bird's set plus any of your own.
     * echo $rule->getId(), ' ', implode(',', $rule->getEffectiveKeywords() ?? []);
     */
    public function create(WhatsAppKeywordRuleCreate $params, ?RequestOptions $options = null): WhatsAppKeywordRule
    {
        return $this->single('POST', '/v1/whatsapp/keyword-rules', WhatsAppKeywordRule::class, $params, null, $options);
    }

    /**
     * Change one of your own keyword rules: its reply or its extra keywords. Bird's own rules cannot be changed; create your own instead with `whatsapp.keyword_rules.create`. Omitting `keywords` leaves the set alone, while sending an empty list clears your additions back to Bird's.
     *
     * @example Change a rule you created
     * // Omitting keywords leaves the set alone; an empty array clears your additions
     * // back to Bird's.
     * $rule = $bird->whatsapp->keywordRules->update(
     *     'wkr_01m2kj8x4te9p0rr7e5w2n1abc',
     *     (new WhatsAppKeywordRuleUpdate())->setKeywords(['no more texts', 'remove me']),
     * );
     * echo implode(',', $rule->getEffectiveKeywords() ?? []);
     */
    public function update(string $id, WhatsAppKeywordRuleUpdate $params, ?RequestOptions $options = null): WhatsAppKeywordRule
    {
        return $this->single('PATCH', '/v1/whatsapp/keyword-rules/' . rawurlencode($id), WhatsAppKeywordRule::class, $params, null, $options);
    }

    /**
     * Delete one of your own keyword rules. The next rule in the ladder answers that scope instead, which is not always one of yours: Bird's rule for the sender's country outranks your worldwide rule. The keywords the deleted rule added go with it, so a word only it matched stops matching. List the rules to read the order. Bird's rules cannot be deleted.
     *
     * @example Drop your override
     * // The next rule in the ladder answers the scope, which is another rule of yours if you hold a less specific one; STOP never stops working.
     * $bird->whatsapp->keywordRules->delete('wkr_01m2kj8x4te9p0rr7e5w2n1abc');
     */
    public function delete(string $id, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/whatsapp/keyword-rules/' . rawurlencode($id), null, null, $options);
    }
}
