<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppGroup;
use MessageBird\Wire\Model\WhatsAppGroupCreate;
use MessageBird\Wire\Model\WhatsAppGroupList;
use MessageBird\Wire\Model\WhatsAppGroupUpdate;

class WhatsappGroupsBase extends Resource
{
    /**
     * Create a WhatsApp group administered by one of your business numbers. The number must hold Official Business Account status, which `whatsapp.numbers.list` reports as is_official_business_account. The response is the accepted group with status pending; WhatsApp confirms it moments later, which is when the group gains its invite link and becomes messageable. Re-read the group until its status is active.
     *
     * @example Create a group on a business number
     * $group = $bird->whatsapp->groups->create(
     *     (new WhatsAppGroupCreate())
     *         ->setWhatsappNumberId('wan_01krdgeqcxet5s7t44vh8rt9mg')
     *         ->setSubject('Norwood Fleet — Tuesday route'),
     * );
     * echo $group->getId(), ' ', $group->getStatus(); // pending; read it back for the invite link
     */
    public function create(WhatsAppGroupCreate $params, ?RequestOptions $options = null): WhatsAppGroup
    {
        return $this->single('POST', '/v1/whatsapp/groups', WhatsAppGroup::class, $params, null, $options);
    }

    /**
     * List the WhatsApp groups your workspace created, newest first, as a cursor page. Each carries its subject, status, invite link and participant count. Filter by the business number that administers the group (number), by the WhatsApp Business Account it sends under (waba), by status, or search subjects and descriptions with q. Each group includes its participants.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppGroup>
     *
     * @example Walk the workspace's groups
     * foreach ($bird->whatsapp->groups->list() as $group) {
     *     echo $group->getId(), ' ', $group->getSubject(), PHP_EOL;
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppGroup::class,
            fn (?string $cursor): WhatsAppGroupList => $this->single('GET', '/v1/whatsapp/groups', WhatsAppGroupList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppGroupList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppGroupList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Read one WhatsApp group: its subject, description, status, invite link, and who is in it. Poll it after creating a group to see status move from pending to active, which is when the invite link appears.
     *
     * @example Read a group back until it is active
     * $group = $bird->whatsapp->groups->get('wag_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $group->getStatus(), ' ', $group->getInviteLink();
     */
    public function get(string $groupId, ?RequestOptions $options = null): WhatsAppGroup
    {
        return $this->single('GET', '/v1/whatsapp/groups/' . rawurlencode($groupId), WhatsAppGroup::class, null, null, $options);
    }

    /**
     * Change a group's subject, description or picture. Fields you omit are left alone. WhatsApp applies each field separately, so one can be refused while the others take effect. Only an active group can be changed.
     *
     * @example Rename a group
     * $group = $bird->whatsapp->groups->update(
     *     'wag_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new WhatsAppGroupUpdate())->setSubject('Norwood Fleet — Wednesday route'),
     * );
     * echo $group->getLastOperation()?->getStatus(); // pending until WhatsApp reports back
     */
    public function update(string $groupId, WhatsAppGroupUpdate $params, ?RequestOptions $options = null): WhatsAppGroup
    {
        return $this->single('PATCH', '/v1/whatsapp/groups/' . rawurlencode($groupId), WhatsAppGroup::class, $params, null, $options);
    }

    /**
     * Delete a group. Every participant loses access, including your business, and the invite link stops working. Terminal and not reversible; the group stays readable with status deleted.
     *
     * @example Delete a group
     * $group = $bird->whatsapp->groups->delete('wag_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $group->getLastOperation()?->getStatus(); // pending until WhatsApp confirms it
     */
    public function delete(string $groupId, ?RequestOptions $options = null): WhatsAppGroup
    {
        return $this->single('DELETE', '/v1/whatsapp/groups/' . rawurlencode($groupId), WhatsAppGroup::class, null, null, $options);
    }
}
