<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppGroupInviteLink;

final class WhatsappGroupsInviteLink extends Resource
{
    /**
     * Issue a new invite link for the group and invalidate every link issued before. Anyone holding an old link can no longer join. The group's current link is on the group itself, so read it rather than rotating to fetch it. Answers 200: the new link comes back on the call itself.
     *
     * @example Issue a new invite link
     * $link = $bird->whatsapp->groups->inviteLink->rotate('wag_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $link->getInviteLink(); // every earlier link has stopped working
     */
    public function rotate(string $groupId, ?RequestOptions $options = null): WhatsAppGroupInviteLink
    {
        return $this->single('POST', '/v1/whatsapp/groups/' . rawurlencode($groupId) . '/invite-link/rotate', WhatsAppGroupInviteLink::class, null, null, $options);
    }
}
