<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppBusinessAccount;
use MessageBird\Wire\Model\WhatsAppBusinessAccountList;

final class WhatsappBusinessAccounts extends Resource
{
    /**
     * List the WhatsApp Business Accounts the workspace has connected, as a cursor page, with the state WhatsApp reports for each. The `waba` a returned account carries is the same value that ties a number to its account, and the one `whatsapp.numbers.list`'s `waba` filter takes.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppBusinessAccount>
     *
     * @example List the accounts behind your senders
     * foreach ($bird->whatsapp->businessAccounts->list() as $account) {
     *     echo $account->getId(), ' ', $account->getName(), ' ', $account->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppBusinessAccount::class,
            fn (?string $cursor): WhatsAppBusinessAccountList => $this->single('GET', '/v1/whatsapp/business-accounts', WhatsAppBusinessAccountList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppBusinessAccountList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppBusinessAccountList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Read one connected WhatsApp Business Account by its `id` (`waa_` prefix) or the ID WhatsApp reports in `waba`, with the state WhatsApp reports for the account.
     *
     * @example Read one account's review state
     * $account = $bird->whatsapp->businessAccounts->get('waa_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $account->getAccountReviewStatus(), ' ', $account->getBusinessVerificationStatus(), "\n";
     */
    public function get(string $businessAccountRef, ?RequestOptions $options = null): WhatsAppBusinessAccount
    {
        return $this->single('GET', '/v1/whatsapp/business-accounts/' . rawurlencode($businessAccountRef), WhatsAppBusinessAccount::class, null, null, $options);
    }
}
