<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppGroupJoinRequest;
use MessageBird\Wire\Model\WhatsAppGroupJoinRequestDecision;
use MessageBird\Wire\Model\WhatsAppGroupJoinRequestDecisionResult;
use MessageBird\Wire\Model\WhatsAppGroupJoinRequestList;

final class WhatsappGroupsJoinRequests extends Resource
{
    /**
     * List the people waiting to be let into a group, oldest first, as a cursor page. Only a group created with join_approval_mode approval_required collects them. Decide them with the batch-approve and batch-reject operations.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppGroupJoinRequest>
     *
     * @example See who is waiting to get in
     * foreach ($bird->whatsapp->groups->joinRequests->list('wag_01krdgeqcxet5s7t44vh8rt9mg') as $request) {
     *     echo $request->getId(), ' ', $request->getBsuid(), PHP_EOL;
     * }
     */
    public function list(string $groupId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppGroupJoinRequest::class,
            fn (?string $cursor): WhatsAppGroupJoinRequestList => $this->single('GET', '/v1/whatsapp/groups/' . rawurlencode($groupId) . '/join-requests', WhatsAppGroupJoinRequestList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppGroupJoinRequestList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppGroupJoinRequestList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Approve up to 50 pending join requests in one call. WhatsApp decides each one on its own, so the response splits them into decided and failed; a failure on one leaves the rest applied.
     *
     * @example Approve a batch of join requests
     * $result = $bird->whatsapp->groups->joinRequests->approve(
     *     'wag_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new WhatsAppGroupJoinRequestDecision())->setJoinRequestIds(['wgj_01krdgeqcxet5s7t44vh8rt9mg']),
     * );
     * echo count($result->getDecided() ?? []), ' ', count($result->getFailed() ?? []);
     */
    public function approve(string $groupId, WhatsAppGroupJoinRequestDecision $params, ?RequestOptions $options = null): WhatsAppGroupJoinRequestDecisionResult
    {
        return $this->single('POST', '/v1/whatsapp/groups/' . rawurlencode($groupId) . '/join-requests/batch-approve', WhatsAppGroupJoinRequestDecisionResult::class, $params, null, $options);
    }

    /**
     * Reject up to 50 pending join requests in one call. WhatsApp decides each one on its own, so the response splits them into decided and failed; a failure on one leaves the rest applied. A group that is not active refuses the whole call with a 409 WhatsAppGroupNotActive.
     *
     * @example Reject a batch, reading the refusals
     * $result = $bird->whatsapp->groups->joinRequests->reject(
     *     'wag_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new WhatsAppGroupJoinRequestDecision())->setJoinRequestIds(['wgj_01krdgeqcxet5s7t44vh8rt9mg']),
     * );
     * foreach ($result->getFailed() ?? [] as $failure) {
     *     echo $failure->getJoinRequestId(), ' ', $failure->getError()?->getDescription(), PHP_EOL;
     * }
     */
    public function reject(string $groupId, WhatsAppGroupJoinRequestDecision $params, ?RequestOptions $options = null): WhatsAppGroupJoinRequestDecisionResult
    {
        return $this->single('POST', '/v1/whatsapp/groups/' . rawurlencode($groupId) . '/join-requests/batch-reject', WhatsAppGroupJoinRequestDecisionResult::class, $params, null, $options);
    }
}
