<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppTemplateVersion;
use MessageBird\Wire\Model\WhatsAppTemplateVersionList;
use MessageBird\Wire\Model\WhatsAppTemplateVersionSummary;

class WhatsappTemplatesVersionsBase extends Resource
{
    /**
     * List a WhatsApp template's versions, newest first. Each version is one immutable submission; an open draft, if one exists, appears alongside them. Use this to find the version a send resolves to, or the draft still being edited.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppTemplateVersionSummary>
     *
     * @example Walk a template's submissions
     * foreach ($bird->whatsapp->templates->versions->list('bird_otp') as $version) {
     *     echo $version->getId(), ' ', $version->getVersionNumber(), "\n";
     * }
     */
    public function list(string $templateRef, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppTemplateVersionSummary::class,
            fn (?string $cursor): WhatsAppTemplateVersionList => $this->single('GET', '/v1/whatsapp/templates/' . rawurlencode($templateRef) . '/versions', WhatsAppTemplateVersionList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppTemplateVersionList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppTemplateVersionList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get one version of a WhatsApp template: its submission state and the languages it carries. This is the level at which content exists.
     *
     * @example Read one version of a template
     * $version = $bird->whatsapp->templates->versions->get('bird_otp', 'wav_01ky4x8e4genzb7way45txfkm1');
     * echo $version->getVersionNumber();
     */
    public function get(string $templateRef, string $versionId, ?RequestOptions $options = null): WhatsAppTemplateVersion
    {
        return $this->single('GET', '/v1/whatsapp/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId), WhatsAppTemplateVersion::class, null, null, $options);
    }
}
