<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppReactionAccepted;
use MessageBird\Wire\Model\WhatsAppReactionEvent;
use MessageBird\Wire\Model\WhatsAppReactionEventList;
use MessageBird\Wire\Model\WhatsAppReactionUpsert;

final class WhatsappReaction extends Resource
{
    /**
     * Place an emoji reaction on a WhatsApp message the workspace received. You hold at most one reaction per message, so calling this again replaces the emoji rather than adding a second one. The message must be one the contact sent and still resolvable: Bird keeps the id a reaction needs for 15 days, so an older message is a 404. The 202 is the reaction accepted, not delivered: use whatsapp_get and read the message's `reactions` to see what stands, or whatsapp_reaction_list_events for what WhatsApp made of it.
     *
     * @example React to a received message
     * $reaction = $bird->whatsapp->reaction->set(
     *     'wam_01krdgeqcxet5s7t44vh8rt9mg',
     *     (new WhatsAppReactionUpsert())->setEmoji("\u{1F44D}"),
     * );
     * echo $reaction->getId(), ' ', $reaction->getEmoji();
     */
    public function set(string $messageId, WhatsAppReactionUpsert $params, ?RequestOptions $options = null): WhatsAppReactionAccepted
    {
        return $this->single('PUT', '/v1/whatsapp/messages/' . rawurlencode($messageId) . '/reaction', WhatsAppReactionAccepted::class, $params, null, $options);
    }

    /**
     * Take back the reaction this workspace placed on a WhatsApp message. Removing a reaction from a message you have not reacted to changes nothing and still answers 202. A removal is refused on the same grounds as a placement: a message this workspace sent is a 422, and one Bird can no longer resolve is a 404, on the same 15-day retention. The 202 is the removal accepted, not applied: the reaction leaves the message's `reactions`, readable with whatsapp_get, once WhatsApp confirms it, and whatsapp_reaction_list_events records the removal either way.
     *
     * @example Take your reaction back
     * $bird->whatsapp->reaction->remove('wam_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function remove(string $messageId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/whatsapp/messages/' . rawurlencode($messageId) . '/reaction', null, null, $options);
    }

    /**
     * Get every change made to one WhatsApp message's reactions, newest first, as a cursor page ({data, next_cursor, …}): each emoji placed, each one replaced by another, and each one taken back, by the contact and by this workspace alike. Entries carry a status, so a reaction WhatsApp refused is visible here with its error. Use whatsapp_get and read the message's `reactions` instead for what currently stands.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppReactionEvent>
     *
     * @example Follow what became of each reaction
     * foreach ($bird->whatsapp->reaction->listEvents('wam_01krdgeqcxet5s7t44vh8rt9mg') as $event) {
     *     echo $event->getId(), ' ', $event->getEmoji(), ' ', $event->getStatus(), "\n";
     * }
     */
    public function listEvents(string $messageId, ?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppReactionEvent::class,
            fn (?string $cursor): WhatsAppReactionEventList => $this->single('GET', '/v1/whatsapp/messages/' . rawurlencode($messageId) . '/reaction-events', WhatsAppReactionEventList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppReactionEventList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppReactionEventList);

                return $page->getNextCursor();
            },
        );
    }
}
