<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppSuppression;
use MessageBird\Wire\Model\WhatsAppSuppressionCreate;
use MessageBird\Wire\Model\WhatsAppSuppressionList;

final class WhatsappSuppressions extends Resource
{
    /**
     * List the workspace's recorded WhatsApp suppression addresses as a cursor page.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppSuppression>
     *
     * @example See who you will not message
     * // address is a prefix, so a partial value matches every address under it.
     * foreach ($bird->whatsapp->suppressions->list(['address' => '+1555']) as $suppression) {
     *     echo $suppression->getAddress(), ' ', $suppression->getWaba() ?? 'every account', PHP_EOL;
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppSuppression::class,
            fn (?string $cursor): WhatsAppSuppressionList => $this->single('GET', '/v1/whatsapp/suppressions', WhatsAppSuppressionList::class, null, $cursor === null ? ($query ?? []) : array_merge(array_diff_key($query ?? [], ['ending_before' => true]), ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppSuppressionList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppSuppressionList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Read one WhatsApp suppression by ID, including one that has already ended. An ended record reports when it ended and what ended it. To find a suppression by address rather than by ID, use `whatsapp.suppressions.list` with its address filter.
     *
     * @example Read one suppression
     * // Resolves a record that has already ended, which the list leaves out.
     * $suppression = $bird->whatsapp->suppressions->get('was_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $suppression->getReason(), ' ', $suppression->getEndedAt()?->format(DATE_ATOM) ?? 'still in force';
     */
    public function get(string $suppressionId, ?RequestOptions $options = null): WhatsAppSuppression
    {
        return $this->single('GET', '/v1/whatsapp/suppressions/' . rawurlencode($suppressionId), WhatsAppSuppression::class, null, null, $options);
    }

    /**
     * Record a WhatsApp address on the workspace suppression list.
     *
     * @example Stop messaging an address
     * // Omit setWaba to block the address for the whole workspace, whichever account
     * // sends. With it, your other accounts keep reaching them, and the same address
     * // for two accounts is two records.
     * $suppression = $bird->whatsapp->suppressions->add(
     *     (new WhatsAppSuppressionCreate())
     *         ->setAddress('+15550001234')
     *         ->setWaba('102290129340398'),
     * );
     * echo $suppression->getId(), ' ', $suppression->getAppliesTo();
     */
    public function add(WhatsAppSuppressionCreate $params, ?RequestOptions $options = null): WhatsAppSuppression
    {
        return $this->single('POST', '/v1/whatsapp/suppressions', WhatsAppSuppression::class, $params, null, $options);
    }

    /**
     * End one WhatsApp suppression by ID. The record is kept and stays readable. Only suppressions with reason `manual` can be ended; a recipient's own opt-out is refused.
     *
     * @example Message an address again
     * // Only a manual suppression can be ended; a recipient's own opt-out is theirs
     * // to reverse. The record is kept and still reads back by id.
     * $bird->whatsapp->suppressions->remove('was_01krdgeqcxet5s7t44vh8rt9mg');
     */
    public function remove(string $suppressionId, ?RequestOptions $options = null): void
    {
        $this->none('DELETE', '/v1/whatsapp/suppressions/' . rawurlencode($suppressionId), null, null, $options);
    }
}
