<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\Core\Page;
use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppEventList;
use MessageBird\Wire\Model\WhatsAppMessage;
use MessageBird\Wire\Model\WhatsAppMessageList;

class WhatsappBase extends Resource
{
    /**
     * Get one WhatsApp message by id: current delivery status, sent/delivered/read timestamps, the template it was sent from, and failure detail if it failed. For the per-event timeline use whatsapp_list_events.
     *
     * @example Read a message back
     * $message = $bird->whatsapp->get('wamid_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $message->getStatus();
     */
    public function get(string $messageId, ?RequestOptions $options = null): WhatsAppMessage
    {
        return $this->single('GET', '/v1/whatsapp/messages/' . rawurlencode($messageId), WhatsAppMessage::class, null, null, $options);
    }

    /**
     * List WhatsApp messages, newest first, as a cursor page ({data, next_cursor, …}). Pass next_cursor back as starting_after to fetch the next page. Filter by direction, status, contact phone number, bsuid, template category, or tag. Use whatsapp_get for one message's current state.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @return Page<WhatsAppMessage>
     *
     * @example Iterate delivered messages
     * foreach ($bird->whatsapp->list(['status' => ['delivered']]) as $message) {
     *     echo $message->getId(), ' ', $message->getStatus(), "\n";
     * }
     */
    public function list(?array $query = null, ?RequestOptions $options = null): Page
    {
        return $this->paginate(
            WhatsAppMessage::class,
            fn (?string $cursor): WhatsAppMessageList => $this->single('GET', '/v1/whatsapp/messages', WhatsAppMessageList::class, null, $cursor === null ? ($query ?? []) : array_merge($query ?? [], ['starting_after' => $cursor]), $options),
            static function (object $page): iterable {
                \assert($page instanceof WhatsAppMessageList);

                return $page->getData() ?? [];
            },
            static function (object $page): ?string {
                \assert($page instanceof WhatsAppMessageList);

                return $page->getNextCursor();
            },
        );
    }

    /**
     * Get one WhatsApp message's delivery timeline, oldest first: whatsapp.accepted, whatsapp.sent, whatsapp.delivered, whatsapp.read, and whatsapp.failed events, with failure detail on failed events. Not paginated; an unknown message id is a 404. Use whatsapp_get for the condensed current status.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Read one message's delivery timeline
     * $events = $bird->whatsapp->listEvents('wamid_01krdgeqcxet5s7t44vh8rt9mg');
     * foreach ($events->getData() ?? [] as $event) {
     *     echo $event->getType(), ' ', $event->getId(), "\n";
     * }
     */
    public function listEvents(string $messageId, ?array $query = null, ?RequestOptions $options = null): WhatsAppEventList
    {
        return $this->single('GET', '/v1/whatsapp/messages/' . rawurlencode($messageId) . '/events', WhatsAppEventList::class, null, $query, $options);
    }
}
