<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppGroup;

final class WhatsappGroupsParticipants extends Resource
{
    /**
     * Remove one person from a group, named by their business-scoped user ID or their phone number. IRREVERSIBLE: WhatsApp blocks a removed person from rejoining by invite link at all, and there is no add operation, so nothing puts them back in this group. Rotating the link does not lift it, and reaching that person again means a new group.
     *
     * @example Remove someone, permanently
     * $group = $bird->whatsapp->groups->participants->remove(
     *     'wag_01krdgeqcxet5s7t44vh8rt9mg',
     *     'BR.1566655121691972',
     * );
     * echo count($group->getParticipants() ?? []);
     */
    public function remove(string $groupId, string $participantRef, ?RequestOptions $options = null): WhatsAppGroup
    {
        return $this->single('DELETE', '/v1/whatsapp/groups/' . rawurlencode($groupId) . '/participants/' . rawurlencode($participantRef), WhatsAppGroup::class, null, null, $options);
    }
}
