<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppStatsByCountryResponse;
use MessageBird\Wire\Model\WhatsAppStatsByErrorCodeResponse;
use MessageBird\Wire\Model\WhatsAppStatsByPhoneNumberResponse;
use MessageBird\Wire\Model\WhatsAppStatsByTagResponse;
use MessageBird\Wire\Model\WhatsAppStatsByTemplateCategoryResponse;
use MessageBird\Wire\Model\WhatsAppStatsByTemplateResponse;
use MessageBird\Wire\Model\WhatsAppStatsResponse;
use MessageBird\Wire\Model\WhatsAppStatsSummary;

class WhatsappStatsBase extends Resource
{
    /**
     * Aggregate outbound WhatsApp counts for one window: accepted, sent, delivered, failed and rejected, with delivery and failure rates, read engagement, and processing and end-to-end latency percentiles. Restrict it to one dimension with `template`, `category`, `phone_number` or `tag`, one at a time, not combined. Set `compare` to `previous_period` for the deltas against the window immediately before. `from` and `to` are optional and default to the trailing 30 days. Counts are attributed to the time each message was accepted, so a delivery confirmed today counts against the day its message was accepted; `period.data_as_of` is the freshness boundary the rollups have reached.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Aggregate KPIs for a window
     * $summary = $bird->whatsapp->stats->summary([
     *     'from' => '2026-08-01',
     *     'to' => '2026-08-31',
     *     'timezone' => 'Europe/Amsterdam',
     * ]);
     * echo $summary->getDelivery()?->getAccepted(), ' ', $summary->getDelivery()?->getDelivered();
     */
    public function summary(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsSummary
    {
        return $this->single('GET', '/v1/whatsapp/stats/summary', WhatsAppStatsSummary::class, null, $query, $options);
    }

    /**
     * Outbound WhatsApp lifecycle counts, one row per calendar day of the window, gap-filled so a silent day is a zero row rather than a missing one. Every event a message produces counts against the day that message was accepted, so a row is a funnel over that day's sends and recent rows under-report while callbacks arrive. Each row carries its own latency percentiles, but delivery, failure and read rates are whole-window figures: read those from `whatsapp.stats.summary`. Accepts the same single-dimension restriction: `template`, `category`, `phone_number` or `tag`. Days are calendar days in `timezone`, or UTC when it is omitted. Max window 365 days; `from` and `to` default to the trailing 30 days.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example One row per calendar day
     * $daily = $bird->whatsapp->stats->daily(['from' => '2026-08-01', 'to' => '2026-08-31']);
     * foreach ($daily->getData() ?? [] as $point) {
     *     echo $point->getBucket(), ' ', $point->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function daily(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/daily', WhatsAppStatsResponse::class, null, $query, $options);
    }

    /**
     * Outbound WhatsApp lifecycle counts, one row per hour, gap-filled. Every event a message produces counts against the hour that message was accepted, so a row is a funnel over that hour's sends and recent rows under-report while callbacks arrive. Each row carries its own latency percentiles, but delivery, failure and read rates are whole-window figures: read those from `whatsapp.stats.summary`. Use it where the daily grain hides the shape; a window spans at most 720 hours (30 days), and for anything longer use `whatsapp.stats.daily`. Accepts the same single-dimension restriction: `template`, `category`, `phone_number` or `tag`. `from` and `to` are optional RFC 3339 instants, defaulting to the trailing 168 hours.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example One row per hour, up to 30 days
     * $hourly = $bird->whatsapp->stats->hourly(['from' => '2026-08-30T00:00:00Z', 'to' => '2026-08-31T00:00:00Z']);
     * foreach ($hourly->getData() ?? [] as $point) {
     *     echo $point->getBucket(), ' ', $point->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function hourly(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/hourly', WhatsAppStatsResponse::class, null, $query, $options);
    }

    /**
     * Failed outbound WhatsApp messages grouped by the normalized failure reason, the same value a failed message reports in `last_error.code`, ranked by volume. This is the read that answers "why are sends failing"; `whatsapp.stats.summary` gives the failure rate, this gives its composition. A send declined before handoff (insufficient balance, missing price, suppressed recipient) counts as rejected rather than failed and is absent here; read `delivery.rejected` on `whatsapp.stats.summary` for it. Rows are the whole workspace's: the breakdown takes no dimension filter. Cap the rows with `limit` (default 50, max 200).
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Which reasons drive failures
     * $byErrorCode = $bird->whatsapp->stats->byErrorCode(['from' => '2026-08-01', 'to' => '2026-08-31']);
     * foreach ($byErrorCode->getData() ?? [] as $row) {
     *     echo $row->getErrorCode(), ' ', $row->getCount(), PHP_EOL;
     * }
     */
    public function byErrorCode(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsByErrorCodeResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/error-codes', WhatsAppStatsByErrorCodeResponse::class, null, $query, $options);
    }

    /**
     * Outbound WhatsApp counts grouped by template, keyed by `template_id`, ranked by accepted volume. Resolve the id through the WhatsApp template endpoints for a name. Rows sum to less than the period's accepted total: a free-form send resolves no template, and some volume cannot be attributed to one at all, so take the denominator from `whatsapp.stats.summary`. Rows are the whole workspace's: the breakdown takes no dimension filter; to see one template over time, filter `whatsapp.stats.daily` by `template` instead. Cap the rows with `limit` (default 50, max 200).
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Rank templates by accepted volume
     * $byTemplate = $bird->whatsapp->stats->byTemplate(['from' => '2026-08-01', 'to' => '2026-08-31']);
     * foreach ($byTemplate->getData() ?? [] as $row) {
     *     echo $row->getTemplateId(), ' ', $row->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function byTemplate(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsByTemplateResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/templates', WhatsAppStatsByTemplateResponse::class, null, $query, $options);
    }

    /**
     * Outbound WhatsApp counts grouped by Meta's template category (`authentication`, `utility` and `marketing` today, and the vocabulary is open), ranked by accepted volume. Category is what WhatsApp prices a message on, so this is the breakdown that explains a spend change. A free-form send carries no category, so rows sum to less than the period's accepted total; take the denominator from `whatsapp.stats.summary`. Rows are the whole workspace's: the breakdown takes no dimension filter. Cap the rows with `limit` (default 50, max 200).
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Group by Meta's template category
     * $byTemplateCategory = $bird->whatsapp->stats->byTemplateCategory(['from' => '2026-08-01', 'to' => '2026-08-31']);
     * foreach ($byTemplateCategory->getData() ?? [] as $row) {
     *     echo $row->getCategory(), ' ', $row->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function byTemplateCategory(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsByTemplateCategoryResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/template-categories', WhatsAppStatsByTemplateCategoryResponse::class, null, $query, $options);
    }

    /**
     * Outbound WhatsApp counts grouped by the tags a send attached, ranked by accepted volume. A row's tag is `name:value`, so one tag name spreads over as many rows as it has values. Rows are the whole workspace's: the breakdown takes no dimension filter; to see one tag over time, filter `whatsapp.stats.daily` by `tag` instead. Cap the rows with `limit` (default 50, max 200).
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Compare campaigns and segments
     * $byTag = $bird->whatsapp->stats->byTag(['from' => '2026-08-01', 'to' => '2026-08-31']);
     * foreach ($byTag->getData() ?? [] as $row) {
     *     echo $row->getTag(), ' ', $row->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function byTag(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsByTagResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/tags', WhatsAppStatsByTagResponse::class, null, $query, $options);
    }

    /**
     * Outbound WhatsApp counts grouped by the business number that sent them, ranked by accepted volume, each row marked as a number your workspace connected or one Bird manages on your behalf. Use it to find the sender behind a delivery problem: a row identifies the number in E.164 form. Rows are the whole workspace's: the breakdown takes no dimension filter.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Compare how each sender number performs
     * $byPhoneNumber = $bird->whatsapp->stats->byPhoneNumber(['from' => '2026-08-01', 'to' => '2026-08-31']);
     * foreach ($byPhoneNumber->getData() ?? [] as $row) {
     *     echo $row->getPhoneNumber(), ' ', $row->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function byPhoneNumber(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsByPhoneNumberResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/phone-numbers', WhatsAppStatsByPhoneNumberResponse::class, null, $query, $options);
    }

    /**
     * Outbound WhatsApp delivery, read and latency stats grouped by the recipient's country, ranked by accepted volume. Use it to compare markets. A weak market cannot be narrowed further: no breakdown takes a country filter, so `whatsapp.stats.by_error_code` reports the workspace's failure reasons rather than the selected country's, and pairing the two is inference, not attribution. A recipient whose country cannot be resolved is counted under `ZZ`, so one-to-one sends always land somewhere. Group sends are the exception and are absent by design: one spans up to eight countries and has no single destination, so rows sum to `whatsapp.stats.summary` less that group volume. Do not report the difference as missing data. Rows are the whole workspace's: the breakdown takes no dimension filter.
     *
     * @param array<string, mixed>|null $query query parameters (untyped for now)
     *
     * @example Compare destination markets
     * $byCountry = $bird->whatsapp->stats->byCountry(['from' => '2026-08-01', 'to' => '2026-08-31']);
     * foreach ($byCountry->getData() ?? [] as $row) {
     *     echo $row->getCountry(), ' ', $row->getDelivery()?->getAccepted(), PHP_EOL;
     * }
     */
    public function byCountry(?array $query = null, ?RequestOptions $options = null): WhatsAppStatsByCountryResponse
    {
        return $this->single('GET', '/v1/whatsapp/stats/countries', WhatsAppStatsByCountryResponse::class, null, $query, $options);
    }
}
