<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppTemplateLanguage;
use MessageBird\Wire\Model\WhatsAppTemplateLanguageList;

final class WhatsappTemplatesVersionsLanguages extends Resource
{
    /**
     * List the languages one WhatsApp template version carries, with each language's review outcome at Meta and a content hash to tell which ones actually differ before fetching any of them. Use `whatsapp.templates.versions.languages.get` for a single language's content blocks.
     *
     * @example See which languages a version holds
     * $languages = $bird->whatsapp->templates->versions->languages->list('bird_otp', 'wav_01ky4x8e4genzb7way45txfkm1');
     * foreach ($languages->getData() ?? [] as $language) {
     *     echo $language->getLanguage(), ' ', $language->getStatus(), "\n";
     * }
     */
    public function list(string $templateRef, string $versionId, ?RequestOptions $options = null): WhatsAppTemplateLanguageList
    {
        return $this->single('GET', '/v1/whatsapp/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages', WhatsAppTemplateLanguageList::class, null, null, $options);
    }

    /**
     * Get one language of one WhatsApp template version: its content blocks, what this version's submission did with it, and Meta's review outcome and category for it.
     *
     * @example Read one language's content
     * $language = $bird->whatsapp->templates->versions->languages->get('bird_otp', 'wav_01ky4x8e4genzb7way45txfkm1', 'nl-BE');
     * foreach ($language->getComponents() ?? [] as $component) {
     *     echo $component->getType(), "\n";
     * }
     */
    public function get(string $templateRef, string $versionId, string $language, ?RequestOptions $options = null): WhatsAppTemplateLanguage
    {
        return $this->single('GET', '/v1/whatsapp/templates/' . rawurlencode($templateRef) . '/versions/' . rawurlencode($versionId) . '/languages/' . rawurlencode($language), WhatsAppTemplateLanguage::class, null, null, $options);
    }
}
