<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\WhatsAppNumberProfile;

final class WhatsappNumbersProfile extends Resource
{
    /**
     * Read the business profile WhatsApp shows to people a connected number messages.
     *
     * @example Read the profile people see in WhatsApp
     * $profile = $bird->whatsapp->numbers->profile->get('wan_01krdgeqcxet5s7t44vh8rt9mg');
     * echo $profile->getDisplayName(), ' ', $profile->getDescription(), "\n";
     */
    public function get(string $numberId, ?RequestOptions $options = null): WhatsAppNumberProfile
    {
        return $this->single('GET', '/v1/whatsapp/numbers/' . rawurlencode($numberId) . '/profile', WhatsAppNumberProfile::class, null, null, $options);
    }
}
