<?php

declare(strict_types=1);

// Code generated by surface-gen; DO NOT EDIT.

namespace MessageBird\Resources;

use MessageBird\RequestOptions;
use MessageBird\Wire\Model\Workspace;

final class WorkspaceResource extends Resource
{
    /**
     * Fetch the current workspace's ID, name, and the ID of the organization owning it. This is the workspace the current credentials are scoped to.
     *
     * @example Read the workspace this credential is scoped to
     * $workspace = $bird->workspace->get();
     * echo $workspace->getId() . ' ' . $workspace->getName() . PHP_EOL;
     */
    public function get(?RequestOptions $options = null): Workspace
    {
        return $this->single('GET', '/v1/workspace', Workspace::class, null, null, $options);
    }
}
